### PR TITLE
Use shared informer for await logic for deployments

### LINKED ISSUE #1628: `pulumi up` stuck on "Waiting for app ReplicaSet be marked available"
I've recently had issues with pulumi hanging (or timing out) when attempting to deploy changes.
Our stack has 8 deployments. Some of them get updated, others fail. The number varies. Usually 2-4 are successfully updated.

On the kubernetes side, it appears as if the deployment has been successful.

### Versions info
OS: macos
Pulumi CLI: 3.5.1
Python: 3.7.3
Python package versions
 - pulumi: 3.5.1
 - pulumi-kubernetes: 3.4.0

k8s: 1.17 on AWS EKS

Here's the output after a failed deployment:
```
Updating (dev-delta-api):
     Type                                 Name                                  Status                  Info
     pulumi:pulumi:Stack                  grid-api-dev-delta-api                **failed**              1 error
 ~   ├─ pulumi-python:dynamic:Resource    grid-api-ecr-image                    updated                 [diff: ~image_name]
 ~   ├─ kubernetes:batch/v1beta1:CronJob  grid-api                              updated                 [diff: ~spec]
 ~   ├─ kubernetes:apps/v1:Deployment     grid-api                              updated                 [diff: ~spec]
 ~   ├─ kubernetes:apps/v1:Deployment     grid-api-thumbnail-worker             updated                 [diff: ~spec]
 ~   ├─ kubernetes:apps/v1:Deployment     grid-api-regenerate-thumbnail-worker  **updating failed**     [diff: ~spec]; 1 error
 ~   ├─ kubernetes:apps/v1:Deployment     grid-api-gdrive-monitor-worker        **updating failed**     [diff: ~spec]; 1 error
 ~   ├─ kubernetes:apps/v1:Deployment     grid-api-cloud-drive-refresh-worker   **updating failed**     [diff: ~spec]; 1 error
 ~   ├─ kubernetes:apps/v1:Deployment     grid-api-document-analytics-writer    **updating failed**     [diff: ~spec]; 1 error
 ~   ├─ kubernetes:apps/v1:Deployment     grid-api-chargebee-webhook-worker     **updating failed**     [diff: ~spec]; 1 error
 ~   └─ kubernetes:apps/v1:Deployment     grid-api-orphaned-workbook-remover    **updating failed**     [diff: ~spec]; 1 error

Diagnostics:
  kubernetes:apps/v1:Deployment (grid-api-document-analytics-writer):
    error: 2 errors occurred:
    	* the Kubernetes API server reported that "grid-api-document-analytics-writer" failed to fully initialize or become live: 'grid-api-document-analytics-writer' timed out waiting to be Ready
    	* Attempted to roll forward to new ReplicaSet, but minimum number of Pods did not become live

  kubernetes:apps/v1:Deployment (grid-api-chargebee-webhook-worker):
    error: 2 errors occurred:
    	* the Kubernetes API server reported that "grid-api-chargebee-webhook-worker" failed to fully initialize or become live: 'grid-api-chargebee-webhook-worker' timed out waiting to be Ready
    	* Attempted to roll forward to new ReplicaSet, but minimum number of Pods did not become live

  pulumi:pulumi:Stack (grid-api-dev-delta-api):
    error: update failed

  kubernetes:apps/v1:Deployment (grid-api-orphaned-workbook-remover):
    error: 2 errors occurred:
    	* the Kubernetes API server reported that "grid-api-orphaned-workbook-remover" failed to fully initialize or become live: 'grid-api-orphaned-workbook-remover' timed out waiting to be Ready
    	* Attempted to roll forward to new ReplicaSet, but minimum number of Pods did not become live

  kubernetes:apps/v1:Deployment (grid-api-regenerate-thumbnail-worker):
    error: 2 errors occurred:
    	* the Kubernetes API server reported that "grid-api-regenerate-thumbnail-worker" failed to fully initialize or become live: 'grid-api-regenerate-thumbnail-worker' timed out waiting to be Ready
    	* Attempted to roll forward to new ReplicaSet, but minimum number of Pods did not become live

  kubernetes:apps/v1:Deployment (grid-api-gdrive-monitor-worker):
    error: 2 errors occurred:
    	* the Kubernetes API server reported that "grid-api-gdrive-monitor-worker" failed to fully initialize or become live: 'grid-api-gdrive-monitor-worker' timed out waiting to be Ready
    	* Attempted to roll forward to new ReplicaSet, but minimum number of Pods did not become live

  kubernetes:apps/v1:Deployment (grid-api-cloud-drive-refresh-worker):
    error: 2 errors occurred:
    	* the Kubernetes API server reported that "grid-api-cloud-drive-refresh-worker" failed to fully initialize or become live: 'grid-api-cloud-drive-refresh-worker' timed out waiting to be Ready
    	* Attempted to roll forward to new ReplicaSet, but minimum number of Pods did not become live

Resources:
    ~ 4 updated
    4 unchanged

Duration: 10m17s
```

While I was waiting for the deployment to complete, I ran `kubectl get deploy` and `kubectl get rs`
```
(⎈ |dev-delta)~❯ kubectl get deploy
NAME                                   READY   UP-TO-DATE   AVAILABLE   AGE
document-thumbnailer                   2/2     2            2           270d
excel-processor                        2/2     2            2           270d
grid-api                               3/3     3            3           269d
grid-api-chargebee-webhook-worker      1/1     1            1           98d
grid-api-cloud-drive-refresh-worker    1/1     1            1           115d
grid-api-document-analytics-writer     1/1     1            1           109d
grid-api-gdrive-monitor-worker         1/1     1            1           153d
grid-api-orphaned-workbook-remover     1/1     1            1           40d
grid-api-regenerate-thumbnail-worker   1/1     1            1           5d20h
grid-api-thumbnail-worker              1/1     1            1           269d
grid-api2                              1/1     1            1           248d
grid-api2-thumbnail-worker             0/0     0            0           248d
grid-client                            2/2     2            2           269d
nginx-proxy                            1/1     1            1           272d
traefik-router                         2/2     2            2           272d
(⎈ |dev-delta)~❯ kubectl get rs
NAME                                              DESIRED   CURRENT   READY   AGE
document-thumbnailer-5787bb49b5                   0         0         0       6d17h
document-thumbnailer-5d4d8f55bc                   0         0         0       63d
document-thumbnailer-6559d8649c                   2         2         2       6d16h
document-thumbnailer-659f5c67bf                   0         0         0       52d
document-thumbnailer-668f44f684                   0         0         0       214d
document-thumbnailer-74b8bd4d59                   0         0         0       53d
document-thumbnailer-75477cd55                    0         0         0       222d
document-thumbnailer-7974f57c89                   0         0         0       6d17h
document-thumbnailer-7c584ff45                    0         0         0       203d
document-thumbnailer-9c77fc8c6                    0         0         0       12d
document-thumbnailer-bff5fc75c                    0         0         0       221d
excel-processor-54fcd89bc6                        2         2         2       5d22h
excel-processor-5867f648dd                        0         0         0       6d17h
excel-processor-5fd65b7db7                        0         0         0       34d
excel-processor-64f6d866                          0         0         0       6d17h
excel-processor-65f68d8f69                        0         0         0       12d
excel-processor-6cb97d9d74                        0         0         0       13d
excel-processor-6fc6599f96                        0         0         0       12d
excel-processor-6fc76887fd                        0         0         0       11d
excel-processor-786b55c779                        0         0         0       20d
excel-processor-86697b4cb4                        0         0         0       20d
excel-processor-f58f854c5                         0         0         0       12d
grid-api-58c8d4cb7c                               0         0         0       5d21h
grid-api-58d57688c8                               0         0         0       5d20h
grid-api-5b4b666bb                                0         0         0       2d16h
grid-api-5c45dd78c9                               0         0         0       3d18h
grid-api-5cf8458c84                               0         0         0       4d15h
grid-api-6cfcdbbc64                               0         0         0       10h
grid-api-6dc5c7559f                               0         0         0       3d20h
grid-api-6dd9cc7889                               3         3         3       15h
grid-api-7644cd5475                               0         0         0       21h
grid-api-chargebee-webhook-worker-586c9c9754      0         0         0       18h
grid-api-chargebee-webhook-worker-5b7d7c6b67      0         0         0       5d22h
grid-api-chargebee-webhook-worker-5d86974455      0         0         0       5d21h
grid-api-chargebee-webhook-worker-5df6b68db7      0         0         0       16h
grid-api-chargebee-webhook-worker-65cd958846      0         0         0       10h
grid-api-chargebee-webhook-worker-69ccc7b4bd      0         0         0       2d16h
grid-api-chargebee-webhook-worker-6f5ff7459       1         1         1       15h
grid-api-chargebee-webhook-worker-6f8dc59f77      0         0         0       21h
grid-api-chargebee-webhook-worker-7c9dcb5966      0         0         0       4d15h
grid-api-chargebee-webhook-worker-7d97d9f876      0         0         0       5d20h
grid-api-chargebee-webhook-worker-7f8fdcd66f      0         0         0       3d20h
grid-api-cloud-drive-refresh-worker-549bc7f995    1         1         1       15h
grid-api-cloud-drive-refresh-worker-58cb8fb777    0         0         0       3d20h
grid-api-cloud-drive-refresh-worker-598974547     0         0         0       16h
grid-api-cloud-drive-refresh-worker-65945bdd95    0         0         0       5d21h
grid-api-cloud-drive-refresh-worker-6c79cc4cf8    0         0         0       18h
grid-api-cloud-drive-refresh-worker-6cbd645cf4    0         0         0       4d15h
grid-api-cloud-drive-refresh-worker-7b648bcdd     0         0         0       5d20h
grid-api-cloud-drive-refresh-worker-7c845f85bd    0         0         0       2d16h
grid-api-cloud-drive-refresh-worker-7d65d75c46    0         0         0       10h
grid-api-cloud-drive-refresh-worker-986fdf449     0         0         0       21h
grid-api-cloud-drive-refresh-worker-fc67f56c      0         0         0       5d22h
grid-api-ddb49db4f                                0         0         0       16h
grid-api-document-analytics-writer-5484d944db     0         0         0       21h
grid-api-document-analytics-writer-549f4f8567     0         0         0       10h
grid-api-document-analytics-writer-57b65bd65f     0         0         0       18h
grid-api-document-analytics-writer-57cb9fb9b9     0         0         0       2d16h
grid-api-document-analytics-writer-59c46d8d48     0         0         0       5d22h
grid-api-document-analytics-writer-5df8fc4cd8     0         0         0       16h
grid-api-document-analytics-writer-696b6fccb5     0         0         0       5d20h
grid-api-document-analytics-writer-6bc5c84988     1         1         1       15h
grid-api-document-analytics-writer-74fc7b76ff     0         0         0       4d15h
grid-api-document-analytics-writer-7954646894     0         0         0       3d20h
grid-api-document-analytics-writer-84f5ff7ddd     0         0         0       5d21h
grid-api-ff5fb75dd                                0         0         0       18h
grid-api-gdrive-monitor-worker-54494b89f7         0         0         0       5d22h
grid-api-gdrive-monitor-worker-5587bc8695         0         0         0       21h
grid-api-gdrive-monitor-worker-57fcb8495d         0         0         0       18h
grid-api-gdrive-monitor-worker-66bdd688cc         0         0         0       5d21h
grid-api-gdrive-monitor-worker-6cc69dfd6c         0         0         0       3d20h
grid-api-gdrive-monitor-worker-767ddb57c          1         1         1       15h
grid-api-gdrive-monitor-worker-768796d7cb         0         0         0       2d16h
grid-api-gdrive-monitor-worker-7879cdc974         0         0         0       10h
grid-api-gdrive-monitor-worker-7b75b8b557         0         0         0       16h
grid-api-gdrive-monitor-worker-84bdc587b          0         0         0       5d20h
grid-api-gdrive-monitor-worker-99b4dd598          0         0         0       4d15h
grid-api-orphaned-workbook-remover-556586c88      0         0         0       2d16h
grid-api-orphaned-workbook-remover-556697cfdc     0         0         0       21h
grid-api-orphaned-workbook-remover-59d4c6588f     0         0         0       5d21h
grid-api-orphaned-workbook-remover-5c8db59dbc     0         0         0       3d20h
grid-api-orphaned-workbook-remover-6588cc77fc     0         0         0       5d22h
grid-api-orphaned-workbook-remover-6b76cbd7b6     0         0         0       18h
grid-api-orphaned-workbook-remover-6f9b74c6d8     0         0         0       5d20h
grid-api-orphaned-workbook-remover-78758c47c      1         1         1       15h
grid-api-orphaned-workbook-remover-78b84b8bcd     0         0         0       4d15h
grid-api-orphaned-workbook-remover-7d8dd98cc8     0         0         0       10h
grid-api-orphaned-workbook-remover-9cb68c67c      0         0         0       16h
grid-api-regenerate-thumbnail-worker-58d947559f   0         0         0       18h
grid-api-regenerate-thumbnail-worker-64487cbd98   0         0         0       3d20h
grid-api-regenerate-thumbnail-worker-69b58765d9   0         0         0       2d16h
grid-api-regenerate-thumbnail-worker-6d9d4d9db7   0         0         0       10h
grid-api-regenerate-thumbnail-worker-74844bf9c6   0         0         0       16h
grid-api-regenerate-thumbnail-worker-777c4fd55b   1         1         1       15h
grid-api-regenerate-thumbnail-worker-7d8655496c   0         0         0       4d15h
grid-api-regenerate-thumbnail-worker-bf7fcb849    0         0         0       5d20h
grid-api-regenerate-thumbnail-worker-db8f65c4     0         0         0       21h
grid-api-thumbnail-worker-574f59674d              0         0         0       10h
grid-api-thumbnail-worker-5987d4956b              0         0         0       2d16h
grid-api-thumbnail-worker-59c6cc7cf6              0         0         0       18h
grid-api-thumbnail-worker-5d4f79c85               0         0         0       5d22h
grid-api-thumbnail-worker-5d6d95dffc              1         1         1       15h
grid-api-thumbnail-worker-687f9669f               0         0         0       21h
grid-api-thumbnail-worker-6f48ff74fc              0         0         0       5d21h
grid-api-thumbnail-worker-767f7dd649              0         0         0       16h
grid-api-thumbnail-worker-76f8865894              0         0         0       5d20h
grid-api-thumbnail-worker-7f985d7d88              0         0         0       4d15h
grid-api-thumbnail-worker-8c8c87847               0         0         0       3d20h
grid-api2-54879b9bf9                              0         0         0       223d
grid-api2-5c66fdddb4                              0         0         0       228d
grid-api2-657f59c995                              0         0         0       223d
grid-api2-664688b765                              0         0         0       236d
grid-api2-694bc66649                              1         1         1       185d
grid-api2-69c8449d9c                              0         0         0       236d
grid-api2-74dd495fdc                              0         0         0       185d
grid-api2-845ccb8f55                              0         0         0       248d
grid-api2-85f4c6b789                              0         0         0       222d
grid-api2-97675df68                               0         0         0       223d
grid-api2-bfc9fcc99                               0         0         0       223d
grid-api2-thumbnail-worker-59479ccd5f             0         0         0       236d
grid-api2-thumbnail-worker-5b7649ffc7             0         0         0       236d
grid-api2-thumbnail-worker-5bbdc7fff4             0         0         0       236d
grid-api2-thumbnail-worker-658898d85              0         0         0       248d
grid-api2-thumbnail-worker-6798b9b984             0         0         0       185d
grid-api2-thumbnail-worker-7d456fb6f8             0         0         0       222d
grid-api2-thumbnail-worker-7f85445b48             0         0         0       223d
grid-api2-thumbnail-worker-7f96f8bc8f             0         0         0       228d
grid-api2-thumbnail-worker-857c7698d9             0         0         0       223d
grid-api2-thumbnail-worker-859cbb6b6d             0         0         0       223d
grid-api2-thumbnail-worker-97b4b84bd              0         0         0       223d
grid-client-56cc6557db                            0         0         0       5d14h
grid-client-585856bb66                            0         0         0       5d15h
grid-client-5ff555c88c                            0         0         0       15h
grid-client-66458dcf47                            0         0         0       3d18h
grid-client-6d4f7d7f4c                            0         0         0       16h
grid-client-6d69478b9b                            2         2         2       9h
grid-client-7db7979fcf                            0         0         0       16h
grid-client-7f894448cd                            0         0         0       5d15h
grid-client-7f9f4c7b8                             0         0         0       3d20h
grid-client-9dd8bdfcd                             0         0         0       15h
grid-client-f555db5f7                             0         0         0       20h
nginx-proxy-566f4bb4f5                            0         0         0       12d
nginx-proxy-5b5cdf87c8                            0         0         0       5d17h
nginx-proxy-6894ccf656                            0         0         0       35d
nginx-proxy-6d76459864                            0         0         0       126d
nginx-proxy-755fd9bc95                            0         0         0       122d
nginx-proxy-7cc8c9d7df                            0         0         0       146d
nginx-proxy-7d69f64bbc                            0         0         0       157d
nginx-proxy-846c44f5c4                            1         1         1       15h
nginx-proxy-854d95c659                            0         0         0       122d
nginx-proxy-85755b9dcc                            0         0         0       126d
nginx-proxy-85d59cd96b                            0         0         0       16h
traefik-router-67cbbd787f                         2         2         2       91d
traefik-router-86c7fd6f89                         0         0         0       272d
```

### PR DESCRIPTION
**Pull request by viveklak**
Builds on #1634.

Fixes #1628 

Note - the current iteration launches an informer per deployment instead of having a provider level informer. This is still a pretty significant improvement since all replicasets, pods, pvcs associated with a deployment set use the same informer.

I ran several dozen updates with this and various scenarios. I didn't see any throttles (and if they occurred they were handled gracefully). 

We also get the behavior we want for #1502 - since the informer will feed the initial read as an event to the respective channels and we don't miss deployments/replicaset scale ups.

I will follow up with a separate PR for some additional unit tests to cover some more scenarios which might require a little bit of refactoring here.

### CODE REVIEW

**Comment by mikhailshilkov** [comment]
A couple of fundamental questions before commenting on details:

- Given our previous need to flip back to the previous await logic in a patch release, is there a way we could avoid doing so if this new code goes sideways? Can we add a flag to turn it off? Can we combine both methods somehow?
- I noticed that the TF provider awaits with polling, at least [for deployment](https://github.com/hashicorp/terraform-provider-kubernetes/blob/main/kubernetes/resource_kubernetes_deployment.go). In general, I'm bias towards polling because it's much easier to reason about compared to event handling. Is there a reason we can't use polling here?

File: provider/pkg/await/deployment.go [hunk 1]
```diff
@@ -858,3 +886,35 @@ func (dia *deploymentInitAwaiter) makeClients() (
 
 	return
 }
+
+func (dia *deploymentInitAwaiter) makeInformer(gvr schema.GroupVersionResource, informChan chan<- watch.Event) cache.SharedIndexInformer {
+	informer := dia.config.informerFactory.ForResource(gvr).Informer()
+	informer.AddEventHandler(cache.ResourceEventHandlerFuncs{
+		AddFunc: func(obj interface{}) {
+			informChan <- watch.Event{
+				Object: obj.(*unstructured.Unstructured),
```
Comment (lblackstone) [inline provider/pkg/await/deployment.go:895]: We should probably do a defensive type assertion here to avoid panics in case the object is the wrong type somehow.

File: provider/pkg/provider/provider.go [hunk 2]
```diff
@@ -63,7 +53,16 @@ import (
 	"k8s.io/client-go/tools/clientcmd"
 	clientapi "k8s.io/client-go/tools/clientcmd/api"
 	k8sopenapi "k8s.io/kubectl/pkg/util/openapi"
+	"net/http"
```
Comment (lblackstone) [inline provider/pkg/provider/provider.go:56]: nit: We've been using `goimports` to format the k8s provider code. It looks like we may be using different toolchains, so we should pick one and standardize on it.

**Comment by mikhailshilkov** [comment]
I'm less concerned about Kubernetes not being able to provide events or something, but rather about the consequences of a lost/delayed/wrong-sequenced/duplicate event throwing off our client logic and potentially leading to stuck updates, while being hard to test.

Is poll bad in terms of performance? Or what are some concerns about it?

File: provider/pkg/await/deployment.go [hunk 3]
```diff
@@ -372,16 +395,16 @@ func (dia *deploymentInitAwaiter) processDeploymentEvent(event watch.Event) {
...
+			event.Object)
 		return
 	}
 
 	// Start over, prove that rollout is complete.
 	dia.deploymentErrors = map[string]string{}
 
 	// Do nothing if this is not the Deployment we're waiting for.
-	if deployment.GetName() != inputDeploymentName {
+	if deployment.GetName() != inputDeploymentName || deployment.GetNamespace() != dia.config.currentInputs.GetNamespace() {
```
Comment (lblackstone) [inline provider/pkg/await/deployment.go:407]: Since the informer is already filtering by namespace, is this necessary?

File: provider/pkg/await/await.go [hunk 4]
```diff
@@ -215,6 +217,7 @@ func Creation(c CreateConfig) (*unstructured.Unstructured, error) {
 					urn:               c.URN,
 					initialAPIVersion: c.InitialAPIVersion,
 					clientSet:         c.ClientSet,
+					informerFactory:   dynamicinformer.NewFilteredDynamicSharedInformerFactory(c.ClientSet.GenericClient, 5*time.Second, c.Inputs.GetNamespace(), nil),
```
Comment (lblackstone) [inline provider/pkg/await/await.go:220]: I'm not sure yet if we want to set the refresh period on the informers, and if so, what the period should be. This will need some more testing/tuning.

File: provider/pkg/await/deployment.go [hunk 5]
```diff
@@ -144,53 +144,72 @@ func (dia *deploymentInitAwaiter) Await() error {
...
-	if err != nil {
-		return errors.Wrapf(err,
-			"Could not create watcher for PersistentVolumeClaims objects associated with Deployment %q",
-			dia.config.currentInputs.GetName())
-	}
-	defer pvcWatcher.Stop()
+	stopper := make(chan struct{})
+	defer close(stopper)
+
+	// Limit the lifetime of this to each deployment await for now. We can reduce this sharing further later.
```
Comment (lblackstone) [inline provider/pkg/await/deployment.go:150]: Any particular reason for initializing a factory per await? Seems like we could share the factory across the provider without much difference in level of effort.

**Comment by lblackstone** [comment]
> I'm less concerned about Kubernetes not being able to provide events or something, but rather about the consequences of a lost/delayed/wrong-sequenced/duplicate event throwing off our client logic and potentially leading to stuck updates, while being hard to test.

I'm not 100% sure that this is the case, but I believe the await logic should be idempotent. We already support resuming a previous update, which isn't guaranteed to include the full sequence of events. At least for Job and Pod, a single event is sufficient to declare that the resource is ready, so it's not sensitive to ordering/duplicates. We should verify that this is the case for all awaiters, but I'm pretty sure it is.

> Is poll bad in terms of performance? Or what are some concerns about it?
Yes, polling can cause performance problems for k8s clusters at scale. It's not that polling would not work for our use case, but that [watch is preferred to polling in general for k8s](https://speakerdeck.com/thockin/kubernetes-controllers-are-they-loops-or-events).

File: provider/pkg/provider/provider.go (hunk 2 above)
Comment (viveklak) [reply provider/pkg/provider/provider.go:56]: I default to gofmt and assumed make lint would catch it. Sounds good, I will run goimports.

File: provider/pkg/await/deployment.go (hunk 3 above)
Comment (viveklak) [reply provider/pkg/await/deployment.go:407]: Yup - makes sense. Will remove.

**Comment by viveklak** [comment]
> I'm less concerned about Kubernetes not being able to provide events or something, but rather about the consequences of a lost/delayed/wrong-sequenced/duplicate event throwing off our client logic and potentially leading to stuck updates, while being hard to test.

I think this is a valid concern. That said, a watch with a reasonably spaced resync interval essentially mimics the poll behavior as a fallback. With this approach we are making it much harder to miss an event.

To be clear, the change that we reverted wasn't wrong. We theorize it made the likelihood of hitting an API server-side throttle a bit higher but we are still definitely hitting those throttling events regardless of that change. 

IMO this is a longstanding issue. I don't know why it is becoming more prevalent now. Perhaps newer api servers are more aggressive on throttling or cloud providers have dialed these up? While I am still working through testing this, I have already seen the informer model handle throttling a lot better.

**Comment by mikhailshilkov** [comment]
> We theorize it made the likelihood of hitting an API server-side throttle a bit higher but we are still definitely hitting those throttling events regardless of that change.

What is the failure mode when we hit throttling? Why does it lead to stuck updates as opposed to just slower updates? Any good places for me to read about this?

Thank you for bearing with my noob questions!

**Comment by viveklak** [comment]
> > We theorize it made the likelihood of hitting an API server-side throttle a bit higher but we are still definitely hitting those throttling events regardless of that change.
> 
> What is the failure mode when we hit throttling? Why does it lead to stuck updates as opposed to just slower updates? Any good places for me to read about this?
> 
> Thank you for bearing with my noob questions!

Not a problem. The tight loop is just a straight up bug. https://github.com/pulumi/pulumi-kubernetes/blob/master/provider/pkg/await/deployment.go#L314
ResultChan() can be closed if there is an error, this could be a throttle or a network blip. As a result, we keep reading from a closed channel. There is a low-level backoff protocol embedded, e.g.: https://github.com/kubernetes/client-go/blob/v0.21.2/tools/watch/retrywatcher.go#L189 but informer handles all this internally.

**Comment by viveklak** [comment]
@lblackstone @mikhailshilkov I think this is ready for another look. In my tests things seemed much more stable with this.

File: provider/pkg/await/deployment.go (hunk 5 above)
Comment (viveklak) [reply provider/pkg/await/deployment.go:151]: > Any particular reason for initializing a factory per await? Seems like we could share the factory across the provider without much difference in level of effort.

One thing was to set the lifetime of the factory itself (the stop channel to pass to the `Start` call in the next line). This way we know it's safe to kill the informer once an individual deployment has been waited on. A shared informer for the entire provider would need some degree of coordination to make sure all the deployments had completed etc. which I didn't want to layer on yet.

Comment (lblackstone) [reply provider/pkg/await/deployment.go:151]: Ok. That sounds reasonable as a first step, but presumably doesn't buy us anything in terms of performance since we aren't sharing the cache between resources?

File: provider/pkg/await/await.go [hunk 6]
```diff
@@ -208,13 +210,18 @@ func Creation(c CreateConfig) (*unstructured.Unstructured, error) {
...
+				namespace = metav1.NamespaceDefault
+			}
 			if awaiter.awaitCreation != nil {
 				conf := createAwaitConfig{
 					host:              c.Host,
 					ctx:               c.Context,
 					urn:               c.URN,
 					initialAPIVersion: c.InitialAPIVersion,
 					clientSet:         c.ClientSet,
+					informerFactory:   dynamicinformer.NewFilteredDynamicSharedInformerFactory(c.ClientSet.GenericClient, 60*time.Second, namespace, nil),
```
Comment (lblackstone) [inline provider/pkg/await/await.go:224]: I just noticed that the resync is from the local cache and doesn't check the authoritative source. Since all of the awaiters are running locally to the cache anyway, we should be able to disable the resync.

> The resync operation consists of delivering to the handler an update notification for every object in the informer's local cache; it does not add any interactions with the authoritative storage.

Comment (viveklak) [reply provider/pkg/await/await.go]: I have removed the informer factory from the await config. I initially dropped the resync but I think it might be best to keep it there to allow us to ensure the await logic gets kicked periodically anyway which seems desirable. In a way this gives us polling for the await logic without actually hitting the API server so the cost of having this is very low.

File: provider/pkg/await/deployment.go [hunk 7]
```diff
@@ -144,53 +146,88 @@ func (dia *deploymentInitAwaiter) Await() error {
...
+		}, deploymentEvents)
+	go deploymentV1Informer.Informer().Run(stopper)
+	deploymentV1Beta1Informer := dia.makeInformer(
+		informerFactory,
+		schema.GroupVersionResource{
+			Group:    "extensions",
+			Version:  "v1beta1",
+			Resource: "deployments",
+		}, deploymentEvents)
+	go deploymentV1Beta1Informer.Informer().Run(stopper)
```
Comment (lblackstone) [inline provider/pkg/await/deployment.go:176]: I'm not sure if we need Informers for the old apiVersions. I believe the watch clients were previously only using the latest apiVersions.

**Review by lblackstone — APPROVED** [review]

File: provider/pkg/await/deployment.go (hunk 7 above)
Comment (viveklak) [reply provider/pkg/await/deployment.go:176]: Ah interesting. Does that mean that we don't really support the v1beta1 etc. variants? It seems like we load the latest api versions when creating clients and use them to create watches. I can't really verify this since all the cloud providers seem to have stopped supporting  1.15 or older (bunch of these were killed in 1.16).

Comment (viveklak) [reply provider/pkg/await/deployment.go]: Caught up with @lblackstone offline. It seems we should be safe here. Removed non-v1 informer variants.
