### PR TITLE
Fix Deployment await logic for extensions/v1beta1

### LINKED ISSUE #611: A failed Deployment update doesn't seem to fail
If I update an existing Deployment to reference an erroneous image name, the update succeeds, even though the resulting Pod ends up in an endless backoff.

The resulting `kubectl get po` looks like this:

```
$ kubectl get po
NAME                              READY     STATUS             RESTARTS   AGE
nginx-u76btcdw-9b5ccdb7-psf64     0/1       ImagePullBackOff   0          22s
nginx-u76btcdw-9cb4784bd-vjrww    1/1       Running            0          52s
```

`nginx-u76btcdw-9cb4784bd-vjrww` is the old Pod running the correctly named image -- which I assume would go away once the rollout has completed -- and `nginx-u76btcdw-9b5ccdb7-psf64` is the newly created Pod that is meant to replace it, but cannot, due to the mistyped image name.

This is inconsistent with what happens with a new `Deployment`. Shouldn't this fail too?

-------

@lblackstone Update:
I've fixed this for all apiVersions except for `extensions/v1beta1`, which will require additional work. Will close out this issue once #656 is done.

### LINKED ISSUE #656: The Deployment awaiter doesn't handle rollouts properly for extensions/v1beta1
Related to #611 

In the interest of getting a fix pushed out for the bulk of cases, I'm splitting out the fix for the old `extensions/v1beta1` version of Deployment, and tracking here.

### PR DESCRIPTION
**Pull request by lblackstone**
The Deployment await logic was not correctly checking rollout
success for the `extensions/v1beta1` apiVersion, which was
causing the await logic to erroneously pass for change
triggered rollouts, even if the Deployment was invalid.

Added additional logic to the readiness check based on
status fields present in all apiVersions.

Fixes #611 
Fixes #656

### CODE REVIEW

File: pkg/await/apps_deployment.go [hunk 1]
```diff
@@ -528,29 +546,65 @@ func (dia *deploymentInitAwaiter) checkReplicaSetStatus() {
...
+		unavailableReplicasPresent = unavailableReplicas != 0
+	}
+
 	glog.V(3).Infof("ReplicaSet %q requests '%v' replicas, but has '%v' ready",
 		rs.GetName(), specReplicas, readyReplicas)
 
 	if dia.changeTriggeredRollout() {
-		dia.updatedReplicaSetReady = lastGeneration != dia.currentGeneration && updatedReplicaSetCreated &&
-			readyReplicasExists && readyReplicas >= specReplicas
+	    if extensionsv1beta1API {
```
Comment (hausdorff) [inline pkg/await/apps_deployment.go]: You're using spaces here when you should use tabs. Here and in other places.

File: pkg/await/apps_deployment.go [hunk 2]
```diff
@@ -394,6 +395,23 @@ func (dia *deploymentInitAwaiter) processDeploymentEvent(event watch.Event) {
 		// No current generation, Deployment controller has not yet created a ReplicaSet. Do
 		// nothing.
 		return
+	} else {
+		if currentGenerationInt, err := strconv.Atoi(dia.currentGeneration); err == nil {
```
Comment (hausdorff) [inline pkg/await/apps_deployment.go]: Instead of an `else` it seems like this should be hidden behind an `if extensionsv1beta1API {`. In particular, it seems like we _don't_ want to affect the code paths of the other versions, since they already work.

File: pkg/await/apps_deployment.go [hunk 3]
```diff
@@ -394,6 +395,23 @@ func (dia *deploymentInitAwaiter) processDeploymentEvent(event watch.Event) {
...
+			if int64(currentGenerationInt) != dia.deployment.GetGeneration() {
+				// If the generation is set, make sure it matches the revision annotation, otherwise, ignore this
+				// event because the status we care about may not be set yet.
+				return
+			}
+			if rawObservedGeneration, ok := openapi.Pluck(
```
Comment (hausdorff) [inline pkg/await/apps_deployment.go]: Is there a particular reason why we're starting with the metadata and falling back to the status, rather than the reverse?

File: pkg/await/apps_deployment.go [hunk 4]
```diff
@@ -528,29 +546,65 @@ func (dia *deploymentInitAwaiter) checkReplicaSetStatus() {
...
+	// Note that this status field does not appear immediately on update, so it's not sufficient to
+	// determine readiness by itself.
+	unavailableReplicasPresent := false
+	if rawUnavailableReplicas, ok := openapi.Pluck(
+		dia.deployment.Object, "status", "unavailableReplicas"); ok {
+		unavailableReplicas, _ = rawUnavailableReplicas.(int64)
+
+		unavailableReplicasPresent = unavailableReplicas != 0
+	}
+
```
Comment (hausdorff) [inline pkg/await/apps_deployment.go]: I'm not sure why this chunk of added code should not be behind `if extensionsv1beta1API {` also?

File: pkg/await/apps_deployment.go (hunk 1 above)
Comment (lblackstone) [reply pkg/await/apps_deployment.go]: Argh, thought I had fixed that. Will double-check

File: pkg/await/apps_deployment.go (hunk 2 above)
Comment (lblackstone) [reply pkg/await/apps_deployment.go]: I was thinking that these conditions applied generally, but I think you're right. It was working well before, so I'm going to make this conditional on the older API version.

File: pkg/await/apps_deployment.go (hunk 3 above)
Comment (lblackstone) [reply pkg/await/apps_deployment.go]: No; I just wanted to check both conditions, but the order wasn't material.

File: pkg/await/apps_deployment.go (hunk 4 above)
Comment (lblackstone) [reply pkg/await/apps_deployment.go]: Will do
