### PR TITLE
Handle resource change from static name to autoname under SSA

### LINKED ISSUE #2384: k8s Provider with server-side apply enabled can't replace namespace
### What happened?

Given minimal stack:
```
import pulumi
import pulumi_kubernetes as k8s

prov = k8s.Provider("k8s", enable_server_side_apply=True)

ns = k8s.core.v1.Namespace(
    "test",
    metadata=k8s.meta.v1.ObjectMetaArgs(
       name="test"
    ),
    opts=pulumi.ResourceOptions(provider=prov),
)
```
and upping it up:
```
Previewing update (dev):
     Type                             Name     Plan       
 +   pulumi:pulumi:Stack              pb2-dev  create     
 +   ├─ pulumi:providers:kubernetes   k8s      create     
 +   └─ kubernetes:core/v1:Namespace  test     create     


Resources:
    + 3 to create

Do you want to perform this update? yes
Updating (dev):
     Type                             Name     Status              
 +   pulumi:pulumi:Stack              pb2-dev  created (0.64s)     
 +   ├─ pulumi:providers:kubernetes   k8s      created (0.38s)     
 +   └─ kubernetes:core/v1:Namespace  test     created (0.28s)     


Resources:
    + 3 created

Duration: 3s


```

removing fixed namespace to create one with auto-generated name
```
import pulumi
import pulumi_kubernetes as k8s

prov = k8s.Provider("k8s", enable_server_side_apply=True)

ns = k8s.core.v1.Namespace(
    "test",
    opts=pulumi.ResourceOptions(provider=prov),
)
```

fails:
```
Previewing update (dev):
     Type                             Name     Plan     Info
     pulumi:pulumi:Stack              pb2-dev           
     └─ kubernetes:core/v1:Namespace  test              1 error


Diagnostics:
  kubernetes:core/v1:Namespace (test):
    error: namespaces "test" not found
```

### Expected Behavior

New namespace created. Old namespace removed.

### Steps to reproduce

up first stack, edit, up again

### Output of `pulumi about`

```
CLI          
Version      3.65.1
Go Version   go1.20.3
Go Compiler  gc

Plugins
NAME        VERSION
kubernetes  3.27.0
python      unknown

Host     
OS       debian
Version  12.0
Arch     x86_64

This project is written in python: executable='/home/bacek/pb2/venv/bin/python3' version='3.8.10
'

Current Stack: organization/pb2/dev

TYPE                          URN
pulumi:pulumi:Stack           urn:pulumi:dev::pb2::pulumi:pulumi:Stack::pb2-dev
pulumi:providers:kubernetes   urn:pulumi:dev::pb2::pulumi:providers:kubernetes::k8s
kubernetes:core/v1:Namespace  urn:pulumi:dev::pb2::kubernetes:core/v1:Namespace::test


Found no pending operations associated with dev

Backend        
Name           sunburst
URL            s3://com-neara-pulumi-27d0047/stacks
User           bacek
Organizations  

Dependencies:
NAME               VERSION
pip                23.1.2
pulumi-kubernetes  3.27.0
setuptools         67.7.2
wheel              0.40.0

Pulumi locates its logs in /tmp by default
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by lblackstone**
### Proposed changes
Server-side apply mode had a bug where changing a resource from having a static `.metadata.name` to being autonamed by removing the `.metadata` property would return an error. This change updates the diff logic to account for this case, which will result in the resource being replaced.

### Related issues (optional)
Fix #2384

### CODE REVIEW

File: provider/pkg/provider/provider.go [hunk 1]
```diff
@@ -1654,6 +1654,10 @@ func (k *kubeProvider) Diff(ctx context.Context, req *pulumirpc.DiffRequest) (*p
 				switch v.Kind {
 				case pulumirpc.PropertyDiff_ADD_REPLACE, pulumirpc.PropertyDiff_DELETE_REPLACE, pulumirpc.PropertyDiff_UPDATE_REPLACE:
 					replaces = append(replaces, k)
+				case pulumirpc.PropertyDiff_DELETE:
+					if k == "metadata" {
```
Comment (thomas11) [inline provider/pkg/provider/provider.go:1658]: Is it ever a possibility that `metadata` remains but `metadata.name` is removed?

**Review by thomas11 — APPROVED** [review]
