### PR TITLE
Add resource autonaming, fix various replacement issues

### LINKED ISSUE #68: `pulumi update` does not wait for pod restarts
If you change (_e.g._) the environment variables of a container in some pod, it should trigger a hard reset of that pod. Unfortunately, `pulumi update` will usually not wait for the pod to restart, instead simply reporting immediately that the resource was created.

### PR DESCRIPTION
**Pull request by hausdorff**
Add autonaming (_cf_., #10). The design of this feature (which is fairly simple) is specified in that issue.

Fix #68, #99, and #81 (correctness and replacement issues).

Add end-to-end tests for delete-before-replace semantics (partial for #90).

NOTE: We would add end to end tests for service and PVs, but they won't work until we write up the test ci cluster.

[asciicast](https://asciinema.org/a/slOPaYVTX6pZu49m1FIyHYCci?autoplay=1)

### CODE REVIEW

File: pkg/provider/naming.go [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+		}
+	}
+}
+
+func randString(n int) string {
+	var alphabet = []rune("abcdefghijklmnopqrstuvwxyz0123456789")
+
+	b := make([]rune, n)
+	for i := range b {
+		b[i] = alphabet[rand.Intn(len(alphabet))]
```
Comment (pgavlin) [inline pkg/provider/naming.go]: Note that the default `rand` source is seeded with the same value each time the process starts, so this will be essentially deterministic. If that matters, you should seed the source in this package's `init` function.

File: pkg/provider/naming.go [hunk 2]
```diff
@@ -0,0 +1,44 @@
...
+func assignName(obj *unstructured.Unstructured, base tokens.QName) {
+	if !renameBlacklist.Has(obj.GroupVersionKind().String()) {
+		replaceNameIfUnnamed(obj, fmt.Sprintf("%s-%s", base, randString(8)))
+	} else {
+		replaceNameIfUnnamed(obj, string(base))
+	}
+}
+
+// replaceNameIfUnnamed will replace an object's name if it doesn't already have one.
+func replaceNameIfUnnamed(obj *unstructured.Unstructured, name string) {
```
Comment (pgavlin) [inline pkg/provider/naming.go]: `setNameIfUnnamed` might be a better name--in a Pulumi context, `replace` has pretty specific connotations.

File: pkg/provider/provider.go [hunk 3]
```diff
@@ -205,7 +208,6 @@ func (k *kubeProvider) Check(ctx context.Context, req *pulumirpc.CheckRequest) (
 		}
 	}
 
-	// We currently don't change the inputs during check.
 	return &pulumirpc.CheckResponse{Inputs: newResInputs, Failures: failures}, nil
```
Comment (pgavlin) [inline pkg/provider/provider.go]: will `newResInputs` contain the autoname, then?

File: pkg/provider/naming.go [hunk 4]
```diff
@@ -0,0 +1,44 @@
...
+	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
+	"k8s.io/apimachinery/pkg/util/sets"
+)
+
+var renameBlacklist = sets.NewString("v1/Namespace")
+
+// assignName generates a name for an object if it doesn't already have one. Uses DNS-1123-compliant
+// characters.
+func assignName(obj *unstructured.Unstructured, base tokens.QName) {
+	if !renameBlacklist.Has(obj.GroupVersionKind().String()) {
```
Comment (swgillespie) [inline pkg/provider/naming.go]: Okay, so for my own understanding, this reads to me as "autogenerate a random suffix for this thing's name if it's not a v1/Namespace". I thought [here](https://github.com/pulumi/pulumi-kubernetes/issues/10#issuecomment-407160010) you said that `v1/Namespace` isn't an exception - should we be doing the same for those, too?

File: pkg/provider/naming.go [hunk 5]
```diff
@@ -0,0 +1,44 @@
...
+		if meta == nil {
+			obj.Object["metadata"] = map[string]interface{}{"name": name}
+		} else {
+			meta.(map[string]interface{})["name"] = name
+		}
+	}
+}
+
+func randString(n int) string {
+	var alphabet = []rune("abcdefghijklmnopqrstuvwxyz0123456789")
```
Comment (swgillespie) [inline pkg/provider/naming.go]: This can be a global `var`

File: tests/integration/autonaming/step1/Pulumi.yaml [hunk 6]
```diff
@@ -0,0 +1,3 @@
+name: partial_state
```
Comment (swgillespie) [inline tests/integration/autonaming/step1/Pulumi.yaml]: nit: `autonaming`

File: tests/integration/pod/step1/Pulumi.yaml [hunk 7]
```diff
@@ -0,0 +1,3 @@
+name: partial_state
```
Comment (swgillespie) [inline tests/integration/pod/step1/Pulumi.yaml]: same here. Don't think this really matters, it's just hygiene.

File: pkg/await/awaiters.go [hunk 8]
```diff
@@ -141,6 +141,8 @@ var awaiters = map[string]awaitSpec{
 		awaitCreation: untilCoreV1PersistentVolumeClaimBound,
 	},
 	coreV1Pod: {
+		// NOTE: Because we replace the Pod in most situations, we do not require special logic for the
+		// update path.
```
Comment (swgillespie) [inline pkg/await/awaiters.go]: Is this to say that there's pretty much no input change to a `Pod` that won't cause a replacement?

File: pkg/provider/naming.go (hunk 1 above)
Comment (swgillespie) [inline pkg/provider/naming.go]: `rand.Intn` is deterministic by default (https://github.com/golang/go/issues/4509) - since I don't think we seed rand anywhere we should either 1) seed it explicitly on startup or 2) use `crypto/rand` so that we don't get in bad situations with name collisions?

Comment (swgillespie) [reply pkg/provider/naming.go]: Ah, OK, looks like we are seeding:

https://github.com/pulumi/pulumi-kubernetes/blob/8c0b67e07348696c273cfb109d1997c22a248c44/pkg/watcher/watcher.go#L188

Never mind, then.

Comment (pgavlin) [reply pkg/provider/naming.go]: We should still be explicit about the seeding in this package if it requires it.

File: pkg/provider/provider.go (hunk 3 above)
Comment (hausdorff) [reply pkg/provider/provider.go]: It will, yes.

File: pkg/provider/naming.go (hunk 4 above)
Comment (hausdorff) [reply pkg/provider/naming.go]: I haven't updated this yet, I'm removing it now.

File: pkg/provider/naming.go (hunk 5 above)
Comment (hausdorff) [reply pkg/provider/naming.go]: I don't like global `var`, but this is also minor so let's do that.

File: pkg/await/awaiters.go (hunk 8 above)
Comment (hausdorff) [reply pkg/await/awaiters.go]: It's basically saying there is no input change to `Pod` won't result in a replacement, _that also requires an await_.

File: pkg/provider/provider.go [hunk 9]
```diff
@@ -251,9 +253,13 @@ func (k *kubeProvider) Diff(
 	}
 	newInputs := propMapToUnstructured(newResInputs)
 
-	// Naive replacement strategy. We will kill and recreate a resource only if the name or namespace
-	// has changed.
-	replaces, err := forceNewProperties(oldInputs.Object, newInputs.Object, oldInputs.GroupVersionKind())
+	// If the new object doesn't have a name, it was probably autonamed, so we give it the old
+	// object's name.
+	newName := newInputs.GetName()
+	replaceNameIfUnnamed(newInputs, oldInputs.GetName())
```
Comment (pgavlin) [inline pkg/provider/provider.go]: I think this is in the wrong place: I'm pretty sure this needs to happen in Check.

File: pkg/await/awaiters.go (hunk 8 above)
Comment (swgillespie) [reply pkg/await/awaiters.go]: got it, thanks.

File: pkg/provider/provider.go (hunk 9 above)
Comment (hausdorff) [reply pkg/provider/provider.go]: Ah, I see what's going on here. Initially when I mutated the inputs to have the new name, they weren't getting propagated to calls to `Diff`, `Create`, _etc_. The reason for this is that we weren't marshalling those mutations back and returning those -- we were just returning the inputs verbatim.

**Comment by hausdorff** [comment]
Unfortunately my laptop is too wimpy to run the CI tests without becoming catastrophically unusable, so I'll have to nudge things along until the CI passes, but modulo that I think we agree that this approach is the one we want to go with.
