### PR TITLE
Fix ServiceAccount update panic

### LINKED ISSUE #3166: await.untilCoreV1ServiceAccountInitialized panic
### What happened?

Came across this while hacking. Not sure how to reproduce, but it looks like we assume we have a cluster version that's not always available.

```
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10605c4b4]
    goroutine 598 [running]:
    github.com/pulumi/pulumi-kubernetes/provider/v4/pkg/await.untilCoreV1ServiceAccountInitialized({{0x1089ba708, 0x140004f24b0}, {0x14005c14090, 0x8a}, {0x14003f5e2be, 0x2}, 0x1400204cd40, 0x1400015c6c0, 0x14005c405d0, 0x14005c40540, ...})
    	/home/runner/work/pulumi-kubernetes/pulumi-kubernetes/provider/pkg/await/awaiters.go:692 +0x54
    github.com/pulumi/pulumi-kubernetes/provider/v4/pkg/await.Update({{{0x1089ba708, 0x140004f24b0}, {0x1089a7640, 0x140001a06d8}, {0x14005c14090, 0x8a}, {0x14003f5e2be, 0x2}, {0x140020b2020, 0x1a}, ...}, ...})
    	/home/runner/work/pulumi-kubernetes/pulumi-kubernetes/provider/pkg/await/await.go:431 +0x644
    github.com/pulumi/pulumi-kubernetes/provider/v4/pkg/provider.(*kubeProvider).Update(0x14000516000, {0x1089ba6d0, 0x140024a11a0}, 0x14000f96120)
    	/home/runner/work/pulumi-kubernetes/pulumi-kubernetes/provider/pkg/provider/provider.go:2417 +0x9e4
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Update_Handler.func1({0x1089ba6d0?, 0x140024a11a0?}, {0x1083457e0?, 0x14000f96120?})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.127.0/proto/go/provider_grpc.pb.go:687 +0xd0
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x1089ba6d0, 0x140024a0780}, {0x1083457e0, 0x14000f96120}, 0x140069981e0, 0x14001d04588)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2e4
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Update_Handler({0x1088c8b60, 0x14000516000}, {0x1089ba6d0, 0x140024a0780}, 0x14007002180, 0x1400061c420)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.127.0/proto/go/provider_grpc.pb.go:689 +0x148
    google.golang.org/grpc.(*Server).processUnaryRPC(0x1400079c200, {0x1089ba6d0, 0x140024a06f0}, {0x108a12a20, 0x140004e4000}, 0x14001afc900, 0x140008f9920, 0x10c5248a8, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.65.0/server.go:1379 +0xb58
    google.golang.org/grpc.(*Server).handleStream(0x1400079c200, {0x108a12a20, 0x140004e4000}, 0x14001afc900)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.65.0/server.go:1790 +0xb20
    google.golang.org/grpc.(*Server).serveStreams.func2.1()
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.65.0/server.go:1029 +0x8c
    created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 54
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.65.0/server.go:1040 +0x13c
```

### Example

n/a

### Output of `pulumi about`

n/a

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by blampe**
The `ServiceAccount` awaiter is the only one which uses `clusterVersion` to decide its behavior, and we were only populating this on creation. #3139 consolidated create/update wait logic, which introduced a panic in this case because we're now calling the init awaiter during update.

This PR adds a `nil` check to be safe and also populates `clusterVersion` for update/delete/read in the off chance that another awaiter might want to use it later down the line.

Fixes #3166

### CODE REVIEW

File: provider/pkg/await/awaiters.go [hunk 1]
```diff
@@ -689,7 +689,7 @@ func untilCoreV1ServiceAccountInitialized(c awaitConfig) error {
 	// k8s v1.24 changed the default secret provisioning behavior for ServiceAccount resources, so don't wait for
 	// clusters >= v1.24 to provision a secret before marking the resource as ready.
 	// https://github.com/kubernetes/kubernetes/blob/v1.24.3/CHANGELOG/CHANGELOG-1.24.md#urgent-upgrade-notes
-	if c.clusterVersion.Compare(cluster.ServerVersion{Major: 1, Minor: 24}) >= 0 {
+	if c.clusterVersion != nil && c.clusterVersion.Compare(cluster.ServerVersion{Major: 1, Minor: 24}) >= 0 {
```
Comment (EronWright) [inline provider/pkg/await/awaiters.go:692]: I don't see a problem with taking the assumption that `c.clusterVersion` is non-nil. An assertion would make more sense than conditional logic, unless there's actually a use-case where cluster version is unknown.
```go
import "github.com/pulumi/pulumi/sdk/v3/go/common/util/contract"
```

**Review by EronWright — APPROVED** [review]
