### PR TITLE
Use HELM_HOME as default if set

### LINKED ISSUE #854: HELM_HOME environment variable is ignored
**Describe the bug**
Running a Pulumi preview command using the task, even after a HelmInstaller task successfully runs, fails to fetch a helm chart if a Chart resource exists in the Pulumi project.  The Helm tool cannot locate the `.helm` folder.

**To Reproduce**
Use a Chart resource from a Pulumi project run by the Pulumi@1 task.

**Expected behavior**
The helm Chart resource provider should locate the `.helm` folder using the HELM_HOME environment variable.

**Screenshots**
pulumi-helm-preview-error

**Additional context**
A demo exists [here](https://dev.azure.com/mark-labs/_git/azure-pipelines-pulumi-helm-test?_a=readme) with a pipeline already setup and failing.  The failing build log is [here](https://dev.azure.com/mark-labs/azure-pipelines-pulumi-helm-test/_build/results?buildId=4).

### PR DESCRIPTION
**Pull request by lblackstone**
### Proposed changes
Previously, the Chart resource ignored the HELM_HOME
environment variable. This value is now used as a default
if set. Note that the fetch `home` option still takes
precedence over HELM_HOME.

### Related issues (optional)

Fixes #854

### CODE REVIEW

File: pkg/gen/nodejs-templates/helm/v2/helm.ts [hunk 1]
```diff
@@ -394,7 +402,17 @@ export function fetch(chart: string, opts?: ResolvedFetchOpts) {
         // Untar by default.
         if(opts.untar !== false) { flags.push(`--untar`); }
 
-        // For arguments that are not paths to files, it is sufficent to use shell.quote to quote the arguments.
+        // Fallback to using the HELM_HOME environment variable if opts.home is not set.
+        if (opts.home !== undefined) {
```
Comment (pgavlin) [inline pkg/gen/nodejs-templates/helm/v2/helm.ts]:
```suggestion
        if (!opts.home) {
            opts.home = process.env.HELM_HOME || undefined;
        }
```

File: pkg/gen/nodejs-templates/helm/v2/helm.ts [hunk 2]
```diff
@@ -192,8 +192,16 @@ export class Chart extends yaml.CollectionComponentResource {
                 const namespaceArg = cfg.namespace
                     ? `--namespace ${shell.quote([cfg.namespace])}`
                     : "";
+                let cmd = `helm template ${chart} --name-template ${release} --values ${defaultValues} --values ${values} ${namespaceArg}`;
+
+                // Use the HELM_HOME environment variable value if set.
+                const home = process.env.HELM_HOME || undefined;
+                if (home !== undefined) {
+                    cmd += ` --home ${home}`;
```
Comment (pgavlin) [inline pkg/gen/nodejs-templates/helm/v2/helm.ts]:
```suggestion
                    cmd += ` --home ${path.quotePath(home)}`;
```
