### PR TITLE
Fix deprecation notice for CSINode

### LINKED ISSUE #943: Fix deprecation warning for storage/v1beta1/CSINode
### Problem description

- I saw an issue in the following documentation: https://github.com/pulumi/pulumi-kubernetes/blob/5eaa7266027cd6d8b68bed0d18da34caeb98ae26/sdk/nodejs/storage/v1beta1/CSINode.ts#L12

The generated deprecation warning is invalid, and the related deprecation logic may also be incorrect.

### PR DESCRIPTION
**Pull request by lblackstone**
### Related issues (optional)

Fixes #943

### CODE REVIEW

File: pkg/gen/additionalComments.go [hunk 1]
```diff
@@ -164,10 +164,18 @@ func PulumiComment(kind string) string {
...
 	removedIn := kinds.RemovedInVersion(gvk)
-	return fmt.Sprintf(template, gvkStr, kinds.SuggestedApiVersion(gvk), removedIn)
+
+	comment := fmt.Sprintf(deprecatedTemplate, gvkStr, kinds.SuggestedApiVersion(gvk))
+	if removedIn != nil {
+		comment += fmt.Sprintf(notSupportedTemplate, removedIn)
+	} else {
+		comment += "."
+	}
+	comment += "\n\n"
```
Comment (justinvp) [inline pkg/gen/additionalComments.go]: Note: I removed the trailing newlines in https://github.com/pulumi/pulumi-kubernetes/pull/942/files#diff-8e79ebc2d540f3681d4e0b6bcf3a595bL167-R167, so depending on which PR is merged first, we'll need to make sure to do the same when addressing the merge conflict.
