### PR TITLE
Fix hang on large YAML files

### LINKED ISSUE #963: Hangs and crashes with 1.4.2 - WAS: Regression between 1.4.1 and >= 1.4.2 in `k8s.yaml.ConfigGroup`
### Problem description

In 1.4.1 we create a k8s.yaml.ConfigGroup with 10 yaml files and everything was ok. When I migrate to 1.4.2 or to last version 1.4.5, `pulumi up` just freeze while generating the preview state. If I comment ConfigGroup creation, everything works again and If I go back to version 1.4.1 everything works again too.

### Affected product version(s)

>= 1.4.2

### Reproducing the issue

The problem appear with a simple yaml from cert-manager for exemple: https://github.com/jetstack/cert-manager/releases/download/v0.12.0/cert-manager.yaml and this code:
```
const configGroup = new k8s.yaml.ConfigGroup(
    'kubernetes-ressources',
    {
      files: [
        '../manifests/cert-manager.yaml',
      ],
    },
    { provider: clusterProvider }
  );
```

Any idea ?

### PR DESCRIPTION
**Pull request by lblackstone**
### Related issues (optional)

Fixes #963

### CODE REVIEW

File: pkg/gen/nodejs-templates/yaml.ts.mustache [hunk 1]
```diff
@@ -87,7 +87,7 @@ import * as outputs from "../types/output";
 
     export interface ConfigOpts {
         /** JavaScript objects representing Kubernetes resources. */
-        objs: pulumi.Input<pulumi.Input<any>[]>;
```
Comment (pgavlin) [inline pkg/gen/nodejs-templates/yaml.ts.mustache]: Has this always been an inputty type that just hasn't worked?

Comment (lblackstone) [reply pkg/gen/nodejs-templates/yaml.ts.mustache]: Nope, this value was previously prompt (only usage occurred inside resolved Outputs/Promises).
