### PR TITLE
[yaml/v2] Support for resource ordering (implicit and explicit)

### LINKED ISSUE #2881: Apply heuristics to apply CRDs and Namespaces before all other resources in components
### Problem description

It's very common for Kubernetes components - `helm/v2.Chart`, `yaml.ConfigFile`, `kustomize.Directory` - to fail when deploying manifests that contain custom resource definitions to deploy resources in an "incorrect order".

### Errors & Logs

Errors like the following:

```
    error: creation of resource argocd/autoscaling failed because the Kubernetes API server reported that the apiVersion for this resource does not exist. Verify that any required CRDs have been created: no matches for kind "Application" in version "argoproj.io/v1alpha1"
```

### Suggestions for a fix

Providing fine grain control, as in the following issue, is one way to support this:
- #2880 

However, our components written in Go should be able to apply some heuristics to provide safer, more reliable deployments by sorting the resources and tracking a list of shared dependencies. Perhaps as a stepping stone to implementing #2879 or #2880 or richer transformations, the provider should apply this in `YAML/v2` and subsequent resources.

### PR DESCRIPTION
**Pull request by EronWright**
### Proposed changes

This PR adds support for resource ordering within a `ConfigGroup` or `ConfigFile`. Two approaches are supported (and work in combination):
1. implicit dependencies: the provider uses heuristics to install CRDs and namespaces first.
2. explicit dependencies: the provider understands the `config.kubernetes.io/depends-on` annotation to explicitly declare a dependency on a given resource.

The implementation is based on [kubernetes-sigs/cli-utils](https://github.com/kubernetes-sigs/cli-utils) and its support for resource ordering ([documentation](https://github.com/kubernetes-sigs/cli-utils?tab=readme-ov-file#resource-ordering)).

To be clear, ordering _across_ `ConfigGroup` resources is supported already, simply using the `dependsOn` option. This PR adds a more granular ordering _within_ the group.

### Testing
New test cases were added to verify the new behavior. Many tests rely on a common manifest file, and it is updated to include a CRD and a namespace.

Manual testing was performed with the following well-known manifests:
1. knative-serving-core ([ref](https://github.com/knative/serving/releases/download/knative-v1.13.1/serving-core.yaml))
2. cert-manager ([ref](https://github.com/cert-manager/cert-manager/releases/download/v1.14.4/cert-manager.yaml))

### Example
Here's an example that installs cert-manager then provisions a certificate issuer and a TLS certificate. An explicit dependency is drawn between the `Certificate` and `Issuer`.

```yaml
name: issue-2881-cert-manager
runtime: yaml
description: Installs cert-manager.  See https://cert-manager.io/docs/installation/kubectl/ for details.
variables: {}
resources:
  install:
    type: kubernetes:yaml/v2:ConfigGroup
    properties:
      files:
      - https://github.com/cert-manager/cert-manager/releases/download/v1.14.4/cert-manager.yaml
  test:
    type: kubernetes:yaml/v2:ConfigGroup
    options:
      dependsOn:
      - ${install}
    properties:
      yaml: |
        apiVersion: v1
        kind: Namespace
        metadata:
          name: cert-manager-test
        ---
        apiVersion: cert-manager.io/v1
        kind: Issuer
        metadata:
          name: test-selfsigned
          namespace: cert-manager-test
        spec:
          selfSigned: {}
        ---
        apiVersion: cert-manager.io/v1
        kind: Certificate
        metadata:
          name: selfsigned-cert
          namespace: cert-manager-test
          annotations:
            config.kubernetes.io/depends-on: cert-manager.io/namespaces/cert-manager-test/Issuer/test-selfsigned
        spec:
          dnsNames:
            - example.com
          secretName: selfsigned-cert-tls
          issuerRef:
            name: test-selfsigned
```

Within the stack state, one sees dependencies, e.g. on the `Certificate` resource.
```json
{
    "urn": "urn:pulumi:dev::issue-2881-cert-manager::kubernetes:yaml/v2:ConfigGroup$kubernetes:cert-manager.io/v1:Certificate::test-cert-manager-test/selfsigned-cert",
    "id": "cert-manager-test/selfsigned-cert",
    "type": "kubernetes:cert-manager.io/v1:Certificate",
    "dependencies": [
        "urn:pulumi:dev::issue-2881-cert-manager::kubernetes:yaml/v2:ConfigGroup$kubernetes:cert-manager.io/v1:Issuer::test-cert-manager-test/test-selfsigned",
        "urn:pulumi:dev::issue-2881-cert-manager::kubernetes:yaml/v2:ConfigGroup$kubernetes:core/v1:Namespace::test-cert-manager-test"
    ]
}
```

### Related issues (optional)

Closes #2881

### CODE REVIEW

File: provider/pkg/provider/yaml/v2/yaml.go [hunk 1]
```diff
@@ -140,14 +182,54 @@ type RegisterOptions struct {
...
 func Register(ctx *pulumi.Context, opts RegisterOptions) (pulumi.ArrayOutput, error) {
-	resources := pulumi.Array{}
+	objs := make(cliutilsobject.UnstructuredSet, 0, len(opts.Objects))
 	for _, obj := range opts.Objects {
-		rs, err := register(ctx, &obj, opts)
-		if err != nil {
-			return pulumi.ArrayOutput{}, err
-		}
-		for _, r := range rs {
+		obj := obj
```
Comment (blampe) [inline provider/pkg/provider/yaml/v2/yaml.go:187]: If this is to avoid a loop capture bug, it's not needed unless there's a closure/goroutine involved. I'd love to set `GOEXPERIMENT=loopvar` and never think about these again.

File: provider/pkg/provider/yaml/v2/yaml.go [hunk 2]
```diff
@@ -77,6 +79,7 @@ func Parse(ctx context.Context, clientSet *clients.DynamicClientSet, opts ParseO
 				if err != nil {
 					return nil, errors.Wrapf(err, "expanding glob")
 				}
+				sort.Strings(files)
```
Comment (blampe) [inline provider/pkg/provider/yaml/v2/yaml.go:82]: Does expand require these to be sorted?

**Review by blampe — COMMENTED** [review]
Looks reasonable - just some small comments/questions.

File: provider/pkg/provider/yaml/v2/yaml.go [hunk 3]
```diff
@@ -130,6 +137,41 @@ func yamlDecode(text string, _ *clients.DynamicClientSet) ([]unstructured.Unstru
 	return resources, nil
 }
 
+func Expand(objs []unstructured.Unstructured) ([]unstructured.Unstructured, error) {
```
[the remark this answers is not in the document]
Comment (EronWright) [reply provider/pkg/provider/yaml/v2/yaml.go:140]: I made it public for symmetry with `Parse` and `Register`, all of which are useful when implementing a component resource.  It so happens that `ConfigGroup` and `ConfigFile` are in the same package, but `Chart` wouldn't be.  That said, I don't anticipate any actual usages.

File: provider/pkg/provider/yaml/v2/yaml.go (hunk 2 above)
Comment (EronWright) [reply provider/pkg/provider/yaml/v2/yaml.go:82]: No, I chose to sort the files to have the globbed manifests be visited in a stable order.  The K community sometimes uses `001-crds.yaml`, `002-deployment.yaml` etc. 

To be clear, this doesn't bear on the dependencies and is just a 'best effort'.

File: provider/pkg/provider/yaml/v2/yaml.go (hunk 1 above)
Comment (EronWright) [reply provider/pkg/provider/yaml/v2/yaml.go:187]: Since we store a pointer to the loop variable (into `objs`), I thought it necessary.

File: provider/pkg/provider/yaml/v2/configfile_test.go [hunk 4]
```diff
@@ -88,7 +88,9 @@ var _ = Describe("ConfigFile.Construct", func() {
 				Expect(err).ShouldNot(HaveOccurred())
 				outputs := unmarshalProperties(GinkgoTB(), resp.State)
 				Expect(outputs).To(MatchProps(IgnoreExtras, Props{
-					"resources": MatchArrayValue(HaveExactElements(
+					"resources": MatchArrayValue(ConsistOf(
```
[the remark this answers is not in the document]
Comment (EronWright) [reply provider/pkg/provider/yaml/v2/configfile_test.go:91]: The only difference between `ConsistOf` and `HaveExactElements` is the latter has a strict ordering requirement. I don't want to impose or imply a specific ordering of the `resources` output array.

File: provider/pkg/provider/yaml/v2/yaml.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (EronWright) [reply provider/pkg/provider/yaml/v2/yaml.go:140]: BTW, I plan to rename `Expand` to `Canonicalize` in a follow-up PR (or maybe in this one) and perform a couple of other fixups.

**Comment by lblackstone** [comment]
This change also relates to the following issues:
https://github.com/pulumi/pulumi-kubernetes/issues/1098
https://github.com/pulumi/pulumi-kubernetes/issues/1671
https://github.com/pulumi/pulumi-kubernetes/issues/2227

File: provider/pkg/provider/yaml/v2/yaml.go (hunk 1 above)
Comment (rquitales) [reply provider/pkg/provider/yaml/v2/yaml.go:187]: We still need to do this since we're still using Go v1.21.
Fyi, the `GOEXPERIMENT=loopvar` preview is now the default in Go v1.22 (https://go.dev/blog/loopvar-preview). So we don't need to worry about these loop capture bugs once we upgrade to Go v1.22.

File: provider/pkg/provider/yaml/v2/yaml.go [hunk 5]
```diff
@@ -130,6 +137,41 @@ func yamlDecode(text string, _ *clients.DynamicClientSet) ([]unstructured.Unstru
...
+		//
+		// Since Kubernetes does not instantiate list types directly, Pulumi also traverses lists
+		// for resource definitions that can be managed by Kubernetes, and registers those with the
+		// engine instead.
+		if obj.IsList() {
+			list, err := obj.ToList()
+			if err != nil {
+				return nil, fmt.Errorf("YAML object is invalid: `%s`: %w", printUnstructured(&obj), err)
+			}
+			objs = append(list.Items, objs...)
```
Comment (rquitales) [inline provider/pkg/provider/yaml/v2/yaml.go:166]: I'm slightly worried about expanding list items. There is a long standing bug in upstream kubernetes/kubernetes (https://github.com/kubernetes/kubernetes/issues/3030) where attempting to get the GVK of list items return empty. In cli-utils `HydrateSetList`, it calls `UnstructuredToObjMetadata` to get the object's GVK (https://github.com/kubernetes-sigs/cli-utils/blob/7928dbf3d402196a58ae57d8377961c6dffc8e01/pkg/object/unstructured.go#L32-L38).

I'm not sure if List items would work as expected in the wild - I see you have a unit test added but I'm not sure if it will sufficiently cover this, especially given that this bug occurs for some List objects, not all. We might need a workaround for List objects.

Comment (rquitales) [reply provider/pkg/provider/yaml/v2/yaml.go:166]: After further discussions, this probably isn't a concern since these list objects are generated and consumed locally by Pulumi. It's a concern when we fetch the list objects with client-go from an API server.

**Review by rquitales — APPROVED** [review]
LGTM

File: provider/pkg/provider/yaml/v2/yaml.go (hunk 5 above)
Comment (EronWright) [reply provider/pkg/provider/yaml/v2/yaml.go:166]: It is true that this implementation doesn't infer the `kind` of items within a typed list, it expects each item to have a `kind`.  That's true of "yaml/v1" also.

Note that the code uses `unstructured.IsList()` and thus relies on this definition of a list (from [api-conventions.md](https://github.com/chrisnegus/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#types-kinds)):

> Any kind that has the "items" field must be a list kind.
