### PR TITLE
Handle different namespaces for server-side diff

### LINKED ISSUE #683: JSON patch not working properly for changed namespaces
```
Failed to check for changes in resource default/foo because of an error computing the JSON patch describing the resource changes: the namespace of the object (default) does not match the namespace on the request (foo)
```

Before:
```ts
const ns = new k8s.core.v1.Namespace("foo", {metadata: {name: "foo"}});
const provider = new k8s.Provider("bar", {namespace: ns.metadata.name});

const appLabels = { app: "nginx" };
const deployment = new k8s.apps.v1.Deployment("nginx", {
    metadata: { name: "foo"},
    spec: {
        selector: { matchLabels: appLabels },
        replicas: 1,
        template: {
            metadata: { labels: appLabels },
            spec: {
                containers: [{ name: "nginx", image: "nginx:1.14"}],
            },
        },
    }
}, {provider: provider});
```

After:
```ts
const ns = new k8s.core.v1.Namespace("foo", {metadata: {name: "foo"}});
const provider = new k8s.Provider("bar", {});

const appLabels = { app: "nginx" };
const deployment = new k8s.apps.v1.Deployment("nginx", {
    metadata: { name: "foo"},
    spec: {
        selector: { matchLabels: appLabels },
        replicas: 1,
        template: {
            metadata: { labels: appLabels },
            spec: {
                containers: [{ name: "nginx", image: "nginx:1.14"}],
            },
        },
    }
}, {provider: provider});
```

### PR DESCRIPTION
**Pull request by lblackstone**
### Proposed changes
The server-side diff logic previously tried to use the
same k8s client for calculating the patch. In the case
where the namespace of a resource changed, this
diff would fail because the client was for the old
namespace.

### Related issues (optional)
Fix #683

### CODE REVIEW

File: tests/sdk/nodejs/dry-run/step2/index.ts [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+// limitations under the License.
+
+import * as k8s from "@pulumi/kubernetes";
+import * as random from "@pulumi/random";
+import * as pulumi from "@pulumi/pulumi";
+
+// TODO(levi): Use auto-naming for namespace once https://github.com/pulumi/pulumi-kubernetes/issues/1632 is fixed.
+const suffix = new random.RandomString("suffix", {length: 7, special: false, upper: false}).result;
+const ns = new k8s.core.v1.Namespace("test", {metadata: {name: pulumi.interpolate`test-${suffix}`}});
+const provider = new k8s.Provider("k8s", {enableDryRun: true}); // Use the default namespace.
```
Comment (mikhailshilkov) [inline tests/sdk/nodejs/dry-run/step2/index.ts:22]: Consider adding a comment explaining what we are testing here, it's bit hard to spot the difference between step1 and step2 and understand why we are doing this

File: provider/pkg/provider/provider.go [hunk 2]
```diff
@@ -2201,14 +2201,25 @@ func (k *kubeProvider) serverSidePatch(
...
+		newObject, err = client.Create(context.TODO(), newInputs, metav1.CreateOptions{
 			DryRun: []string{metav1.DryRunAll},
 		})
-	case errors.IsNotFound(err):
+	case newInputs.GetNamespace() != oldInputs.GetNamespace():
+		client, err := k.clientSet.ResourceClient(newInputs.GroupVersionKind(), newInputs.GetNamespace())
+		if err != nil {
+			return nil, nil, err
+		}
 		newObject, err = client.Create(context.TODO(), newInputs, metav1.CreateOptions{
```
Comment (mikhailshilkov) [inline provider/pkg/provider/provider.go:2213]: I'm just trying to wrap my head around this... What happens with the object in the old namespace? Don't we need to delete it?

File: tests/sdk/nodejs/dry-run/step2/index.ts (hunk 1 above)
Comment (lblackstone) [reply tests/sdk/nodejs/dry-run/step2/index.ts:22]: I'll add a comment, but the idea is that the Provider in step1 specifies a namespace, and then removes that option in step2, which replaces the Deployment in the default namespace. This is equivalent to changing `.metadata.namespace` on the Deployment.

File: provider/pkg/provider/provider.go (hunk 2 above)
Comment (lblackstone) [reply provider/pkg/provider/provider.go:2213]: This method just computes the patch. The resource replacement logic happens separately from this.

**Review by viveklak — APPROVED** [review]
