### PR TITLE
Fix Ingress awaiter for ExternalName Services

### LINKED ISSUE #317: Ingress error with ExternalName Service
I am creating an Service of type ExternalName along with an Ingress that uses it like this:
```
const service = new k8s.core.v1.Service("foo", {
    metadata: {
        name: "foo",
        namespace: "default",
    },
    spec: {
        type: "ExternalName",
        externalName: "foo.s3-website-eu-west-1.amazonaws.com",
        ports: [
            {
                port: 80,
            },
        ],
    },
}, {provider: k8sProvider});

const ingress = new k8s.extensions.v1beta1.Ingress("foo", {
    metadata: {
        annotations: {
            "kubernetes.io/ingress.class": "traefik",
            "traefik.frontend.passHostHeader": "false",
            "traefik.frontend.priority": "1"
        },
        name: "foo",
        namespace: "default",
    },
    spec: {
        rules: [
            {
                host: "*.example.com",
                http: {
                    paths: [
                        {
                            backend: {
                                serviceName: "foo",
                                servicePort: 80,
                            },
                            path: "/",
                        },
                    ],
                },
            },
        ],
    },
}, {provider: k8sProvider});
```

Both are created correctly, and it works as expected (all incoming traffic to *.example.com is proxied to an S3 bucket), however Pulumi hangs with this error:
```
error: No matching service found for ingress rule: "/"
```

It appears that it's not considering Services of this type as a valid target.

### PR DESCRIPTION
**Pull request by lblackstone**
The await logic was incorrectly waiting for active Pods for all Service
types. However, Services with type: ExternalName do not have
associated Pods and should succeed as long as the Service exists.

Fixes #317

### CODE REVIEW

File: pkg/await/extensions_ingress.go [hunk 1]
```diff
@@ -50,6 +51,7 @@ type ingressInitAwaiter struct {
 	endpointsReady   bool
 	endpointsSettled bool
 	endpointExists   map[string]bool
```
Comment (hausdorff) [inline pkg/await/extensions_ingress.go]: A better name for this is now probably something like `serviceReady`, as `Service`s with type `ExternalName` don't have endpoints.

Comment (hausdorff) [reply pkg/await/extensions_ingress.go]: Arg, dammit. I'm testing out the GH extension and it apparently doesn't let you batch up review comments?

**Comment by hausdorff** [comment]
Because @lblackstone is not currently here, I've gone ahead and "addressed" my comments. To my eye, this is semantically equivalent, but with the (small) changes noted in the following list. I'd like to turn this sort of thing around pretty quick, so I'll file a follow-up issue to have @lblackstone do a post-commit review to make sure I didn't do anything silly.

* Renamed `iia.endpointExists` -> `iia.knownEndpointObjects` and `iia.externalServices` -> `iia.knownExternalNameServices`, and made both of them `sets.String`.
  * **Rationale:** Fundamentally the awaiter now checks readiness by determining if a `v1/Endpoint` object exists, but _only_ if the `v1/Service` is not of type `ExternalName`. If we maintain a set of `Endpoint`s and `Service` objects that have type `ExternalName`, it seems to make it quite simple to check whether this condition is true. We rename because we want the names to reflect this usage.
* Removed `iia.endpointsReady`, replaced all instances where we check this with `iia.checkIfEndpointsReady()`.
  * **Rationale:** Unlike `iia.ingressReady`, this field is now quite complex, and we find ourselves having to update it before every check to ensure correctness. `iia.ingressReady`, on the other hand, is set only in one place, and is fairly simple. So, we think it makes sense to just call `iia.checkIfEndpointsReady()` directly.
* When we receive a `v1/Event` indicating a deletion of a `Service` or `Endpoint`, we now delete them from `iia.knownExternalNameServices` and `iia.knownEndpointObjects`, respectively. Before, we'd keep them in a map, and set their values to `false`.
* We un-delete on of the test cases, and simply add the new test case alongside it. (I believe the deletion was originally a mistake.)
