### PR TITLE
Document await timeouts and how to override

### LINKED ISSUE #714: Document await timeout defaults
The await logic for each resource has a default timeout value set, which will cause the update to fail if it hasn't reached a ready state by that time. This works well in the majority of cases, but can cause spurious failures in some cases where the resource takes an unusually long time to be ready. We should take the following steps to make this less confusing to users:

1. Document the default timeout value for each resource that includes one.
2. Ensure that error messages for the timeout case are clear about the (possibly erroneous) failure reason, and link to information about overriding the timeout value.

### PR DESCRIPTION
**Pull request by lblackstone**
Fixes #714

### CODE REVIEW

File: pkg/gen/awaitComments.go [hunk 1]
```diff
@@ -15,15 +15,46 @@
...
 
 import (
+	"fmt"
+
 	"github.com/pulumi/pulumi-kubernetes/pkg/kinds"
 )
 
-const preamble = `This resource waits until it is ready before registering success for
+func timeoutComment(kind kinds.Kind) string {
+	const timeoutOverride = `setting 'pulumi.com/timeoutSeconds' as a '.metadata.annotation' on the resource.`
```
Comment (lblackstone) [inline pkg/gen/awaitComments.go]: Note that this will be updated to use `customTimeouts` as soon as it's implemented.

Comment (metral) [reply pkg/gen/awaitComments.go]: Is it worth linking to https://github.com/pulumi/pulumi-kubernetes/issues/672 for readers?

File: pkg/gen/awaitComments.go [hunk 2]
```diff
@@ -15,15 +15,46 @@
...
+
+	timeout := func(kind kinds.Kind) string {
```
Comment (metral) [inline pkg/gen/awaitComments.go]: Do we have any referable reasons as to why we're using the following defaults?

I lean towards setting all timeouts to a minimum default of 10 minutes, particularly for Pods, Deployments and StatefulSets since many factors can delay Pod readiness:
- Slow connection
- Slow registry
- Large Docker images being pulled
- Readiness / Liveness Probes
- PodDisruptionBudgets that take a step-wise approach to fan-outs & fan-ins

File: pkg/gen/awaitComments.go [hunk 3]
```diff
@@ -35,21 +66,25 @@ const DeploymentAwaitComment = preamble + `
...
    set to "Running".
-Or (for Jobs): The Pod succeeded ('.status.phase' set to "Succeeded").`
-
-const ServiceAwaitComment = preamble + `
+Or (for Jobs): The Pod succeeded ('.status.phase' set to "Succeeded").
+`
+	case kinds.Service:
+		comment += `
 1. Service object exists.
 2. Related Endpoint objects are created. Each time we get an update, wait ~5-10 seconds
```
Comment (metral) [inline pkg/gen/awaitComments.go]: Is there a reason we have a range of 5-10 seconds here versus a fixed amount?

File: pkg/gen/awaitComments.go (hunk 1 above)
Comment (lblackstone) [reply pkg/gen/awaitComments.go]: Sure, might as well.

File: pkg/gen/awaitComments.go (hunk 2 above)
Comment (lblackstone) [reply pkg/gen/awaitComments.go]: I don't think there was any empirical reason. I'm fine bumping them to 10 mins.

@hausdorff Thoughts?

File: pkg/gen/awaitComments.go (hunk 3 above)
Comment (lblackstone) [reply pkg/gen/awaitComments.go]: Looks like it actually has a 10s timer set. Updated the doc.

File: pkg/gen/awaitComments.go (hunk 2 above)
Comment (lblackstone) [reply pkg/gen/awaitComments.go]: I decided to pull the behavioral change out into a separate PR, and only update docs in this PR.
