### PR TITLE
Propagate cancellation to Helm Release provider action

### LINKED ISSUE #2485: Helm - v3 Release leaks resources on ctrl-c command
### What happened?

During a deployment of helm v3 release, if the user hits ctrl-c Pulumi will leak the resources that have already been created, causing the user to have to manually find and remove the kubernetes resources deployed by the Helm release.

### Expected Behavior

Any resources created should not be leaked during a ctrl-c.

### Steps to reproduce

deploy a helm release and ctrl-c during an in-flight update.

### Output of `pulumi about`

pulumi/pulumi v3.73.0
pulumi/kubernetes v3.30.0

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by EronWright**
### Proposed changes
Closes #2485.

This PR implements cancelation for `Create` and `Update` operations on the Helm Release resource. When the user presses ctrl-c, the Helm operation is cancelled and the stack state is updated accordingly. This is an improvement over the current behavior where the Helm release may be orphaned by Pulumi.

A future enhancement would be to implement cancelation for the `Delete` operation, once it becomes possible in the Helm v3 library (see [PR](https://github.com/helm/helm/pull/12109) and the `RunWithContext` variants).

_Note: no new tests are provided because I don't see a way to simulate cancelation using the integration test framework._

### Related issues (optional)

Related to https://github.com/pulumi/pulumi/issues/14057. It is safe to merge this PR beforehand.

### CODE REVIEW

File: provider/pkg/provider/provider.go [hunk 1]
```diff
@@ -2464,7 +2465,7 @@ func (k *kubeProvider) Delete(ctx context.Context, req *pulumirpc.DeleteRequest)
 
 	config := await.DeleteConfig{
 		ProviderConfig: await.ProviderConfig{
-			Context:           k.canceler.context, // TODO: should this just be ctx from the args?
```
Comment (EronWright) [inline provider/pkg/provider/provider.go:2467]: Removing the above comment because it is 4 years old, and it seems clear that the code is correct and is consistent with the other provider methods (`Create`, `Update`).

File: provider/pkg/provider/helm_release.go [hunk 2]
```diff
@@ -1102,6 +1105,7 @@ func (r *helmReleaseProvider) Delete(ctx context.Context, req *pulumirpc.DeleteR
 		}
 		uninstall.Timeout = time.Duration(timeout) * time.Second
 	}
+	// TODO: once https://github.com/helm/helm/pull/12109 is merged, use uninstall.RunWithContext
```
Comment (rquitales) [inline provider/pkg/provider/helm_release.go:1108]: Could you also create a GH issue against pulumi/pulumi-kubernetes to track this todo item/upstream dependency and link it back to this comment as well? Thanks!

**Review by rquitales — APPROVED** [review]
LGTM with a minor remark to update the code comment and create a issue tracker. Approving so this review is non-blocking.

File: provider/pkg/provider/helm_release.go (hunk 2 above)
Comment (EronWright) [reply provider/pkg/provider/helm_release.go:1108]: https://github.com/pulumi/pulumi-kubernetes/issues/2582
