### PR TITLE
Gracefully handle unreachable k8s cluster

### LINKED ISSUE #950: `refresh` and `up` fail when Kubernetes providers are deleted
Suppose I have a Kubernetes cluster with some number of resources on it, using first-class providers. Suppose also that the cluster is somehow deleted out-of-band. `refresh` and `up` will now _always_ error, because we will time out looking for the cluster. And, because we cannot in general tell the difference between a deleted cluster and a cluster that's unresponsive, this essentially cripples the Pulumi, requiring manual state surgery to fix.

I can think of at least a couple other options that seem better:

* Make it very easy to recursively remove (_e.g._) a provider and all resources that use it from the state.
* Expose some kind of option (through the CLI, _e.g._) that missing providers to be treated as "deleted", and for that delete to be recursive.

The second of these seems like it will require quite a bit more work, as it seems like we will have to plumb that information through the resource graph, so that the engine knows about the missing provider, and knows to override the timeout error of the resources running on the cluster. The first seems like it would be pretty straightforward.

### PR DESCRIPTION
**Pull request by lblackstone**
### Proposed changes
Previously, the provider erroneously expected that the default provider pointed to a functioning Kubernetes cluster. This led to unexpected failures in cases where this wasn't true, such as the user manually setting the kubeconfig value for the stack to an invalid value. This change explicitly checks for a valid configuration, and falls back to a degraded state if this check fails. This still
allows invoke logic to run during previews without requiring an active k8s cluster.

### Related issues (optional)

Fixes #950

### CODE REVIEW

**Comment by pgavlin** [comment]
Here's the approach I was starting in on until the holiday break: https://gist.github.com/pgavlin/35c55c320d9904d04aa4674ff3c9a615

I stalled out on the error classification bit. FWIW, I would rather use this sort of dynamic approach than the static approach--I would expect us to fail as we do today if the kubeconfig is invalid.

**Comment by lblackstone** [comment]
> I would rather use this sort of dynamic approach than the static approach

If I understand correctly, you want:

1. If the kubeconfig is known (not computed) AND is invalid (fails to unmarshal), then return an error
1. If the kubeconfig is known AND valid, check connectivity during `Configure` and return a specific error for an unreachable cluster

Is that right?

**Comment by lblackstone** [comment]
To follow up on that, I think my current approach on `Diff` isn't quite right. If the cluster is not reachable (e.g., in the computed provider case), the diff should be equivalent to a cluster without the resources created.

**Comment by pgavlin** [comment]
> If the kubeconfig is known (not computed) AND is invalid (fails to unmarshal), then return an error

Yes.

> If the kubeconfig is known AND valid, check connectivity during Configure and return a specific error for an unreachable cluster

Essentially, yes. As long as `Read` still operates in the case of an unreachable cluster, I think the other operations (`Check`, `Diff`, `Create`, `Update`, `Delete`) can return the original error that indicated that the cluster is unreachable. I think `Read` should return a nil state and error, and warn that the resource is not found because the cluster could not be reached. This allows `refresh` to operate on unreachable clusters (e.g. clusters that have been deleted).

**Comment by lblackstone** [comment]
@pgavlin This should be RFR now. I tested these changes locally with the invoke changes, and it seems to be working.

File: pkg/provider/provider.go [hunk 1]
```diff
@@ -376,16 +385,33 @@ func (k *kubeProvider) Configure(_ context.Context, req *pulumirpc.ConfigureRequ
 func (k *kubeProvider) Invoke(ctx context.Context,
 	req *pulumirpc.InvokeRequest) (*pulumirpc.InvokeResponse, error) {
 
+	// Important: Some invoke logic is intended to run during preview, and the Kubernetes provider
+	// inputs may not have resolved yet. Rather than returning an error here, any invoke logic must
+	// not assume that a cluster is accessible.
+	if k.clusterUnreachable {
+		glog.V(3).Infof(
+			"configured Kubernetes cluster is unreachable. Invoke call logic may operate in a degraded state.")
+	}
```
Comment (lukehoban) [inline pkg/provider/provider.go]: Do we benefit from having this at this level - or should it just live closer to the point where we actually take a dependency on the cluster - where we can report more explicitly what that implies.

File: pkg/provider/provider.go [hunk 2]
```diff
@@ -1432,6 +1475,10 @@ func (k *kubeProvider) Update(
 	// - [ ] Support server-side apply, when it comes out.
 	//
 
+	if k.clusterUnreachable {
+		return nil, fmt.Errorf("configured Kubernetes cluster is unreachable")
+	}
```
Comment (lukehoban) [inline pkg/provider/provider.go]: Minor - Should this go below the logging about executing an `Update`?  I think it would be surprising not to see that `Update` was called.

Comment (lukehoban) [reply pkg/provider/provider.go]: Also - perhaps a comment on why erroring early is correct here?

File: pkg/provider/provider.go [hunk 3]
```diff
@@ -1104,6 +1136,11 @@ func (k *kubeProvider) Create(
 	//   {inputs: {...}, live: {...}}. This is important both for `Diff` and for `Update`. See
 	//   comments in those methods for details.
 	//
+
+	if k.clusterUnreachable {
+		return nil, fmt.Errorf("configured Kubernetes cluster is unreachable")
+	}
+
```
Comment (lukehoban) [inline pkg/provider/provider.go]: Should this go after the logging of the call to `Create`?

File: tests/integration/provider/provider_test.go [hunk 4]
```diff
@@ -83,5 +83,12 @@ func TestProvider(t *testing.T) {
 			assert.NotEqual(t, providerNsName.(string), namespacedPodNamespace.(string))
 			assert.Equal(t, ns2Name.(string), namespacedPodNamespace.(string))
 		},
+		EditDirs: []integration.EditDir{
+			{
+				Dir:           "step2",
+				Additive:      false,
+				ExpectFailure: true,
```
Comment (lukehoban) [inline tests/integration/provider/provider_test.go]: Is this test really testing anything?  I assume it passed previously as well - just with a different error?

Is it worth having a test that *doesn't* fail after these changes?

File: pkg/provider/provider.go (hunk 1 above)
Comment (lblackstone) [reply pkg/provider/provider.go]: Yeah, I think that makes more sense. I'll leave a note here about the implications, but defer warnings to the point in the logic where it matters.

File: tests/integration/provider/provider_test.go (hunk 4 above)
Comment (lblackstone) [reply tests/integration/provider/provider_test.go]: Yeah, good point. I think what I really want to test is that a preview succeeds even when a cluster isn't reachable, but I don't think our test framework currently handles that case (preview only, no update).

Comment (lblackstone) [reply tests/integration/provider/provider_test.go]: Justin informed me that this is possible using `RunCommand("pulumi", "preview")`, so I'll update the test accordingly.

Comment (lblackstone) [reply tests/integration/provider/provider_test.go]: This turned out to be more difficult than I expected, so I'm opening an issue to update the test framework and will follow up on this later.

Comment (lblackstone) [reply tests/integration/provider/provider_test.go]: https://github.com/pulumi/pulumi/issues/3762
