### PR TITLE
Automatically mark Secret data as Pulumi secrets

### LINKED ISSUE #999: Secrets in Helm chart resource are plaintext in state file
### Problem description

When a Pulumi secret is used in a Helm chart resource, its plaintext value ends up in the Pulumi state file where in other resource types its encrypted value is used as expected.

### Affected product version(s)

- Pulumi CLI - `v1.10.1`
- [package-lock-json](https://gist.github.com/clstokes/a9192849a157307438a433162c16dfc1#file-package-lock-json)

### Reproducing the issue

Code to reproduce - https://gist.github.com/clstokes/a9192849a157307438a433162c16dfc1.

1. `pulumi stack init gh-issue`
1. `pulumi config set mySecret asdf1234`
1. `pulumi up`
1. `pulumi stack export`
    1. observe the value `asdf1234` appears multiple times including in `kubectl.kubernetes.io/last-applied-configuration` annotations

### LINKED ISSUE #1353: Kubernetes secrets created by helm are saved as plaintext in the state
It seems that pulumi doesn't encrypt the data property of Kubernetes secrets when it is saved to the state. 
I'm doing the following to deploy charts:

```
helmv3.NewChart(ctx, deploymentName, chartArgs, pulumi.Provider(p))
```

I tried using local file backend and s3 backend and had the same result.
My encryption provider is `passphrase`

### PR DESCRIPTION
**Pull request by lblackstone**
### Proposed changes
To avoid inadvertently leaking sensitive data into the Pulumi
state for Kubernetes v1/Secret resources, this change manually
marks the "stringData" and "data" fields as secret. The output
fields were already marked as secret.

This combination will also prevent sensitive data that appears
in raw YAML from the YAML and Helm SDKs from appearing
in the state.

### Related issues (optional)
Fix #999 
Fix #1353

### CODE REVIEW

File: sdk/nodejs/yaml/yaml.ts [hunk 1]
```diff
@@ -3069,6 +3069,14 @@ export interface ConfigOpts {
     if (resourcePrefix !== undefined) {
         id = pulumi.concat(resourcePrefix, "-", id);
     }
+
+    if (gvk === "v1/Secret") {
```
Comment (viveklak) [inline sdk/nodejs/yaml/yaml.ts:3073]: Should we merge this with the switch case for `v1/Secret` in the block that follows instead?

Comment (lblackstone) [reply sdk/nodejs/yaml/yaml.ts:3073]: I kept it separate because it's nontrivial to update the mustache template generating this file otherwise. Otherwise, yes. :)

Comment (viveklak) [reply sdk/nodejs/yaml/yaml.ts:3073]: Ah missed that. Gotcha. Looks good! 

Optional - perhaps factor this out to a function so it doesn't distract from the rest of the parsing stuff?

Comment (viveklak) [reply sdk/nodejs/yaml/yaml.ts:3073]: I guess we now need to do this for all the other languages.

Comment (lblackstone) [reply sdk/nodejs/yaml/yaml.ts:3073]: > I guess we now need to do this for all the other languages.

Yep, just fighting with typing on C#, but nearly done. Pushed Python and Go.

File: sdk/python/pulumi_kubernetes/yaml.py [hunk 2]
```diff
@@ -463,6 +463,13 @@ def _parse_yaml_object(
             lambda identifier: f"{resource_prefix}-{identifier}")
 
     gvk = f"{api_version}/{kind}"
+
+    if gvk == "v1/Secret":
+        # Manually mark these fields as secret to avoid leaking sensitive values from raw YAML.
+        for key in ['data', 'string_data']:
```
Comment (lukehoban) [inline sdk/python/pulumi_kubernetes/yaml.py:469]: Curious - Are these the only sensitive input fields in the entire Kubernetes API?

Comment (lblackstone) [reply sdk/python/pulumi_kubernetes/yaml.py:469]: Those are the only ones I can think of that would ~always be sensitive.

File: sdk/go/kubernetes/yaml/yaml.go [hunk 3]
```diff
@@ -356,6 +356,15 @@ func parseYamlObject(ctx *pulumi.Context, obj map[string]interface{}, transforma
 
 	key := fmt.Sprintf("%s::%s", fullKind, metaName)
 
+	if fullKind == "v1/Secret" {
```
Comment (lblackstone) [inline sdk/go/kubernetes/yaml/yaml.go:359]: For the Go SDK, I had to make this change in two places since the YAML support bypasses the `NewSecret` constructor in favor of manually registering the resource with `UntypedArgs`.

Comment (viveklak) [reply sdk/go/kubernetes/yaml/yaml.go:359]: Just confirming that the same is not true for other sdks' yaml support (bypassing resource construction in favor of manually registering resources)? Would also be good to cut tickets to track such deviations across SDKs.

**Comment by viveklak** [comment]
This seems important enough for us to have a test case for each sdk?

File: sdk/go/kubernetes/yaml/yaml.go (hunk 3 above)
Comment (lblackstone) [reply sdk/go/kubernetes/yaml/yaml.go:359]: This is true for both .NET and Go due to the stricter typing in those SDKs.

**Comment by lblackstone** [comment]
@viveklak Added tests and finished the .NET implementation

**Review by viveklak — APPROVED** [review]

**Comment by viveklak** [comment]
Looks like there might be some test failures? Looks good otherwise!

**Comment by lukehoban** [comment]
Overriding the generated files with these point-in-time snapshots feels like it introduces non-trivial maintainability debt - and a lot of ways we could accidentally not pick up other codegen and/or functionality changes in the future. 

Could we just improve the code generators to support generating the right thing here? (A secret annotation on inputs)?

**Comment by lblackstone** [comment]
> Could we just improve the code generators to support generating the right thing here?

Most likely, but I wanted to make sure everything was working as expected in the k8s provider first. My intention is to follow up with the schema changes in the near term. Since all of these tests will already be in place, it should be easier to make sure the codegen is working as expected.

**Comment by lblackstone** [comment]
I started working on the code generators to see how difficult it would be to generalize this, and am about halfway done with the required changes now. My plan for this PR is:

1. Finish the codegen changes, and manually update the template files to match the expected output
2. Merge this PR with the TODO's for updating to codegen
3. Remove the templates + overrides when we bump the p/p dependency after the next release

**Comment by lblackstone** [comment]
Codegen changes are here: https://github.com/pulumi/pulumi/pull/7128
