### PR TITLE
Fix continuous diff for Secret stringData field

### LINKED ISSUE #2507: v1/Secret always in diff when using stringData with v4.0.1
### What happened?

Having a secret as following always results in a diff and pulumi trying to recreate the secret on every run
This works (without a diff) with `@pulumi/kubernetes 3.30.2`

### Expected Behavior

No diff on `pulumi pre//up`

### Steps to reproduce

```
import { Provider } from '@pulumi/kubernetes/provider';
import { Secret } from '@pulumi/kubernetes/core/v1/secret';

const k8sProvider = new Provider('k8sProvider', {
  context: 'mycontext',
});

  new Secret(
    'diff',
    {
      stringData: {
        diff: 'yep',
      },
    },
    {
      provider: k8sProvider,
    }
  );
```

output:
```
pulumi up
Previewing update (orotest):
     Type                          Name                Plan        Info
     pulumi:pulumi:Stack           k8s-4x-bug-orotest              
 +-  └─ kubernetes:core/v1:Secret  diff                replace     [diff: +stringData]


Resources:
    +-1 to replace
    2 unchanged

Do you want to perform this update? details
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:orotest::k8s-4x-bug::pulumi:pulumi:Stack::k8s-4x-bug-orotest]
    ++kubernetes:core/v1:Secret: (create-replacement)
        [id=default/diff-ce1859b6]
        [urn=urn:pulumi:orotest::k8s-4x-bug::kubernetes:core/v1:Secret::diff]
        [provider=urn:pulumi:orotest::k8s-4x-bug::pulumi:providers:kubernetes::k8sProvider::70b9e47c-3365-46c7-a284-14f1c1195b35]
      + stringData: [secret]
    +-kubernetes:core/v1:Secret: (replace)
        [id=default/diff-ce1859b6]
        [urn=urn:pulumi:orotest::k8s-4x-bug::kubernetes:core/v1:Secret::diff]
        [provider=urn:pulumi:orotest::k8s-4x-bug::pulumi:providers:kubernetes::k8sProvider::70b9e47c-3365-46c7-a284-14f1c1195b35]
      + stringData: [secret]
    --kubernetes:core/v1:Secret: (delete-replaced)
        [id=default/diff-ce1859b6]
        [urn=urn:pulumi:orotest::k8s-4x-bug::kubernetes:core/v1:Secret::diff]
        [provider=urn:pulumi:orotest::k8s-4x-bug::pulumi:providers:kubernetes::k8sProvider::70b9e47c-3365-46c7-a284-14f1c1195b35]
```

### Output of `pulumi about`

```
CLI          
Version      3.60.1
Go Version   go1.20.4
Go Compiler  gc

Plugins
NAME        VERSION
kubernetes  4.0.1
nodejs      unknown

Host     
OS       nixos
Version  23.11 (Tapir)
Arch     x86_64

This project is written in nodejs: executable='/nix/store/w1ipv1cmppqbqrpwxi9acdxz7grrdz34-devenv-profile/bin/node' version='v18.16.0'

Current Stack: orotest

TYPE                         URN
pulumi:pulumi:Stack          urn:pulumi:orotest::k8s-4x-bug::pulumi:pulumi:Stack::k8s-4x-bug-orotest
pulumi:providers:kubernetes  urn:pulumi:orotest::k8s-4x-bug::pulumi:providers:kubernetes::k8sProvider
kubernetes:core/v1:Secret    urn:pulumi:orotest::k8s-4x-bug::kubernetes:core/v1:Secret::diff


Found no pending operations associated with orotest

Backend        
Name           OroFramework
URL            file://./
User           oro
Organizations  

Dependencies:
NAME                VERSION
typescript          5.1.6
@pulumi/kubernetes  4.0.1
@types/node         18.16.19

Pulumi locates its logs in /tmp by default
```

### Additional context

It seems to be connected to using `stringData, as the following works (i.e. no diff on subsequent runs)

```
  new Secret(
    'no-diff',
    {
      data: {
        diff: Buffer.from('nope').toString("base64"),
      },
    },
    {
      provider: k8sProvider,
    }
  );
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by lblackstone**
### Proposed changes
If the `stringData` field is set on a Secret resource, then Kubernetes will automatically replace it with an equivalent `data` field. This is causing a continuous diff with the updated logic from 6e329f3. This change updates the input diff logic to include this rewrite.

### Related issues (optional)
Fix #2507

### CODE REVIEW

**Comment by lblackstone** [comment]
The test fails without this change. It looks like it was erroneously expecting refresh changes before, which covered up this regression.

**Comment by lblackstone** [comment]
Not sure why the lint step failed. It's passing for me locally.

File: provider/pkg/clients/unstructured.go [hunk 1]
```diff
@@ -65,22 +65,35 @@ func ToUnstructured(object metav1.Object) (*unstructured.Unstructured, error) {
 // This process normalizes semantically-equivalent resources into an identical output, which is important for diffing.
 // If the scheme is not defined, then return the original resource.
 func Normalize(uns *unstructured.Unstructured) (*unstructured.Unstructured, error) {
+	var result *unstructured.Unstructured
+
 	if IsCRD(uns) {
```
Comment (rquitales) [inline provider/pkg/clients/unstructured.go:70]: nit: preference for switch case here, but will follow up in a later PR/discussion to get this fix out ASAP.

**Review by rquitales — APPROVED** [review]
LGTM, minor comment that we can follow up later.

File: provider/pkg/clients/unstructured.go [hunk 2]
```diff
@@ -65,22 +65,35 @@ func ToUnstructured(object metav1.Object) (*unstructured.Unstructured, error) {
...
+	} else {
+		obj, err := FromUnstructured(uns)
+		// Return the input resource rather than an error if this operation fails.
+		if err != nil {
+			return uns, nil
+		}
+		result, err = ToUnstructured(obj)
+		// Return the input resource rather than an error if this operation fails.
+		if err != nil {
+			return uns, err
```
Comment (EronWright) [inline provider/pkg/clients/unstructured.go:83]: Was it intentional to return the `err` here? The comment seems to say otherwise.

File: provider/pkg/clients/unstructured.go [hunk 3]
```diff
@@ -65,22 +65,35 @@ func ToUnstructured(object metav1.Object) (*unstructured.Unstructured, error) {
...
 	if IsCRD(uns) {
-		return normalizeCRD(uns), nil
+		result = normalizeCRD(uns)
+	} else if IsSecret(uns) {
+		result = normalizeSecret(uns)
+	} else {
+		obj, err := FromUnstructured(uns)
+		// Return the input resource rather than an error if this operation fails.
+		if err != nil {
+			return uns, nil
```
Comment (EronWright) [inline provider/pkg/clients/unstructured.go:78]: Was it intentional to ignore all errors, e.g. a value parsing error? For example, given `creationTimestamp: invalid_value`, a time parser error is caught and ignored.

**Review by EronWright — COMMENTED** [review]
Leaving some remarks as I am reviewing this PR for an unrelated issue.
