### PR TITLE
fix: infer default namespace unless provided by provider config

### LINKED ISSUE #971: Provider ignores the `namespace` setting from the current-context
### Problem description

The provider currently assumes that if no namespace is provided for resource operations, then `default` should be used. This differs from `kubectl`'s behavior, which will use the value from `.context.namespace` if one is set. We should update the provider to use this default value if no other `namespace` value is set (on the resource or via stack config).

This wouldn't affect resources using first-class providers to specify a k8s cluster, only ones using the default provider.

### PR DESCRIPTION
**Pull request by rawkode**
### Proposed changes

Use the discovered kubeconfig namespace when one isn't provided by the Provider configuration instead of default.

### Related issues (optional)

Fix #971

### CODE REVIEW

File: provider/pkg/provider/provider.go [hunk 1]
```diff
@@ -683,10 +683,11 @@ func (k *kubeProvider) Configure(_ context.Context, req *pulumirpc.ConfigureRequ
 	}
 
 	var err error
-	namespace := "default"
-	if k.defaultNamespace != "" {
+	namespace, _, err := kubeconfig.Namespace()
+	if err != nil || k.defaultNamespace != "" {
```
Comment (viveklak) [inline provider/pkg/provider/provider.go:687]: I think you want to set defaultNamespace to kubeconfig.Namespace() if it is non-empty and if the default namespace is not explicitly specified for the provider.

Comment (rawkode) [reply provider/pkg/provider/provider.go:687]: Maybe I misunderstood, but `k.defaultNamespace` is the namespace configured in the `k8s.Provider`.

The original code sets `namespace` to that value, so I thought it best to do the same; I don't believe `k.defaultNamespace` is used any further?

Comment (rawkode) [reply provider/pkg/provider/provider.go:687]: Though `k.defaultNamespace` is also used at line 1279. I'm not terribly familiar with this code.

**Comment by rawkode** [comment]
@viveklak OK, I spent some time this morning going through this code properly and I understand the problem now. I've updated the PR.

I have no idea how to write a unit test for the `Configure` method or if that's even possible, so I've done manual testing locally with the built provider binary.

Setup:

`pulumi new kubernetes-typescript`

Test 1:

- I added `namespace: test-me` to the context for my local Kubernetes cluster
- `pulumi up`
- Resource was created in `test-me` namespace

Test 2:

- Continue from above
- `pulumi config set kubernetes:namespace default`
- `pulumi up`
- Resource is replaced and deployed to `default` namespace

I believe this is the behaviour that we need to resolve #971 

cc @lblackstone

File: CHANGELOG.md [hunk 2]
```diff
@@ -1,3 +1,7 @@
+## Unreleased
+
+- Infer default namespace from kubeconfig when not configured via the provider
```
Comment (lblackstone) [inline CHANGELOG.md:3]:
```suggestion
- Infer default namespace from kubeconfig when not configured via the provider (https://github.com/pulumi/pulumi-kubernetes/pull/1896)
```

**Review by lblackstone — APPROVED** [review]
