### PR TITLE
Fix import for Provider using server-side diff

### LINKED ISSUE #1849: Cannot import resources to a provider which enables sever-side-apply
## Hello!
<!-- Please leave this section as-is, it's designed to help others in the community know how to interact with our GitHub issues. -->

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I could not import an existing Kubernetes resource to Pulumi with `pulumi import` command if the Kubernetes provider is initialized with `enableDryRun` option, server-side-apply.

### Steps to reproduce

Pulumi version: v3.20.0
Kubernetes provider version: v3.12.1

```bash
$ pulumi version     
v3.20.0

$ pulumi plugin ls
NAME        KIND      VERSION  SIZE   INSTALLED  LAST USED
kubernetes  resource  3.12.1   77 MB  n/a        1 minute ago

TOTAL plugin cache size: 77 MB
```

Pulumi script:
```typescript
import * as k8s    from "@pulumi/kubernetes";

const provider   = new k8s.Provider("K8sProvider", {enableDryRun: true})
```

1. Initialize a stack and the provider.
```bash
$ pulumi up
Previewing update (test):                                             
     Type                            Name         Plan                                                                                       
 +   pulumi:pulumi:Stack             local-test   create                                                                                     
 +   └─ pulumi:providers:kubernetes  K8sProvider  create                                                                                     
                                                                                                                                             
Resources:                                                            
    + 2 to create                                                     

Do you want to perform this update? yes                                                                                                      
Updating (test):                                                      
     Type                            Name         Status                                                                                     
 +   pulumi:pulumi:Stack             local-test   created                                                                                    
 +   └─ pulumi:providers:kubernetes  K8sProvider  created                                                                                    
                                                                      
Resources:                                                            
    + 2 created                                                       

Duration: 2s 
```

2. Import an existing Kubernetes service
```bash
# check resource
$ kubectl -n test-namespace get service
NAME    TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)    AGE
dummy   ClusterIP   10.0.73.2    <none>        9000/TCP   3m

# import
$ pulumi import kubernetes:core/v1:Service dummy test-maxi-namespace/dummy --provider="K8sProvider=urn:pulumi:test::local::pulumi:providers:kubernetes::K8sProvider"
Previewing import (test):
     Type                           Name        Plan       Info
     pulumi:pulumi:Stack            local-test             1 error
 =   └─ kubernetes:core/v1:Service  dummy       import     1 error
 
Diagnostics:
  pulumi:pulumi:Stack (local-test):
    error: preview failed
 
  kubernetes:core/v1:Service (dummy):
    error: Preview failed: Failed to check for changes in resource default/ because of an error serializing the JSON patch describing resource changes: unexpected end of JSON input
```

Expected: import completed successfully
Actual: failed as shown above

Even with `--skip-preview` the import failed.
```bash
$ pulumi import kubernetes:core/v1:Service dummy test-maxi-namespace/dummy --provider="K8sProvider=urn:pulumi:test::local::pulumi:providers:kubernetes::K8sProvider" --skip-preview
Importing (test):
     Type                           Name        Status                   Info
     pulumi:pulumi:Stack            local-test  **failed**               1 error
 =   └─ kubernetes:core/v1:Service  dummy       **importing failed**     1 error
 
Diagnostics:
  pulumi:pulumi:Stack (local-test):
    error: update failed
 
  kubernetes:core/v1:Service (dummy):
    error: Failed to check for changes in resource default/ because of an error serializing the JSON patch describing resource changes: unexpected end of JSON input
 
Resources:
    2 unchanged

Duration: 1s
```

Please let me know if I am missing something.

### PR DESCRIPTION
**Pull request by lblackstone**
### Related issues (optional)
Fix #1849

### CODE REVIEW

File: provider/pkg/provider/provider.go [hunk 1]
```diff
@@ -2552,6 +2552,9 @@ func (k *kubeProvider) tryServerSidePatch(oldInputs, newInputs *unstructured.Uns
 			return nil, nil, false
 		}
 	}
+	if err != nil {
+		return nil, nil, false
+	}
```
Comment (viveklak) [inline provider/pkg/provider/provider.go:2557]: Should we add an integration test?

**Review by viveklak — APPROVED** [review]

File: provider/pkg/provider/provider.go (hunk 1 above)
Comment (lblackstone) [reply provider/pkg/provider/provider.go:2557]: I worked on this for awhile today, but can't figure out a reasonable way to test with our existing framework since the bug is specific to using the CLI import command. Since the fix is just handling an unhandled error case, I'm going to defer testing for now.
