### PR TITLE
Fix various typegen issues

### LINKED ISSUE #152: Accept actual Namespace resources wherever a namespace name is accepted
Right now ObjectMetadata.namespace is typed as Input<string>.  It would be nice if it could actually take a core.Namespace instance.

### LINKED ISSUE #444: We should not populate `.status` in the input types
Users are not allowed to change this anyway, so it's pointless to do.

### LINKED ISSUE #728: Kubernetes Python docs missing many things
There are a lot of key things missing in our Kubernetes Python docs.

We should align our Python code generation with tfgen code generation.

Two most obvious issues:
- Resources have no properties
- Resource constructors have no documentation detailing parameter types/info

Kubernetes Python docs:

Screen Shot 2019-08-21 at 4 52 44 PM

vs. tfgen Python docs:

Screen Shot 2019-08-21 at 4 57 09 PM
Screen Shot 2019-08-21 at 4 57 24 PM

### PR DESCRIPTION
**Pull request by hausdorff**
Fixes #444.
Fixes #728.

### CODE REVIEW

**Comment by hausdorff** [comment]
Oops, forgot Python. Will come back for it soon...

File: pkg/gen/typegen.go [hunk 1]
```diff
@@ -301,7 +300,18 @@ func makeTypescriptType(prop map[string]interface{}, opts groupOpts) string {
 					}
 				}
 			}
+		} else if tstr == "string" && resourceType == "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta" && propName == "namespace" {
+			// Special case: `.metadata.namespace` should either take a string or a namespace object
```
Comment (pgavlin) [inline pkg/gen/typegen.go]: Is there anything else you can think of that ought to behave like this? If so, is it worth doing something a bit more general-purpose (ala the `pulumi-terraform` `AltTypes` approach)?

File: sdk/nodejs/admissionregistration/v1beta1/MutatingWebhookConfiguration.ts [hunk 2]
```diff
@@ -77,7 +78,23 @@ import { getVersion } from "../../version";
        * @param opts A bag of options that control this resource's behavior.
        */
       constructor(name: string, args?: inputApi.admissionregistration.v1beta1.MutatingWebhookConfiguration, opts?: pulumi.CustomResourceOptions) {
+          // In Kubernetes, `.metadata.namespace` must be a `string`. In Pulumi, we allow users to
+          // pass in `string | core.v1.Namespace`. Thus, if the user has provided a
+          // `core.v1.Namespace`, we convert it to a `string` representing that namespace's name.
```
Comment (pgavlin) [inline sdk/nodejs/admissionregistration/v1beta1/MutatingWebhookConfiguration.ts]: I think that you can avoid this code iff the a `Namespace`'s `id` is its name: the RPC layer marshals a `Resource` instance as the value of its `id` field.

File: pkg/gen/typegen.go (hunk 1 above)
Comment (hausdorff) [reply pkg/gen/typegen.go]: I actually can, but as they are vastly more specific, we had planned to deal with these in kx instead.

Arguably, this should have gone into kx instead, too, but it's common enough that I'm willing to break from our "pure k8s API" stance.

File: sdk/nodejs/admissionregistration/v1beta1/MutatingWebhookConfiguration.ts (hunk 2 above)
Comment (hausdorff) [reply sdk/nodejs/admissionregistration/v1beta1/MutatingWebhookConfiguration.ts]: We could do this, but in the longer term I wasn't sure whether this would be the `id` ([_cf_](https://github.com/pulumi/pulumi-kubernetes/issues/353).), and in any event, I personally value the explicitness of encoding relationship between resource as code vs. using parts of the Pulumi protocol that happen to contain that info, just to shorten the code. My 2 cents.

Comment (pgavlin) [reply sdk/nodejs/admissionregistration/v1beta1/MutatingWebhookConfiguration.ts]: > I personally value the explicitness of encoding relationship between resource as code vs. using parts of the Pulumi protocol that happen to contain that info, just to shorten the code. My 2 cents.

That's fair. I don't think of this as a nice coincidence, though--the fact that we marshal resources as IDs is very intentional, and is designed to support exactly this sort of scenario without the boilerplate.

File: pkg/gen/nodejs-templates/kind.ts.mustache [hunk 3]
```diff
@@ -52,10 +53,29 @@ import { getVersion } from "../../version";
        * @param opts A bag of options that control this resource's behavior.
        */
       constructor(name: string, args?: inputApi.{{Group}}.{{Version}}.{{Kind}}, opts?: pulumi.CustomResourceOptions) {
+          // In Kubernetes, `.metadata.namespace` must be a `string`. In Pulumi, we allow users to
+          // pass in `string | core.v1.Namespace`. Thus, if the user has provided a
+          // `core.v1.Namespace`, we convert it to a `string` representing that namespace's name.
+          args &&
```
Comment (pgavlin) [inline pkg/gen/nodejs-templates/kind.ts.mustache]: I think that this code just won't work at all:
- The result of the `apply` is never awaited
- Mutating the inputs is probably not a good idea (what if they are shared amongst multiple resources?) if it works at all (and it may not, cc @lukehoban)
- Because `core.v1.Namespace.metadata.name` is itself an output, we may lose dependency information if it is injected inside an `apply` (not 100% sure here, but this definitely happens when an output is _resolved_ to another output)

Comment (hausdorff) [reply pkg/gen/nodejs-templates/kind.ts.mustache]: I think this should work because the `name` is guaranteed to be present after the `Check`, but you're right that this is not acceptable to ship. Let's fix.

Comment (hausdorff) [reply pkg/gen/nodejs-templates/kind.ts.mustache]: I've cleaned this up a bit -- I'm still on the fence about whether we should move `unpackNamespace` out into a utility function in some other file. I'm less concerned that normal because it's all code-gen'd, but if there was a good place to put it I'd be open to moving it out.

**Comment by lukehoban** [comment]
@hausdorff Are we going to finish this off and land it?  There also appear to be a couple unrelated issues being solved here - and the more critical ones may be less contentious so if we need to land those separately we should do so.

**Comment by lukehoban** [comment]
@hausdorff What's the status of this?

File: pkg/gen/nodejs-templates/kind.ts.mustache [hunk 4]
```diff
@@ -54,10 +55,37 @@ import { getVersion } from "../../version";
...
+              }
+
+              return { ...metadata, namespace };
+          }
+
+          // In Kubernetes, `.metadata.namespace` must be a `string`. In Pulumi, we allow users to
+          // pass in `string | core.v1.Namespace`. Thus, if the user has provided a
+          // `core.v1.Namespace`, we convert it to a `string` representing that namespace's name.
+          if (args !== undefined && args.metadata !== undefined) {
+              args = { ...args, metadata: pulumi.output(args.metadata).apply(unpackNamespace) };
```
Comment (pgavlin) [inline pkg/gen/nodejs-templates/kind.ts.mustache]: I have a feeling that there is a subtle issue here if `args.metadata` is an `Output` with a `Namespace` instance passed as `metadata.namespace`. In that case, we would be resolving an `Output` to another `Output`, which does not properly track dependency information due to a bug in the Pulumi SDK. This PR was intended to fix that bug: https://github.com/pulumi/pulumi/pull/2288

While the namespace change would be nice to have, I think it's safer not to take it for 1.0.

Comment (pgavlin) [reply pkg/gen/nodejs-templates/kind.ts.mustache]: If we do want to take the namespace change, I think that we can just change the input type signature and leave this up to the marshalling layer, which will marshal the `Namespace` instance as its ID (which is its name).

Comment (hausdorff) [reply pkg/gen/nodejs-templates/kind.ts.mustache]: Ok, let's pull it out then.

File: pkg/gen/nodejs-templates/kind.ts.mustache [hunk 5]
```diff
@@ -2,6 +2,7 @@
 // *** Do not edit by hand unless you're certain you know what you are doing! ***
 
 import * as pulumi from "@pulumi/pulumi";
+import { core } from "../..";
```
Comment (lblackstone) [inline pkg/gen/nodejs-templates/kind.ts.mustache]: Looks like this isn't always required, but probably doesn't hurt to leave it for simplicity's sake?

File: sdk/nodejs/types/input.ts [hunk 6]
```diff
@@ -21839,12 +21537,6 @@ export namespace storage {
        */
       metadata?: pulumi.Input<meta.v1.ObjectMeta>
 
-      /**
-       * Status of the VolumeAttachment request. Populated by the entity completing the attach or
-       * detach operation, i.e. the external-attacher.
-       */
-      status?: pulumi.Input<storage.v1beta1.VolumeAttachmentStatus>
```
Comment (lblackstone) [inline sdk/nodejs/types/input.ts]: Will this be a breaking change for anybody who was setting `.status` for some reason?

File: sdk/python/pulumi_kubernetes/admissionregistration/v1beta1/MutatingWebhookConfiguration.py [hunk 7]
```diff
@@ -41,6 +72,8 @@ def __init__(self, resource_name, opts=None, metadata=None, webhooks=None, __nam
         __props__['metadata'] = metadata
         __props__['webhooks'] = webhooks
 
+        __props__['status'] = None
```
Comment (lblackstone) [inline sdk/python/pulumi_kubernetes/admissionregistration/v1beta1/MutatingWebhookConfiguration.py]: Wouldn't this be the case by default?

File: tests/integration/query/step1/index.ts [hunk 8]
```diff
@@ -23,7 +23,7 @@ const namespace = new k8s.core.v1.Namespace("test-namespace");
 
 new k8s.core.v1.Pod("query-test", {
     metadata: {
-        namespace: namespace.metadata.name,
+        namespace: namespace,
```
Comment (lblackstone) [inline tests/integration/query/step1/index.ts]: Didn't you revert this change with a TODO?

File: pkg/gen/python-templates/version__init__.py.mustache [hunk 9]
```diff
@@ -4,5 +4,5 @@
 
 # Export this package's modules as members:
 {{#Kinds}}
-from .{{Kind}} import *
-{{/Kinds}}
+from .{{Kind}} import ({{Kind}})
+{{/Kinds}}
```
Comment (lblackstone) [inline pkg/gen/python-templates/version__init__.py.mustache]: Missing newline

File: pkg/gen/nodejs-templates/kind.ts.mustache [hunk 10]
```diff
@@ -54,10 +55,14 @@ import { getVersion } from "../../version";
        * @param opts A bag of options that control this resource's behavior.
        */
       constructor(name: string, args?: inputs.{{Group}}.{{Version}}.{{Kind}}, opts?: pulumi.CustomResourceOptions) {
-          const props: pulumi.Inputs = {};
-          {{#Properties}}
+          let props: pulumi.Inputs = {};
```
[the remark this answers is not in the document]
Comment (justinvp) [reply pkg/gen/nodejs-templates/kind.ts.mustache]: I changed it to `const` as there was no need for it to be `let` AFAICT.

File: sdk/nodejs/types/input.ts (hunk 6 above)
Comment (hausdorff) [reply sdk/nodejs/types/input.ts]: Why would it? You can't set `.status`.

File: sdk/python/pulumi_kubernetes/admissionregistration/v1beta1/MutatingWebhookConfiguration.py (hunk 7 above)
Comment (hausdorff) [reply sdk/python/pulumi_kubernetes/admissionregistration/v1beta1/MutatingWebhookConfiguration.py]: No. You have to set it manually.

File: pkg/gen/nodejs-templates/kind.ts.mustache (hunk 5 above)
Comment (hausdorff) [reply pkg/gen/nodejs-templates/kind.ts.mustache]: Yes.
