### PR TITLE
Fix various usability problems in `yaml.*`

### LINKED ISSUE #448: ConfigGroup does not load urls
This should be implemented, according to #150, but when I try to load several yamls by url with ConfigGroup, it does not work. ConfigFile works:
```
new k8s.yaml.ConfigGroup("jenkins-operator", {
    files: [
        'https://raw.githubusercontent.com/VirtusLab/jenkins-operator/master/deploy/crds/virtuslab_v1alpha1_jenkins_crd.yaml',
        'https://raw.githubusercontent.com/VirtusLab/jenkins-operator/master/deploy/service_account.yaml',
        'https://raw.githubusercontent.com/VirtusLab/jenkins-operator/master/deploy/role.yaml',
        'https://raw.githubusercontent.com/VirtusLab/jenkins-operator/master/deploy/role_binding.yaml',
        'https://raw.githubusercontent.com/VirtusLab/jenkins-operator/master/deploy/operator.yaml',
    ],
    transformations: [
        (obj => obj.metadata.namespace = namespace)
    ]
}, {
    providers: {
        kubernetes: k8sProvider
    }
});
```

### LINKED ISSUE #501: Error parsing unquoted timestamp in ConfigGroup
Trying to add a YAML file as ConfigGroup like this:

```typescript
let linkerdCG = new k8s.yaml.ConfigGroup("linkerd-cg",
    {
        files: "t.yaml",
    },
    {
        providers: {
            kubernetes: kubernetesCluster.kubernetesProvider
        },
        dependsOn: [ kubernetesCluster.kubernetesProvider ]
    }
);
```

with `t.yaml`'s content being:

```yaml
---
kind: Namespace
apiVersion: v1
metadata:
  name: linkerd
  annotations:
    linkerd.io/inject: disabled
---
kind: Secret
apiVersion: v1
metadata:
  name: linkerd-identity-issuer
  namespace: linkerd
  labels:
    linkerd.io/control-plane-component: identity
  annotations:
    linkerd.io/created-by: linkerd/cli edge-19.3.3
    linkerd.io/identity-issuer-expiry: 2020-03-25T13:37:11Z
data:
  crt.pem: ZXhhbXBsZQ==
  key.pem: dmFsdWU=
```

results in an error:

```
error: Plan apply failed: Secret in version "v1" cannot be handled as a Secret: v1.Secret.ObjectMeta: v1.ObjectMeta.Annotations: ReadString: expects " or n, but found {, error found in #10 byte of ...|-expiry":{}},"labels|..., bigger context ...|edge-19.3.3","linkerd.io/identity-issuer-expiry":{}},"labels":{"app.kubernetes.io/managed-by":"pulum|...
```

`kubectl apply -f t.yaml` succeeds, also if the date at the error position is double-quoted (`"2020-03-25T13:37:11Z"`) it succeeds.

### LINKED ISSUE #502: Errors when YAML parsing fails are not intuitive
If you point `k8s.yaml.ConfigFile` at a URL that doesn't exist, but you still have transforms, you get an error like this:

```
error: Running program '/Users/erinkrengel/workspace/pulumi/gke-hello-world' failed with an unhandled exception:
    error: TypeError: Cannot read property 'labels' of undefined
        at k8s.yaml.ConfigFile.transformations (/Users/erinkrengel/workspace/pulumi/gke-hello-world/index.ts:116:30)
        at parseYamlObject (/Users/erinkrengel/workspace/pulumi/gke-hello-world/node_modules/@pulumi/kubernetes/provider.js:144:13)
        at parseYamlDocument (/Users/erinkrengel/workspace/pulumi/gke-hello-world/node_modules/@pulumi/kubernetes/provider.js:125:33)
```

This is confusing, since the error we should get is that the URL doesn't exist.

This happens in other places, too, so we should probably fix it.

### PR DESCRIPTION
**Pull request by hausdorff**
Fixes #448.
Fixes #502.
Fixes #501.

### CODE REVIEW

File: pkg/gen/nodejs-templates/yaml.ts.mustache [hunk 1]
```diff
@@ -235,20 +251,36 @@ import * as outputApi from "../types/output";
...
+                    }, {parent: this})
+                } catch (e) {
+                    throw Error(`Error fetching YAML file '${fileId}': ${e}`);
+                }
+            }));
         }
     }
 
+    /** @ignore */ function isUrl(s: string): boolean {
+        return s.startsWith("http://") || s.startsWith("https://")
```
Comment (pgavlin) [inline pkg/gen/nodejs-templates/yaml.ts.mustache]: Should we be instead attempt to parse a URL with https://nodejs.org/api/url.html#url_class_url and return `true` if parsing succeeds? This would allow us to handle file URLs, etc.

Comment (pgavlin) [reply pkg/gen/nodejs-templates/yaml.ts.mustache]: (I do see that what you've written matches the prior behavior of `ConfigFile`, so no urgency here)
