### PR TITLE
Fix pulumi access token

### LINKED ISSUE #3778: Workflow failure: main
## Workflow Failure

[main](https://github.com/pulumi/pulumi-kubernetes/blob/master/.github/workflows/build.yml) has failed. See the list of failures below:

- [2025-08-21T07:07:53.000Z](https://github.com/pulumi/pulumi-kubernetes/actions/runs/17118934533)

### PR DESCRIPTION
**Pull request by blampe**
Pulling in https://github.com/pulumi/ci-mgmt/pull/1664 and the necessary `.ci-mgmt.yml` change.

Fixes #3778

### CODE REVIEW

File: Makefile [hunk 1]
```diff
@@ -214,6 +214,6 @@ sign-goreleaser-exe-%: bin/jsign-6.0.jar
 # - Run make ci-mgmt to apply the change locally.
 #
 ci-mgmt: .ci-mgmt.yaml
-	go run github.com/pulumi/ci-mgmt/provider-ci@master generate
+	go run github.com/pulumi/ci-mgmt/provider-ci@blampe/cloud-url generate
```
Comment (corymhall) [inline Makefile:217]: Is this right?

File: tests/ci-cluster/gke.ts [hunk 2]
```diff
@@ -55,6 +55,7 @@ export class GkeCluster extends pulumi.ComponentResource {
               enabled: true,
               provider: "CALICO",
             },
+            deletionProtection: false,
```
Comment (corymhall) [inline tests/ci-cluster/gke.ts:58]: Curious why this was set previously? I'm assuming there was a reason, otherwise wouldn't the tests always have failed?

**Review by corymhall — APPROVED** [review]

File: Makefile (hunk 1 above)
Comment (blampe) [reply Makefile:217]: It's not, thank you :)
