### PR TITLE
Fix panic when .metadata.labels is mistyped

### LINKED ISSUE #552: Invalid label causes panic in Python SDK
```py3
import pulumi
from pulumi_kubernetes.core.v1 import Pod

pod = Pod(
    "foo",
    metadata={"labels": "foo"},
    spec={"containers": [{"name": "nginx", "image": "nginx"}]}
)
```
causes the following panic:
```
    panic: interface conversion: interface {} is string, not map[string]interface {}
    goroutine 133 [running]:
    github.com/pulumi/pulumi-kubernetes/pkg/metadata.SetLabel(...)
    	/Users/levi/go/src/github.com/pulumi/pulumi-kubernetes/pkg/metadata/labels.go:31
    github.com/pulumi/pulumi-kubernetes/pkg/metadata.SetManagedByLabel(...)
    	/Users/levi/go/src/github.com/pulumi/pulumi-kubernetes/pkg/metadata/labels.go:40
    github.com/pulumi/pulumi-kubernetes/pkg/provider.(*kubeProvider).Check(0xc0004dc600, 0x257c880, 0xc00137e3c0, 0xc001380000, 0xc0004dc600, 0x213bd01, 0xc001380080)
    	/Users/levi/go/src/github.com/pulumi/pulumi-kubernetes/pkg/provider/provider.go:273 +0x16b0
    github.com/pulumi/pulumi-kubernetes/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Check_Handler.func1(0x257c880, 0xc00137e3c0, 0x226f200, 0xc001380000, 0x228e6a0, 0x340dcf8, 0x257c880, 0xc00137e3c0)
    	/Users/levi/go/src/github.com/pulumi/pulumi-kubernetes/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1303 +0x86
    github.com/pulumi/pulumi-kubernetes/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x257c880, 0xc00137e000, 0x226f200, 0xc001380000, 0xc001378020, 0xc001378040, 0x0, 0x0, 0x253dc20, 0xc0004e5d60)
    	/Users/levi/go/src/github.com/pulumi/pulumi-kubernetes/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go:61 +0x360
    github.com/pulumi/pulumi-kubernetes/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Check_Handler(0x22900e0, 0xc0004dc600, 0x257c880, 0xc00137e000, 0xc00137c000, 0xc00044d180, 0x257c880, 0xc00137e000, 0xc00137a000, 0xc8)
    	/Users/levi/go/src/github.com/pulumi/pulumi-kubernetes/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1305 +0x158
    github.com/pulumi/pulumi-kubernetes/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004cf500, 0x2597b40, 0xc0004b2300, 0xc000012100, 0xc000137f50, 0x33dec60, 0x0, 0x0, 0x0)
    	/Users/levi/go/src/github.com/pulumi/pulumi-kubernetes/vendor/google.golang.org/grpc/server.go:972 +0x470
    github.com/pulumi/pulumi-kubernetes/vendor/google.golang.org/grpc.(*Server).handleStream(0xc0004cf500, 0x2597b40, 0xc0004b2300, 0xc000012100, 0x0)
    	/Users/levi/go/src/github.com/pulumi/pulumi-kubernetes/vendor/google.golang.org/grpc/server.go:1252 +0xda6
    github.com/pulumi/pulumi-kubernetes/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0000ee090, 0xc0004cf500, 0x2597b40, 0xc0004b2300, 0xc000012100)
    	/Users/levi/go/src/github.com/pulumi/pulumi-kubernetes/vendor/google.golang.org/grpc/server.go:691 +0x9f
    created by github.com/pulumi/pulumi-kubernetes/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
    	/Users/levi/go/src/github.com/pulumi/pulumi-kubernetes/vendor/google.golang.org/grpc/server.go:689 +0xa1
```

Labels should be a dict rather than a string (e.g. `"labels": {"foo": "true"}`, not `"labels": "foo"`), but this error should be caught before it causes a panic in the provider.

### PR DESCRIPTION
**Pull request by hausdorff**
Fixes #552.

### CODE REVIEW

File: pkg/metadata/labels.go [hunk 1]
```diff
@@ -67,9 +85,12 @@ func GetLabel(obj *unstructured.Unstructured, key string) interface{} {
 	return labelsRaw.(map[string]interface{})[key]
 }
 
-// SetManagedByLabel sets the `app.kubernetes.io/managed-by` label to `pulumi`.
-func SetManagedByLabel(obj *unstructured.Unstructured) {
-	SetLabel(obj, managedByLabel, "pulumi")
+// TrySetManagedByLabel sets the . TrySetLabel attempts to set the `app.kubernetes.io/managed-by`
```
Comment (lblackstone) [inline pkg/metadata/labels.go]:
```suggestion
// TrySetManagedByLabel attempts to set the `app.kubernetes.io/managed-by`
```

File: pkg/provider/provider.go [hunk 2]
```diff
@@ -403,13 +403,21 @@ func (k *kubeProvider) Check(ctx context.Context, req *pulumirpc.CheckRequest) (
 		// a resource that was created out-of-band. In this case, we do not add the `managed-by` label here, as doing
 		// so would result in a persistent failure to import due to a diff that the user cannot correct.
 		if metadata.HasManagedByLabel(oldInputs) {
-			metadata.SetManagedByLabel(newInputs)
+			_, err = metadata.TrySetManagedByLabel(newInputs)
```
Comment (lblackstone) [inline pkg/provider/provider.go]: Why do you need `succeeded` if you ignore it on all usages?

Comment (hausdorff) [reply pkg/provider/provider.go]: It makes it obvious that it _can_ fail.
