### PR TITLE
Fallback to JSON merge if strategic merge fails

### LINKED ISSUE #568: cert-manager update failed from 0.7.0 to 0.7.2
I've encountered an issue updating cert-manager from 0.7.0 to 0.7.2.  I've found no references to others having this problem, and there is nothing of that nature in the cert-manager issues.

The release url I actually used is not versioned to the patch level for semver, so the below is a reproduction of code using commits/raw from those release commits

## common code
```ts
// Install the CustomResourceDefinitions and cert-manager itself
const installCertManager = (url: string) => {
    const certManager = new k8s.yaml.ConfigFile(url,
      undefined,
      { parent: this },
    )
}
```

## initial install 0.7.0

```ts
installCertManager('https://raw.githubusercontent.com/jetstack/cert-manager/208009151b40a0f82e2f27df7e639996b1529868/deploy/manifests/cert-manager.yaml')
```

```
pulumi up -y
```

Success.

## update to 0.7.2

```ts
installCertManager('https://github.com/jetstack/cert-manager/raw/3180966b87ec604fd05da587303cb6ea575a43f1/deploy/manifests/cert-manager.yaml')
```

```
pulumi up -y

                                                                                                                  
        └─ kubernetes:yaml:ConfigFile                                                 https://raw.githubusercontent.com/jetstack/cert-manager/release-0.7/deploy/manifests/cert-manager.yammmml                     
 ~         ├─ kubernetes:core:ServiceAccount                                          cert-manager/cert-manager-cainjector                                                                       updated            
 ~         ├─ kubernetes:core:ServiceAccount                                          cert-manager/cert-manager                                                                                  updated            
 ~         ├─ kubernetes:rbac.authorization.k8s.io:ClusterRole                        cert-manager-webhook:webhook-requester                                                                     updated            
 ~         ├─ kubernetes:core:ServiceAccount                                          cert-manager/cert-manager-webhook                                                                          updated            
 ~         ├─ kubernetes:certmanager.k8s.io:Issuer                                    cert-manager/cert-manager-webhook-selfsign                                                                 updated            
 ~         ├─ kubernetes:apiregistration:APIService                                   v1beta1.admission.certmanager.k8s.io                                                                       updated            
 ~         ├─ kubernetes:rbac.authorization.k8s.io:ClusterRole                        cert-manager-view                                                                                          updated            
 ~         ├─ kubernetes:rbac.authorization.k8s.io:ClusterRole                        cert-manager-edit                                                                                          updated            
 ~         ├─ kubernetes:certmanager.k8s.io:Certificate                               cert-manager/cert-manager-webhook-webhook-tls                                                              updated            
 ~         ├─ kubernetes:certmanager.k8s.io:Issuer                                    cert-manager/cert-manager-webhook-ca                                                                       updated            
 ~         ├─ kubernetes:rbac.authorization.k8s.io:ClusterRole                        cert-manager                                                                                               updated            
 ~         ├─ kubernetes:core:Service                                                 cert-manager/cert-manager-webhook                                                                          updated            
 ~         ├─ kubernetes:rbac.authorization.k8s.io:ClusterRole                        cert-manager-cainjector                                                                                    updated            
 ~         ├─ kubernetes:apps:Deployment                                              cert-manager/cert-manager                                                                                  updated            
 ~         ├─ kubernetes:apps:Deployment                                              cert-manager/cert-manager-webhook                                                                          updated            
 ~         ├─ kubernetes:rbac.authorization.k8s.io:ClusterRoleBinding                 cert-manager                                                                                               updated            
 ~         ├─ kubernetes:certmanager.k8s.io:Certificate                               cert-manager/cert-manager-webhook-ca                                                                       updated            
 ~         ├─ kubernetes:admissionregistration.k8s.io:ValidatingWebhookConfiguration  cert-manager-webhook                                                                                       updated            
 ~         ├─ kubernetes:rbac.authorization.k8s.io:ClusterRoleBinding                 cert-manager-cainjector                                                                                    updated            
 ~         ├─ kubernetes:apps:Deployment                                              cert-manager/cert-manager-cainjector                                                                       updated            
 ~         ├─ kubernetes:rbac.authorization.k8s.io:ClusterRoleBinding                 cert-manager-webhook:auth-delegator                                                                        updated            
 ~         ├─ kubernetes:rbac.authorization.k8s.io:RoleBinding                        kube-system/cert-manager-webhook:webhook-authentication-reader                                             updated            
 ~         ├─ kubernetes:apiextensions.k8s.io:CustomResourceDefinition                certificates.certmanager.k8s.io                                                                            **updating failed**
 ~         ├─ kubernetes:apiextensions.k8s.io:CustomResourceDefinition                issuers.certmanager.k8s.io                                                                                 **updating failed**
 ~         └─ kubernetes:apiextensions.k8s.io:CustomResourceDefinition                clusterissuers.certmanager.k8s.io                                                                          **updating failed**
 
Diagnostics:
  kubernetes:apiextensions.k8s.io:CustomResourceDefinition (certificates.certmanager.k8s.io):
    error: Plan apply failed: 1 error occurred:
        * expected kind, but got map
 
  kubernetes:apiextensions.k8s.io:CustomResourceDefinition (clusterissuers.certmanager.k8s.io):
    error: Plan apply failed: 1 error occurred:
        * expected kind, but got map
 
  kubernetes:apiextensions.k8s.io:CustomResourceDefinition (issuers.certmanager.k8s.io):
    error: Plan apply failed: 1 error occurred:
        * expected kind, but got map
 
```

Failure

I am not sure where to look.

### PR DESCRIPTION
**Pull request by lblackstone**
Fixes #568

### CODE REVIEW

File: pkg/openapi/openapi.go [hunk 1]
```diff
@@ -106,7 +106,11 @@ func PatchForResourceUpdate(client discovery.CachedDiscoveryInterface, lastSubmi
 	if resSchema := resources.LookupResource(gvk); resSchema != nil {
 		glog.V(1).Infof("Attempting to update '%s' '%s/%s' with strategic merge",
 			gvk.String(), lastSubmitted.GetNamespace(), lastSubmitted.GetName())
-		return strategicMergePatch(gvk, resSchema, lastSubmittedJSON, currentSubmittedJSON, liveOldJSON)
+		patch, patchType, lookupPatchMeta, err := strategicMergePatch(
+			gvk, resSchema, lastSubmittedJSON, currentSubmittedJSON, liveOldJSON)
+		if err == nil {
+			return patch, patchType, lookupPatchMeta, err
```
Comment (metral) [inline pkg/openapi/openapi.go]: Since we already eval `if err == nil` is there a need to return it?
