### PR TITLE
Bugfix for ambiguous kinds

### LINKED ISSUE #2143: Custom resource creation: failed to determine if the following GVK is namespaced
### What happened?

I have the AWX operator (https://github.com/ansible/awx-operator) running on my k8s cluster. When I try to create a custom resource of kind awx, Pulumi fails complaining `resource awx/my-awx-3a77c8ca was not successfully created by the Kubernetes API server : failed to determine if the following GVK is namespaced: awx.ansible.com/v1beta1, Kind=awx`. 

### Steps to reproduce

Install the AWX operator, create an awx resource like this:

```python
awx_deployment = k8s.apiextensions.CustomResource(
    "my-awx",
    kind="awx",
    api_version="awx.ansible.com/v1beta1",
    metadata=k8s.meta.v1.ObjectMetaArgs(
        namespace="awx"
    )
)
```

### Expected Behavior

An AWX resource should be created in the cluster

### Actual Behavior

resource awx/my-awx-3a77c8ca was not successfully created by the Kubernetes API server : failed to determine if the following GVK is namespaced: awx.ansible.com/v1beta1, Kind=awx

### Output of `pulumi about`

I am using the github runner of Pulumi

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### LINKED ISSUE #2865: Deploying a Crossplane provider-sql PostgreSQL Role fails with "the server could not find the requested resource"
### What happened?

Trying to deploy a [PostgreSQL Role](https://github.com/crossplane-contrib/provider-sql/tree/master/examples/postgresql) with `ConfigGroup` fails with:

```
  kubernetes:postgresql.sql.crossplane.io/v1alpha1:Role (postgresql/testrole):
    error: Preview failed: resource "urn:pulumi:dev::keycloak-provisioning::kubernetes:core/v1:Namespace$kubernetes:yaml:ConfigGroup$kubernetes:postgresql.sql.crossplane.io/v1alpha1:Role::postgresql/testrole" was not successfully created by the Kubernetes API server : the server could not find the requested resource
```

The same problem happens with `ConfigFile` as well.

Whereas deploying a `Database` from the same Crossplane provider works just fine.

### Example

```ts
const pgSqlRole = new kube.yaml.ConfigGroup("keycloak-postgresql-role", {
        yaml: `
            apiVersion: postgresql.sql.crossplane.io/v1alpha1
            kind: Role
            metadata:
                name: testrole
                namespace: postgresql
            spec:
                providerConfigRef:
                    name: in-cluster-postgresql
                forProvider:
                    privileges:
                        createDb: false
                        login: true
                writeConnectionSecretToRef:
                    name: test-secret
                    namespace: postgresql
        `
    }, {provider: kubeProvider, parent: namespace})
```

### Output of `pulumi about`

```
CLI
Version      3.109.0
Go Version   go1.22.1
Go Compiler  gc

Plugins
NAME        VERSION
kubernetes  4.9.0
nodejs      unknown

Host
OS       darwin
Version  14.3.1
Arch     arm64

This project is written in nodejs: executable='/Users/pradore/.asdf/shims/node' version='v21.6.2'

Current Stack: organization/keycloak-provisioning/dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend
Name           Renanns-MacBook-Pro-10.local
URL            file://./state
User           pradore
Organizations
Token type     personal

Dependencies:
NAME                VERSION
@pulumi/kubernetes  4.9.0
@pulumi/pulumi      3.109.0
@types/node         18.19.22
ts-dedent           2.2.0

Pulumi locates its logs in /var/folders/cd/xn0tnx691gs84m7m7rl41rxm0000gn/T/ by default
```

### Additional context

Trying to use `ConfigGroup` because I can't generate the typescript definitions due to https://github.com/pulumi/crd2pulumi/issues/126.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by EronWright**
### Proposed changes

This PR fixes a couple of related problems with "ambiguous kinds":
1. For kinds with clashing names (e.g. `Role`), be sure to check the apiversion before using built-in information or dynamic discovery.
2. For kinds with casing problems, don't mask the problem; show the API server error.

Note that kubectl has the following behavior w.r.t (2):

```yaml
apiVersion: awx.ansible.com/v1beta1
kind: awx
metadata:
  name: my-awx
  namespace: awx
```

```
❯ kubectl apply -f manifest.yaml --server-side=false
The awx "my-awx" is invalid: kind: Invalid value: "awx": must be AWX
❯ kubectl apply -f manifest.yaml --server-side=true
Error from server (BadRequest): invalid object type: awx.ansible.com/v1beta1, Kind=awx
```

An explanation of the technical approach: the `kinds.Kind` type is used in the codebase to represent a well-known kind, i.e. known at code generation time. To prepare this PR, I audited the locations where `Kind` is used, and ensured that it wasn't being used for arbitrary kinds.  Where necessary, the use of `Kind` was conditioned on the `apiVersion` being one of the well-known values.

### Related issues (optional)

Closes #2865
Closes #2143

### CODE REVIEW

File: provider/pkg/clients/clients.go [hunk 1]
```diff
@@ -93,12 +94,7 @@ func (dcs *DynamicClientSet) ResourceClient(gvk schema.GroupVersionKind, namespa
 	}
 
 	// For namespaced Kinds, create a namespaced client. If no namespace is provided, use the "default" namespace.
-	namespaced, err := IsNamespacedKind(gvk, dcs)
-	if err != nil {
-		return nil, err
-	}
-
-	if namespaced {
```
Comment (EronWright) [inline provider/pkg/clients/clients.go:101]: The mapper returns the requisite scope information, the call to `IsNamespaceKind` is redundant.

File: provider/pkg/kinds/deprecated.go [hunk 2]
```diff
@@ -261,11 +261,6 @@ func ExistsInVersion(gvk *schema.GroupVersionKind, version *cluster.ServerVersio
 func RemovedInVersion(gvk schema.GroupVersionKind) *cluster.ServerVersion {
 	gv, k := groupVersion(gvk.GroupVersion().String()), Kind(gvk.Kind)
 
-	switch k {
-	case PodSecurityPolicy, PodSecurityPolicyList:
-		return &v125
-	}
-
```
Comment (EronWright) [inline provider/pkg/kinds/deprecated.go:268]: This code wasn't considering the GroupVersion, and was actually returning the wrong result for `extensions/v1beta1:PodSecurityPolicy` (which was removed in v1.16).

File: provider/pkg/clients/clients.go [hunk 3]
```diff
@@ -164,23 +166,25 @@ func (dcs *DynamicClientSet) searchKindInGVResources(gvResources *v1.APIResource
 // IsNamespacedKind checks if a given GVK is namespace-scoped. Known GVKs are compared against a static lookup table.
 // For GVKs not in the table, attempt to look up the GVK from the API server. If the GVK cannot be found, a
 // NoNamespaceInfoErr is returned.
-func IsNamespacedKind(gvk schema.GroupVersionKind, clientSet *DynamicClientSet) (bool, error) {
+func IsNamespacedKind(gvk schema.GroupVersionKind, disco discovery.DiscoveryInterface) (bool, error) {
```
Comment (EronWright) [inline provider/pkg/clients/clients.go:169]: Rationale: changing the function signature to make it more easily testable (using the fake disco client).

File: provider/pkg/clients/clients.go [hunk 4]
```diff
@@ -164,23 +166,25 @@ func (dcs *DynamicClientSet) searchKindInGVResources(gvResources *v1.APIResource
...
 	gv := gvk.GroupVersion().String()
 	if strings.Contains(gv, "core/v1") {
 		gv = "v1"
 	}
 
-	kind := strings.TrimSuffix(gvk.Kind, "Patch") // Check using the underlying kind for Patch resources
-	if known, namespaced := kinds.Kind(kind).Namespaced(); known {
-		return namespaced, nil
+	if kinds.KnownGroupVersions.Has(gvk.GroupVersion().String()) {
+		kind := strings.TrimSuffix(gvk.Kind, "Patch") // Check using the underlying kind for Patch resources
```
Comment (EronWright) [inline provider/pkg/clients/clients.go:176]: I believe it unnecessary to trim the `Patch` suffix, but is also harmless because its applied only to the well-known kinds. cc @lblackstone

**Review by lblackstone — COMMENTED** [review]
Looks good to me. I'll defer to @rquitales for approval since it's been a long time since I've thought about this code.

**Review by rquitales — APPROVED** [review]
