### PR TITLE
Handle auto-named namespaces for server-side diff

### LINKED ISSUE #1632: Server-side diff fails if the namespace is auto-named
The preview fails for the following program:

```ts
const ns = new k8s.core.v1.Namespace("test");
const provider = new k8s.Provider("bar", {enableDryRun: true, namespace: ns.metadata.name});

const appLabels = { app: "nginx" };
const deployment = new k8s.apps.v1.Deployment("nginx", {
    metadata: { name: "foo"},
    spec: {
        selector: { matchLabels: appLabels },
        replicas: 1,
        template: {
            metadata: { labels: appLabels },
            spec: {
                containers: [{ name: "nginx", image: "nginx:1.14"}],
            },
        },
    }
}, {provider: provider});
```

```
     Type                              Name                 Plan       Info
 +   pulumi:pulumi:Stack               pulumi-k8s-test-dev  create     1 error
 +   ├─ kubernetes:core/v1:Namespace   test                 create
 +   ├─ pulumi:providers:kubernetes    bar                  create
 +   └─ kubernetes:apps/v1:Deployment  nginx                create     1 error

Diagnostics:
  pulumi:pulumi:Stack (pulumi-k8s-test-dev):
    error: preview failed

  kubernetes:apps/v1:Deployment (nginx):
    error: Preview failed: resource test-ld0g00tq/foo was not successfully created by the Kubernetes API server : namespaces "test-ld0g00tq" not found
```

The diff logic probably isn't accounting for the case where the namespace doesn't exist yet.

### PR DESCRIPTION
**Pull request by lblackstone**
### Proposed changes
This fixes a bug with server-side diff support where auto-named
namespaces would cause resources using that namespace to
fail during preview. This was caused by configuring the k8s client
to run a server-side preview on a namespace that didn't yet exist.

### Related issues (optional)
Fix #1632

### CODE REVIEW

File: provider/pkg/provider/provider.go [hunk 1]
```diff
@@ -1528,9 +1528,19 @@ func (k *kubeProvider) Create(
 	}
 	initialized, awaitErr := await.Creation(config)
 	if awaitErr != nil {
-		if req.GetPreview() && k.isDryRunDisabledError(err) {
-			logger.V(9).Infof("could not preview Create(%v): %v", urn, err)
-			return &pulumirpc.CreateResponse{Id: "", Properties: req.GetProperties()}, nil
+		if req.GetPreview() {
+			failedPreview := func() bool {
```
Comment (mikhailshilkov) [inline provider/pkg/provider/provider.go:1532]: What is the benefit of declaring this as a function vs. having a variable defaulted to false and set to true inside the if body?

File: provider/pkg/await/error.go [hunk 2]
```diff
@@ -38,6 +45,22 @@ func (ce *cancellationError) Object() *unstructured.Unstructured {
 	return ce.object
 }
 
+// namespaceError represents an operation that failed because the namespace didn't exist.
+type namespaceError struct {
+	object *unstructured.Unstructured
+}
+
+var _ error = (*namespaceError)(nil)
+var _ PreviewError = (*namespaceError)(nil)
```
Comment (mikhailshilkov) [inline provider/pkg/await/error.go:54]: I'm not familiar with this approach - what does it do? Is it to ensure that those types implement the contract correctly?

File: provider/pkg/provider/provider.go [hunk 3]
```diff
@@ -1528,9 +1528,19 @@ func (k *kubeProvider) Create(
...
+				_, isPreviewErr := awaitErr.(await.PreviewError)
```
Comment (mikhailshilkov) [inline provider/pkg/provider/provider.go:1533]: Could you please explain how `&namespaceError{c.Inputs}` becomes `PreviewError`?

File: provider/pkg/await/error.go (hunk 2 above)
Comment (lblackstone) [reply provider/pkg/await/error.go:54]: Yes, this would cause a compile-time error if the type didn't implement the interface.

File: provider/pkg/provider/provider.go (hunk 3 above)
Comment (mikhailshilkov) [reply provider/pkg/provider/provider.go:1533]: I think I was a bit tired on that day. I understand it now.

File: provider/pkg/provider/provider.go (hunk 1 above)
Comment (lblackstone) [reply provider/pkg/provider/provider.go:1532]: That would work too. I didn't think much about it, and am happy to swap approaches if that would be clearer.

File: provider/pkg/provider/provider.go (hunk 3 above)
Comment (lblackstone) [reply provider/pkg/provider/provider.go:1533]: `PreviewError` is an interface, and `namespaceError` implements that interface by defining the `Object` pointer method. I'm not sure this approach is the simplest option, but I'm copying the existing approach taken by this provider.

**Review by mikhailshilkov — APPROVED** [review]
LGTM
