### PR TITLE
Correctly merge provided opts for k8s resources

### LINKED ISSUE #849: Bugs and crashes from resource auto-aliasing.
The new auto-aliasing feature has caused issues with all stacks that contain K8S resources.  Usually resulting in an error like
```
panic: fatal: An assertion has failed: Two resources ('urn:pulumi:mirror::mirror::kubernetes:apps/v1:Deployment::traffic-mirror' and 'urn:pulumi:mirror::mirror::kubernetes:autoscaling/v2beta2:HorizontalPodAutoscaler::traffic-mirror') aliased to the same: 'urn:pulumi:mirror::mirror::kubernetes:apps/v1:Deployment::traffic-mirror'
```
More info in slack thread: https://pulumi-community.slack.com/archives/C84L4E3N1/p1570297147325000

I am also able to repro what seems to be the same issue with this simple example:
https://gist.github.com/timmyers/adc57e4dca7dc7a3c14a310d5f4ce6a6

The program consists of a namespace and a deployment.  I have those both applied successfully, pulumi up shows no diff.  Then I uncomment the service object and try to  pulumi up again.
The first run crashed, the second one gives a very odd unexpected diff.

Running `pulumi  up` over and over seems to randomly either crash, or give the weird diff output, some sort of race condition?

Reverting to `@pulumi/kubernetes:1.1.0` resolves all issues.

### PR DESCRIPTION
**Pull request by lblackstone**
### Proposed changes
~It seems like the construct we were using in case of empty opts was not working properly for the auto-aliases. This change fixes the linked issue, but I don't quite understand what the problem was.~

We were not merging user-provided `opts` properly in k8s resources. The bug reported in #849 was caused by mutating the provided `opts` object in multiple resources, which resulted in every resource being aliased to every other resource type sharing that object.

This also fixes the same issue for `additionalSecretOutputs`.

### Related issues (optional)

Fixes #849

### CODE REVIEW

File: pkg/gen/nodejs-templates/kind.ts.mustache [hunk 1]
```diff
@@ -85,7 +85,6 @@ import { getVersion } from "../../version";
           {{#Aliases}}
               { parent: opts.parent, type: "{{.}}", name: name },
           {{/Aliases}}
-              ...((opts && opts.aliases) || []),
```
Comment (pgavlin) [inline pkg/gen/nodejs-templates/kind.ts.mustache]: It looks like this will cause us to drop any user-specified aliases. I don't think we want that. Did you try changing `((opts && opts.alaises) || [])` to `...(opts.aliases || [])`?

Comment (lblackstone) [reply pkg/gen/nodejs-templates/kind.ts.mustache]:
```        opts.aliases = [
            { parent: opts.parent, type: "kubernetes:apps/v1:Deployment", name: name },
            { parent: opts.parent, type: "kubernetes:apps/v1beta1:Deployment", name: name },
            { parent: opts.parent, type: "kubernetes:apps/v1beta2:Deployment", name: name },
            { parent: opts.parent, type: "kubernetes:extensions/v1beta1:Deployment", name: name },
            ...(opts.aliases || []),
        ];
```
still causes a panic.

Comment (pgavlin) [reply pkg/gen/nodejs-templates/kind.ts.mustache]: Ah, I'll bet know what the issue is. We're mutating an object that is passed in by the caller. We shouldn't do that. In the case of the original bug, I think we're adding aliases for multiple resources to the same `opts` dictionary.

Comment (lblackstone) [reply pkg/gen/nodejs-templates/kind.ts.mustache]: Yep, you're right. I've updated the PR to fix. Looks like we were already handling this properly in the Python SDK.

**Comment by lblackstone** [comment]
@pgavlin @CyrusNajmabadi Can you verify that I'm merging the `opts` properly now? Relevant part of the PR is https://github.com/pulumi/pulumi-kubernetes/pull/850/files#diff-9ccac45941821640b7c297dea985a016 (`kind.ts.mustache`) -- the rest is generated from that.

File: pkg/gen/nodejs-templates/kind.ts.mustache [hunk 2]
```diff
@@ -73,21 +73,19 @@ import { getVersion } from "../../version";
...
+                {{#AdditionalSecretOutputs}}
+                "{{.}}",
+                {{/AdditionalSecretOutputs}}
+            ],
+            aliases: [
+            {{#Aliases}}
+                { parent: opts.parent, type: "{{.}}", name: name },
+            {{/Aliases}}
+            ]
+        })
```
Comment (pgavlin) [inline pkg/gen/nodejs-templates/kind.ts.mustache]: Nit: missing a semicolon here.

File: sdk/nodejs/admissionregistration/v1/MutatingWebhookConfiguration.ts [hunk 3]
```diff
@@ -94,15 +94,13 @@ import { getVersion } from "../../version";
...
-
-          super(MutatingWebhookConfiguration.__pulumiType, name, props, opts);
+        let _opts = pulumi.mergeOptions(opts, {
+            additionalSecretOutputs: [
+            ],
+            aliases: [
+            ]
+        })
+
+          super(MutatingWebhookConfiguration.__pulumiType, name, props, _opts);
```
Comment (lukehoban) [inline sdk/nodejs/admissionregistration/v1/MutatingWebhookConfiguration.ts]: Indentation looks off above.

Also, our lint rules should disallow use of `let` and require `const` here.

Comment (lukehoban) [reply sdk/nodejs/admissionregistration/v1/MutatingWebhookConfiguration.ts]: Also - it's pretty ugly to emit all this merging and empty lists and spread across lines.  I get that this is generated code - but it is code users will see frequently on Go To Definition - are there reasonable ways to clean this all up a bit?

Comment (lukehoban) [reply sdk/nodejs/admissionregistration/v1/MutatingWebhookConfiguration.ts]: Specifically I'm talking about things like this which I see all over the generated output now:

```
 let _opts = pulumi.mergeOptions(opts, {
            additionalSecretOutputs: [
            ],
            aliases: [
            ]
        })
```

Comment (lblackstone) [reply sdk/nodejs/admissionregistration/v1/MutatingWebhookConfiguration.ts]: > Indentation looks off above.
> 
> Also, our lint rules should disallow use of `let` and require `const` here.

Fixed

> Also - it's pretty ugly to emit all this merging and empty lists and spread across lines. I get that this is generated code - but it is code users will see frequently on Go To Definition - are there reasonable ways to clean this all up a bit?

There may be a way to do so with mustache templates, but I couldn't figure out how when I added the auto-alias feature.

**Comment by lblackstone** [comment]
@lukehoban Since your comments were on style/formatting, I'm going to merge now in the interest of making the fix available to test. I can follow up for any further comments.

File: sdk/nodejs/admissionregistration/v1/MutatingWebhookConfiguration.ts [hunk 4]
```diff
@@ -94,15 +94,13 @@ import { getVersion } from "../../version";
...
-          opts.aliases = [
-              ...((opts && opts.aliases) || []),
-          ];
-
-          super(MutatingWebhookConfiguration.__pulumiType, name, props, opts);
+          const _opts = pulumi.mergeOptions(opts, {
+              additionalSecretOutputs: [
+              ],
+              aliases: [
+              ]
```
Comment (CyrusNajmabadi) [inline sdk/nodejs/admissionregistration/v1/MutatingWebhookConfiguration.ts]: this is super unfortunate.
