### PR TITLE
Fix panic condition in Pod await logic

### LINKED ISSUE #994: panic: interface conversion: runtime.Object is nil, not *unstructured.Unstructured
Pulumi panicked when a `transport is closing` error occurred during an `up`. 

#### Output
```
k8s-ts-nginx % pulumi up
Previewing update (dev):

     Type                                  Name                         Plan
 +   pulumi:pulumi:Stack                   demo-k8s-ts-nginx-dev        create
 +   ├─ kubernetes:helm.sh:Chart           echo-server                  create
 +   │  ├─ kubernetes:core:ServiceAccount  echo-server                  create
 +   │  ├─ kubernetes:core:ConfigMap       echo-server                  create
 +   │  ├─ kubernetes:core:Service         echo-server                  create
 +   │  ├─ kubernetes:core:Pod             echo-server-test-connection  create
 +   │  └─ kubernetes:apps:Deployment      echo-server                  create
 +   ├─ gcp:pubsub:Topic                   gcp-demo                     create
 +   ├─ random:index:RandomPassword        clstokes                     create
 +   ├─ gcp:container:Cluster              clstokes                     create
 +   │  └─ pulumi:providers:kubernetes     clstokes                     create
 +   └─ kubernetes:core:Namespace          test                         create

Resources:
    + 12 to create

Do you want to perform this update? yes
Updating (dev):

     Type                                  Name                         Status                  Info
 +   pulumi:pulumi:Stack                   demo-k8s-ts-nginx-dev        **creating failed**     1 error; 26 messages
 +   ├─ kubernetes:helm.sh:Chart           echo-server                  created
 +   │  ├─ kubernetes:core:ServiceAccount  echo-server                  created
 +   │  ├─ kubernetes:core:ConfigMap       echo-server                  created
 +   │  ├─ kubernetes:core:Pod             echo-server-test-connection  **creating failed**     1 error
 +   │  ├─ kubernetes:core:Service         echo-server                  created
 +   │  └─ kubernetes:apps:Deployment      echo-server                  created
 +   ├─ gcp:pubsub:Topic                   gcp-demo                     created
 +   ├─ random:index:RandomPassword        clstokes                     created
 +   ├─ gcp:container:Cluster              clstokes                     created
 +   │  └─ pulumi:providers:kubernetes     clstokes                     created
 +   └─ kubernetes:core:Namespace          test                         created

Diagnostics:
  kubernetes:core:Pod (echo-server-test-connection):
    error: transport is closing

  pulumi:pulumi:Stack (demo-k8s-ts-nginx-dev):
    panic: interface conversion: runtime.Object is nil, not *unstructured.Unstructured
    goroutine 242 [running]:
    github.com/pulumi/pulumi-kubernetes/pkg/await.(*podInitAwaiter).processPodEvent(0xc001739138, 0x0, 0x0, 0x0, 0x0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/pkg/await/pod.go:200 +0x2db
    github.com/pulumi/pulumi-kubernetes/pkg/await.(*podInitAwaiter).Await(0xc001739138, 0x0, 0x0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/pkg/await/pod.go:165 +0x212
    github.com/pulumi/pulumi-kubernetes/pkg/await.awaitPodInit(0xc00051c080, 0x26dcf60, 0xc0000c8dc0, 0xc00136b980, 0x72, 0xc001720aea, 0x2, 0xc00171f740, 0xc0003eb920, 0xc00000f180, ...)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/pkg/await/pod.go:119 +0xe6
    github.com/pulumi/pulumi-kubernetes/pkg/await.Creation(0x26dcf60, 0xc0000c8dc0, 0xc00051c080, 0xc00136b980, 0x72, 0xc001720aea, 0x2, 0xc0003eb920, 0xc00171f740, 0x269e900, ...)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/pkg/await/await.go:190 +0x661
    github.com/pulumi/pulumi-kubernetes/pkg/provider.(*kubeProvider).Create(0xc0003da0b0, 0x26dd020, 0xc001778ea0, 0xc00171f380, 0xc0003da0b0, 0x2271d01, 0xc00171f480)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/pkg/provider/provider.go:1229 +0x671
    github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Create_Handler.func1(0x26dd020, 0xc001778ea0, 0x2391ee0, 0xc00171f380, 0x23bd400, 0x3301080, 0x26dd020, 0xc001778ea0)
    	/home/travis/gopath/pkg/mod/github.com/pulumi/pulumi@v1.6.1/sdk/proto/go/provider.pb.go:1615 +0x86
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x26dd020, 0xc0017787e0, 0x2391ee0, 0xc00171f380, 0xc001774780, 0xc0017747a0, 0x0, 0x0, 0x269c420, 0xc0002a85d0)
    	/home/travis/gopath/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20171105060200-01f8541d5372/go/otgrpc/server.go:61 +0x36e
    github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Create_Handler(0x23ff960, 0xc0003da0b0, 0x26dd020, 0xc0017787e0, 0xc00176d2c0, 0xc00051c0e0, 0x26dd020, 0xc0017787e0, 0xc00136f080, 0x294)
    	/home/travis/gopath/pkg/mod/github.com/pulumi/pulumi@v1.6.1/sdk/proto/go/provider.pb.go:1617 +0x14b
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc000001980, 0x26f99c0, 0xc000088d80, 0xc00154f600, 0xc0004b6270, 0x32cd290, 0x0, 0x0, 0x0)
    	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.21.1/server.go:998 +0x46a
    google.golang.org/grpc.(*Server).handleStream(0xc000001980, 0x26f99c0, 0xc000088d80, 0xc00154f600, 0x0)
    	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.21.1/server.go:1278 +0xd97
    google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0004680a0, 0xc000001980, 0x26f99c0, 0xc000088d80, 0xc00154f600)
    	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.21.1/server.go:717 +0xbb
    created by google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.21.1/server.go:715 +0xa1

    error: update failed

Resources:
    + 11 created

Duration: 15m53s

Permalink: https://app.pulumi.com/clstokes/demo-k8s-ts-nginx/dev/updates/1
```

### PR DESCRIPTION
**Pull request by lblackstone**
### Proposed changes
For events received by the Pod awaiter, explicitly check that
the event has a non-nil Object to avoid a possible panic.

### Related issues (optional)

Fixes #994

### CODE REVIEW

File: pkg/await/pod.go [hunk 1]
```diff
@@ -197,6 +197,10 @@ func (pia *podInitAwaiter) Read() error {
 }
 
 func (pia *podInitAwaiter) processPodEvent(event watch.Event) {
+	if event.Object == nil {
+		glog.V(3).Infof("received event with nil Object: %#v", event)
```
Comment (pgavlin) [inline pkg/await/pod.go]: Under what circumstances does this occur?

Comment (lblackstone) [reply pkg/await/pod.go]: In the linked issue, it seemed like it was caused by a network interruption.

**Comment by pgavlin** [comment]
From https://github.com/pulumi/pulumi-kubernetes/issues/994#issuecomment-587870457:

> I'm guessing that one of the API's that talks to the K8S cluster returned nil (and possibly an unchecked error)

Did we look for any unchecked errors?

**Comment by lblackstone** [comment]
@pgavlin That event is coming from a watch channel, so there's no error to check.

**Comment by pgavlin** [comment]
> @pgavlin That event is coming from a watch channel, so there's no error to check.

Hm. Is this due to the way we've written it? Seems like we must be dropping an error somewhere... Can you file an issue for followup?

**Comment by lblackstone** [comment]
> Seems like we must be dropping an error somewhere...

I could switch on the event type to check for an `Error` type, but I don't know for sure if it would be set properly. The important thing is the check the type cast rather than panicking; if the event is invalid, we should be able to safely ignore it.
