### PR TITLE
Fix HELM_HOME handling for v3

### LINKED ISSUE #1070: Presence of HELM_HOME environment variable causes Helm v3 command to fail
### Problem description

With the Helm v3 binary, it seems `--home` is no longer a valid flag, so the presence of HELM_HOME environment variable will cause helm fetch commands to fail with an unclear error message, when they previously would work with the Helm v2 binary. This affects users of the Pulumi docker images that previously had Helm v2 but are now shipping with Helm v3 by default (since https://github.com/pulumi/pulumi/pull/4090).

### Errors & Logs

The error looks like this, if the HELM_HOME environment variable exists:
```
2020-04-15T00:15:19.5419814Z Diagnostics:
2020-04-15T00:15:19.5420479Z   pulumi:pulumi:Stack (clusterServices-utils):
2020-04-15T00:15:19.5421018Z     error: Program failed with an unhandled exception:
2020-04-15T00:15:19.5421552Z     error: Traceback (most recent call last):
2020-04-15T00:15:19.5422423Z       File "/usr/bin/pulumi-language-python-exec", line 85, in <module>
2020-04-15T00:15:19.5423018Z         loop.run_until_complete(coro)
2020-04-15T00:15:19.5423601Z       File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
2020-04-15T00:15:19.5424173Z         return future.result()
2020-04-15T00:15:19.5424894Z       File "/usr/local/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 81, in run_in_stack
2020-04-15T00:15:19.5425502Z         await run_pulumi_func(lambda: Stack(func))
2020-04-15T00:15:19.5426252Z       File "/usr/local/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 50, in run_pulumi_func
2020-04-15T00:15:19.5426850Z         await RPC_MANAGER.rpcs.pop()
2020-04-15T00:15:19.5427606Z       File "/usr/local/lib/python3.7/site-packages/pulumi/runtime/rpc_manager.py", line 67, in rpc_wrapper
2020-04-15T00:15:19.5428188Z         result = await rpc
2020-04-15T00:15:19.5428922Z       File "/usr/local/lib/python3.7/site-packages/pulumi/runtime/resource.py", line 440, in do_register_resource_outputs
2020-04-15T00:15:19.5429560Z         serialized_props = await rpc.serialize_properties(outputs, {})
2020-04-15T00:15:19.5430355Z       File "/usr/local/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 68, in serialize_properties
2020-04-15T00:15:19.5431151Z         result = await serialize_property(v, deps, input_transformer)
2020-04-15T00:15:19.5432064Z       File "/usr/local/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 173, in serialize_property
2020-04-15T00:15:19.5433311Z         value = await serialize_property(output.future(), deps, input_transformer)
2020-04-15T00:15:19.5434624Z       File "/usr/local/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 159, in serialize_property
2020-04-15T00:15:19.5435457Z         future_return = await asyncio.ensure_future(awaitable)
2020-04-15T00:15:19.5436506Z       File "/usr/local/lib/python3.7/site-packages/pulumi/output.py", line 114, in get_value
2020-04-15T00:15:19.5437304Z         val = await self._future
2020-04-15T00:15:19.5438266Z       File "/usr/local/lib/python3.7/site-packages/pulumi/output.py", line 155, in run
2020-04-15T00:15:19.5439079Z         value = await self._future
2020-04-15T00:15:19.5440040Z       File "/usr/local/lib/python3.7/site-packages/pulumi/output.py", line 155, in run
2020-04-15T00:15:19.5440820Z         value = await self._future
2020-04-15T00:15:19.5441793Z       File "/usr/local/lib/python3.7/site-packages/pulumi/output.py", line 155, in run
2020-04-15T00:15:19.5442575Z         value = await self._future
2020-04-15T00:15:19.5443271Z       [Previous line repeated 3 more times]
2020-04-15T00:15:19.5444263Z       File "/usr/local/lib/python3.7/site-packages/pulumi/output.py", line 186, in run
2020-04-15T00:15:19.5445064Z         return await transformed.future(with_unknowns=True)
2020-04-15T00:15:19.5446107Z       File "/usr/local/lib/python3.7/site-packages/pulumi/output.py", line 114, in get_value
2020-04-15T00:15:19.5446913Z         val = await self._future
2020-04-15T00:15:19.5447870Z       File "/usr/local/lib/python3.7/site-packages/pulumi/output.py", line 155, in run
2020-04-15T00:15:19.5448673Z         value = await self._future
2020-04-15T00:15:19.5463192Z       File "/usr/local/lib/python3.7/site-packages/pulumi/output.py", line 176, in run
2020-04-15T00:15:19.5464048Z         transformed: Input[U] = func(value)
2020-04-15T00:15:19.5465146Z       File "/usr/local/lib/python3.7/site-packages/pulumi_kubernetes/helm/v2/helm.py", line 325, in _parse_chart
2020-04-15T00:15:19.5466062Z         _fetch(chart_to_fetch, fetch_opts)
2020-04-15T00:15:19.5467156Z       File "/usr/local/lib/python3.7/site-packages/pulumi_kubernetes/helm/v2/helm.py", line 407, in _fetch
2020-04-15T00:15:19.5468148Z         subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True, check=True)
2020-04-15T00:15:19.5469024Z       File "/usr/local/lib/python3.7/subprocess.py", line 512, in run
2020-04-15T00:15:19.5469809Z         output=stdout, stderr=stderr)
2020-04-15T00:15:19.5471305Z     subprocess.CalledProcessError: Command '['helm', 'fetch', 'stable/wordpress', '--untar', '--home', '/root/.helm', '--version', '2.1.3', '--destination', '/tmp/tmp9q63lhrf']' returned non-zero exit status 1.
2020-04-15T00:15:19.5472422Z     error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

### Affected product version(s)

I'm using pulumi 1.14.0 and pulumi_kubernetes 1.6.0 on python SDK, and Pulumi action's latest docker image.

### Reproducing the issue

This script to install a Helm chart modified from https://www.pulumi.com/docs/guides/adopting/from_kubernetes/ to use helm.v3 would reproduce the above.
```
import pulumi
from pulumi_kubernetes.helm.v3 import Chart, ChartOpts

# Deploy the latest version of the stable/wordpress chart.
wordpress = Chart('wpdev', config=ChartOpts(
    repo='stable',
    chart='wordpress',
    version='2.1.3',
))
```

### Suggestions for a fix

It might be helpful to warn or throw a clearer assertion error if HELM_HOME is specified when helm.v3 is being used. Or ignore HELM_HOME altogether and not produce the `--home` argument in the helm.v3 module, so that the fetch is still attempted with the default config/cache paths.

For those who need the ability to specify a different helm home directory, it seems the recommended way to override this path in Helm v3 is to use the following environment variables now (based on https://helm.sh/docs/faq/#xdg-base-directory-support):
```
XDG_CONFIG_HOME=$HOME/.config
XDG_CACHE_HOME=$HOME/.cache
```

I'm not sure the best way to achieve this now in the helm.v3 module in lieu of using the FetchOpts.home param, but it seems like any use of this param right now will fail with Helm v3 in a similar manner to above (due to `--home` not being a valid flag for helm v3).

(FWIW, I filed a related issue to suggest adding these environment variable definitions by default to the Pulumi docker images: https://github.com/pulumi/pulumi/issues/4397)

### PR DESCRIPTION
**Pull request by lblackstone**
### Proposed changes
Helm v3 removed the `--home` parameter, but still supports the `HELM_HOME` env var for backward compatibility. Pass ambient env vars to the `helm` binary so this works properly.

TODO:

- [x] NodeJS
- [x] Python
- [x] C#

### Related issues (optional)
Fix #1070

### CODE REVIEW

File: sdk/dotnet/Helm/ChartBase.cs [hunk 1]
```diff
@@ -111,15 +111,8 @@ protected ChartBase(string releaseName, Union<ChartArgs, LocalChartArgs> args, C
...
-                    var home = Environment.GetEnvironmentVariable("HELM_HOME");
-                    if (home != null)
-                    {
-                        flags.Add("--home");
-                        flags.Add(home);
-                    }
-
-                    var yaml = Utilities.ExecuteCommand("helm", flags.ToArray());
+                    var yaml = Utilities.ExecuteCommand("helm", flags.ToArray(),
+                        (Dictionary<string, string>)Environment.GetEnvironmentVariables());
```
Comment (lblackstone) [inline sdk/dotnet/Helm/ChartBase.cs:115]: @mikhailshilkov CI is failing with the following error:
```
kubernetes:helm.sh:Chart empty1 creating error: Pulumi.ResourceException: Unable to cast object of type 'System.Collections.Hashtable' to type 'System.Collections.Generic.Dictionary`2[System.String,System.String]'
```

I'm guessing this line is at fault, but I'm not really sure how to fix. Any thoughts?

Comment (mikhailshilkov) [reply sdk/dotnet/Helm/ChartBase.cs:115]: Unfortunately, `Environment.GetEnvironmentVariables` is a shitty old method that nobody touched for 15 years, so it returns some ancient types. It won't convert to a generic dictionary OOTB.

We likely want a helper wrapper, e.g. in `Utilities`, something like

```cs
public static IDictionary<string, string> GetEnvironmentVariables()
{
    var result = new Dictionary<string, string>();
    foreach (var variable in Environment.GetEnvironmentVariables())
    {
        if (variable == null) continue;

        var entry = (DictionaryEntry)variable; 
        if (entry.Key is string key && entry.Value is string value)
            result.Add(key, value);
    }
    return result;
}
```

It's s chunk of defensive code, but it's kind of needed to make the compiler happy.

File: sdk/dotnet/Helm/ChartBase.cs [hunk 2]
```diff
@@ -152,9 +145,19 @@ private void Fetch(string chart, ChartFetchArgsUnwrap opts)
                 flags.Add("--untar");
             }
 
-            // Fallback to using the HELM_HOME environment variable if opts.home is not set.
-            if (string.IsNullOrEmpty(opts.Home)) {
-                opts.Home = Environment.GetEnvironmentVariable("HELM_HOME");
+            var env = (Dictionary<string, string>)Environment.GetEnvironmentVariables();
```
Comment (mikhailshilkov) [inline sdk/dotnet/Helm/ChartBase.cs:148]: Please call that helper method that I suggested and remove any casts here.

File: sdk/dotnet/Helm/ChartBase.cs [hunk 3]
```diff
@@ -152,9 +145,19 @@ private void Fetch(string chart, ChartFetchArgsUnwrap opts)
...
+
+            // Helm v3 removed the `--home` flag, so we must use an env var instead.
+            if (!string.IsNullOrEmpty(opts.Home))
+            {
+                if (env.ContainsKey("HELM_HOME"))
```
Comment (mikhailshilkov) [inline sdk/dotnet/Helm/ChartBase.cs:153]: You don't need this `if` here: the assignment style `env["HELM_HOME"] = opts.Home;` should work for both cases.

File: sdk/dotnet/Utilities.cs [hunk 4]
```diff
@@ -39,7 +40,7 @@ public static InvokeOptions WithVersion(this InvokeOptions? options)
             };
         }
 
-        public static string ExecuteCommand(string command, string[] flags)
+        public static string ExecuteCommand(string command, string[] flags, IDictionary<string, string>? env)
```
Comment (mikhailshilkov) [inline sdk/dotnet/Utilities.cs:43]:
```suggestion
        public static string ExecuteCommand(string command, string[] flags, IDictionary<string, string> env)
```

I don't see a great reason to make in nullable here, so let's stick to strict type - and then you can remove the null check below.

File: sdk/nodejs/helm/v2/helm.ts [hunk 5]
```diff
@@ -367,10 +361,9 @@ export function fetch(chart: string, opts?: ResolvedFetchOpts) {
         if (opts.repo !== undefined)        { flags.push(`--repo ${path.quotePath(opts.repo)}`);               }
         if (opts.untardir !== undefined)    { flags.push(`--untardir ${path.quotePath(opts.untardir)}`);       }
         if (opts.username !== undefined)    { flags.push(`--username ${shell.quote([opts.username])}`);  }
-        if (opts.home !== undefined)        { flags.push(`--home ${path.quotePath(opts.home)}`);               }
         if (opts.devel === true)            { flags.push(`--devel`);                                           }
         if (opts.prov === true)             { flags.push(`--prov`);                                            }
         if (opts.verify === true)           { flags.push(`--verify`);                                          }
     }
-    execSync(`helm fetch ${shell.quote([chart])} ${flags.join(" ")}`);
+    execSync(`helm fetch ${shell.quote([chart])} ${flags.join(" ")}`, { env });
```
Comment (mikhailshilkov) [inline sdk/nodejs/helm/v2/helm.ts:368]: Are we sure we want to pass all env variables as opposed to passing `HELM_HOME` specifically? Is there a combination of env variables that would change the behavior of helm between two Pulumi versions, and therefore break somebody?

File: sdk/nodejs/helm/v2/helm.ts [hunk 6]
```diff
@@ -345,14 +340,13 @@ interface ResolvedFetchOpts {
...
+    const env: { [key: string]: string | undefined } = {...process.env};
     if (opts !== undefined) {
         // Untar by default.
         if(opts.untar !== false) { flags.push(`--untar`); }
 
-        // Fallback to using the HELM_HOME environment variable if opts.home is not set.
-        if (!opts.home) {
-            opts.home = process.env.HELM_HOME || undefined;
-        }
+        // Helm v3 removed the `--home` flag, so we must use an env var instead.
```
Comment (mikhailshilkov) [inline sdk/nodejs/helm/v2/helm.ts:348]: Is this new way okay for v2 as well?

File: sdk/nodejs/helm/v2/helm.ts [hunk 7]
```diff
@@ -345,14 +340,13 @@ interface ResolvedFetchOpts {
...
+        if (opts.home) { env['HELM_HOME'] = path.quotePath(opts.home) }
```
Comment (mikhailshilkov) [inline sdk/nodejs/helm/v2/helm.ts:349]: Do we need to quote the env variable?

File: sdk/nodejs/helm/v2/helm.ts (hunk 6 above)
Comment (lblackstone) [reply sdk/nodejs/helm/v2/helm.ts:348]: Yep, `HELM_HOME` works on both versions.

File: sdk/nodejs/helm/v2/helm.ts (hunk 7 above)
Comment (lblackstone) [reply sdk/nodejs/helm/v2/helm.ts:349]: I don't think it would hurt. This should be identical to the existing behavior.

File: sdk/nodejs/helm/v2/helm.ts (hunk 5 above)
Comment (lblackstone) [reply sdk/nodejs/helm/v2/helm.ts:368]: I suppose it's possible. The advantage of passing everything is that it makes it easier for users to configure Helm behavior without requiring us to change code, but maybe it would be better to limit the change here.

**Comment by lblackstone** [comment]
@mikhailshilkov Any idea on this error?
```
[              helm-api-versions ]   kubernetes:helm.sh:Chart (api-versions):
[              helm-api-versions ]     error: Pulumi.ResourceException: Value does not fall within the expected range.
[              helm-api-versions ]        at Pulumi.Kubernetes.Helm.ChartBase.<>c__DisplayClass0_0.<.ctor>b__1(ValueTuple`2 values)
[              helm-api-versions ]        at Pulumi.Output`1.ApplyHelperAsync[U](Task`1 dataTask, Func`2 func)
[              helm-api-versions ]        at Pulumi.Output`1.Pulumi.IOutput.GetDataAsync()
[              helm-api-versions ]        at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop)
[              helm-api-versions ]        at Pulumi.Deployment.SerializeFilteredPropertiesAsync(String label, IDictionary`2 args, Predicate`1 acceptKey)
[              helm-api-versions ]        at Pulumi.Deployment.SerializeAllPropertiesAsync(String label, IDictionary`2 args)
[              helm-api-versions ]        at Pulumi.Deployment.RegisterResourceOutputsAsync(Resource resource, Output`1 outputs)
[              helm-api-versions ]        at Pulumi.Deployment.Runner.WhileRunningAsync()
```

File: provider/pkg/gen/nodejs-templates/helm/v2/helm.ts [hunk 8]
```diff
@@ -205,15 +205,10 @@ export class Chart extends yaml.CollectionComponentResource {
...
-                // Use the HELM_HOME environment variable value if set.
-                const home = process.env.HELM_HOME || undefined;
-                if (home !== undefined) {
-                    cmd += ` --home ${path.quotePath(home)}`;
-                }
-
                 const yamlStream = execSync(
                     cmd,
                     {
+                        env: {...process.env},
```
Comment (lukehoban) [inline provider/pkg/gen/nodejs-templates/helm/v2/helm.ts:211]: Isn't this the default already?

File: sdk/nodejs/helm/v2/helm.ts (hunk 5 above)
Comment (lukehoban) [reply sdk/nodejs/helm/v2/helm.ts:368]: The default for `execSync` was to pass `process.env` down to the subprocess.  So I think we should keep that behaviour by default (and add `HELM_HOME`).

Comment (mikhailshilkov) [reply sdk/nodejs/helm/v2/helm.ts:368]: Indeed! The same applies to .NET, actually, if I read the docs correctly. Therefore, we can simplify the PR and not retrieve/pass env variables, only add `HELM_HOME` if needed.

**Comment by mikhailshilkov** [comment]
@lblackstone 

> Any idea on this error?

Hmm, I suspect we screwed up environment variables related to paths somehows. I think we should revert to not passing all the env variables explicitly and only pass `HELM_HOME` in addition to the ambient defaults - and I think the error will be gone.

File: sdk/nodejs/helm/v2/helm.ts (hunk 5 above)
Comment (lblackstone) [reply sdk/nodejs/helm/v2/helm.ts:368]: @lukehoban [This comment](https://stackoverflow.com/questions/7824789/nodejs-set-environment-variable-for-exec#comment57015051_7825732) indicates that setting `env` only sets the passed values, which is why I copied `process.env` explicitly.

Comment (mikhailshilkov) [reply sdk/nodejs/helm/v2/helm.ts:368]: @lblackstone That makes sense to me. I think we don't need to retrieve/pass them for .NET - just add the extra one.

**Comment by lblackstone** [comment]
> Do we have any way to test this?

I specified the `home` option on a test Chart for each SDK. This should be a no-op if things are working, and fail in current `master` if the helm v3 binary is used.
