### PR TITLE
BREAKING: Change resource naming scheme, fix a small set of bugs

### LINKED ISSUE #146: Presence of CRDs cause deletes to fail

### PR DESCRIPTION
**Pull request by hausdorff**
BREAKING CHANGE: This PR fixes a small set of bugs and changes the way resources are named in the Pulumi Kubernetes provider. Quoting from the relevant commit:

> Use `/` in fully-qualified resource names
>
> Fixes #146.
> 
> Currently we're creating canonical IDs for resources using the `.`
> character. These IDs take the form of `${namespace}.${name}`, or simply
> `${name}` if namespace does not exist.
> 
> We copied this strategy from ksonnet, which in turn copied it from some
> part of kubectl, but this turns out to be a critical flaw, because `.`
> is an allowed character in DNS-1123-compliant names. This means it's
> possible to name your resource `foo.bar`, and if it does not contain a
> namespace, then we'd decide the namespace was `foo`.
> 
> The solution is to move canonical IDs for resources to use `/` to
> delimit namespace, which is much better because `/` is not DNS-1123
> compliant, and therefore no Kubernetes resource can have the slash in
> it.

This change is absolutely necessary, but it will be painful for anyone who (1) has a stack with explicitly-namespaced resources, or (2) uses `.` in the name or namespace of a resource.

Our plan is to:

- Include this in v0.15.2
- Find all users who are affected by the change (we have the appropriate SQL query written)
- Email all of them to let them know what will happen when they upgrade
- In my personal time, I will write a migration tool so they can do something like `pulumi stack export | migrate.sh | pulumi stack import`

### CODE REVIEW

File: Makefile [hunk 1]
```diff
@@ -38,7 +38,7 @@ build:: $(OPENAPI_FILE)
 		yarn install && \
 		yarn run tsc
 	cp README.md LICENSE ${PACKDIR}/nodejs/package.json ${PACKDIR}/nodejs/yarn.lock ${PACKDIR}/nodejs/bin/
-	sed -i 's/$${VERSION}/$(VERSION)/g' ${PACKDIR}/nodejs/bin/package.json
+	sed -i.bak 's/$${VERSION}/$(VERSION)/g' ${PACKDIR}/nodejs/bin/package.json
```
Comment (lukehoban) [inline Makefile]: ?

File: pkg/await/apps_deployment.go [hunk 2]
```diff
@@ -455,8 +455,32 @@ func (dia *deploymentInitAwaiter) checkReplicaSetStatus() {
 	glog.V(3).Infof("ReplicaSet '%s' requests '%v' replicas, but has '%v' ready",
 		rs.GetName(), specReplicas, readyReplicas)
 
-	dia.updatedReplicaSetReady = lastGeneration != dia.currentGeneration && udpatedReplicaSetCreated &&
-		readyReplicasExists && readyReplicas >= int64(specReplicas)
+	if dia.changeTriggeredRollout() {
+		dia.updatedReplicaSetReady = lastGeneration != dia.currentGeneration && udpatedReplicaSetCreated &&
+			readyReplicasExists && readyReplicas >= int64(specReplicas)
+	} else {
+		dia.updatedReplicaSetReady = lastGeneration == dia.currentGeneration && udpatedReplicaSetCreated &&
```
Comment (lukehoban) [inline pkg/await/apps_deployment.go]: Do we need to enforce that they are equal on this path?  In general, how should we think about being conservative about blocking success?  Seems we should aim to have as few things be capable of blocking success as possible, and be sure they are rock solid signals of a problem if they do?

File: Makefile (hunk 1 above)
Comment (hausdorff) [reply Makefile]: The title of this commit is:

> `make install` should be macOS-compatible

The macOS implementation of the `-i` flag requires the `.bak` suffix to work at all.

File: pkg/await/apps_deployment.go (hunk 2 above)
Comment (hausdorff) [reply pkg/await/apps_deployment.go]: Ok, we can do that.

File: pack/nodejs/helm.ts [hunk 3]
```diff
@@ -65,6 +66,9 @@ export namespace v2 {
                     yaml: [yamlStream],
                     transformations: config.transformations || [],
                 }, { parent: this });
+            } catch (e) {
+                console.error(e.toString());
+                process.exit(1);
```
Comment (pgavlin) [inline pack/nodejs/helm.ts]: This is pretty surprising. An uncaught exception should already tear the process down. Is this not happening?

Comment (pgavlin) [reply pack/nodejs/helm.ts]: Let's change this to throw a `pulumi.RunError`.

**Comment by hausdorff** [comment]
Ok, so to follow up, I did manually migrate all stacks deploying Kubernetes that are affected, and emailed them their new stacks. So anyone who is interested has a smooth transition.
