### PR TITLE
Helm Release: fix username fetch option

### LINKED ISSUE #1757: [Helm Release] Not working with private helm repos
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

Copied from https://github.com/pulumi/pulumi-kubernetes/issues/1735#issuecomment-933611354
## Issue details
I tried using the new helm.Release but that does not seem to work with a private helm repo.
```
argo_args = helm.ReleaseArgs(
    chart="argocd",
    skip_await=False,
    namespace='argocd',
    values=values['argocd'],
    repository_opts=helm.RepositoryOptsArgs(
        repo=config.require('helm_repo'),
        username=config.require('helm_user'),
        password=config.require('helm_password')
    )
)
argo_release = helm.Release("argocd", args=argo_args)
```
This gives me the following error:

```
error: failed to pull chart: looks like "https://genuitysci.jfrog.io/artifactory/gorkubbe" is not a valid chart repository or cannot be reached: failed to fetch https://genuitysci.jfrog.io/artifactory/gorkubbe/index.yaml : 401 Unauthorized
This is using the same credentials that work with helm.Chart so they are not the problem
```

### PR DESCRIPTION
**Pull request by lblackstone**
### Proposed changes
The username was incorrectly being set to the password value,
which caused authentication to fail for private Helm repos.

### Related issues (optional)
Fix #1757

### CODE REVIEW

**Review by danielrbradley — APPROVED** [review]

File: provider/pkg/provider/helm_release.go [hunk 1]
```diff
@@ -985,7 +985,7 @@ func computeResourceNames(r *Release) (map[string][]string, error) {
 			Keyring:  r.Keyring,
 			Password: r.RepositoryOpts.Password,
 			Repo:     r.RepositoryOpts.Repo,
-			Username: r.RepositoryOpts.Password,
+			Username: r.RepositoryOpts.Username,
```
Comment (viveklak) [inline provider/pkg/provider/helm_release.go:988]: 🤦🏾‍♂️  Thanks for the fix!
