### PR TITLE
Resource undergoing replacement has incorrect status messages

### LINKED ISSUE #2761: Replacement has incorrect status messages
### What happened?

I observe that Pulumi emits incorrect status messages when doing a replacement of a Kubernetes resource.  In particular, the last message pertaining to the "replacement" object (as it is created) is later shown on the "original" object (as it is deleted).  

### Example

For example, observe the erroneous "Waiting" messages in the following sequence. Note that I am using `--non-interactive` for clarity, and that Pulumi is using delete-after-replace semantics in this example.

```plain
 ++ kubernetes:core/v1:Pod autonaming-test creating replacement (0s) [diff: ~metadata]
 ++ kubernetes:core/v1:Pod autonaming-test creating replacement (0s) [diff: ~metadata];
 ++ kubernetes:core/v1:Pod autonaming-test creating replacement (0s) [diff: ~metadata]; Waiting for Pod "test-namespace-4d5e71b3/autonaming-test" to be scheduled
 ++ kubernetes:core/v1:Pod autonaming-test creating replacement (0s) [diff: ~metadata]; Waiting for Pod "test-namespace-4d5e71b3/autonaming-test" to be initialized
 ++ kubernetes:core/v1:Pod autonaming-test creating replacement (0s) [diff: ~metadata]; Waiting for Pod "test-namespace-4d5e71b3/autonaming-test" to be ready
@ updating....
 ++ kubernetes:core/v1:Pod autonaming-test created replacement (1s) [diff: ~metadata]; Waiting for Pod "test-namespace-4d5e71b3/autonaming-test" to be ready
 +- kubernetes:core/v1:Pod autonaming-test replacing (0s) [diff: ~metadata]; Waiting for Pod "test-namespace-4d5e71b3/autonaming-test" to be ready
 +- kubernetes:core/v1:Pod autonaming-test replaced (0.00s) [diff: ~metadata]; Waiting for Pod "test-namespace-4d5e71b3/autonaming-test" to be ready
 -- kubernetes:core/v1:Pod autonaming-test deleting original (0s) [diff: ~metadata]; Waiting for Pod "test-namespace-4d5e71b3/autonaming-test" to be ready
@ updating.....
 -- kubernetes:core/v1:Pod autonaming-test deleted original (1s) [diff: ~metadata]; Waiting for Pod "test-namespace-4d5e71b3/autonaming-test" to be ready
```

### Output of `pulumi about`

```
❯ pulumi about
CLI          
Version      3.94.2
Go Version   go1.21.4
Go Compiler  gc

Host     
OS       darwin
Version  13.5.1
Arch     arm64
```

### Additional context

I believe that the root cause is related to the fact that the "original" object and "replacement" object have the same resource URN. As the CLI emits a log line for each engine event, it repeats the most recent diagnostic message for the associated resource. The "replacement" object's await logic produces the diagnostic messages, but the "original" object doesn't produce any diagnostic message and so the last message of the former object is repeated.

Two fixes come to mind:
1. Clear the diagnostic message after the await logic completes for a given resource, and/or
2. Emit a diagnostic message in the await logic for deletions, e.g. "Waiting for finalization..."

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by EronWright**
### Proposed changes

This PR clears the resource status after the awaiter completes, to ensure that the status pertaining to a replacement resource (which would have the same URN) isn't stale.

In this example, the status message is obsolete once the flow hits "created replacement".  Before:
```
 ++ kubernetes:core/v1:Pod autonaming-test creating replacement (0s) [diff: ~metadata]
 ++ kubernetes:core/v1:Pod autonaming-test creating replacement (0s) [diff: ~metadata];
 ++ kubernetes:core/v1:Pod autonaming-test creating replacement (0s) [diff: ~metadata]; Waiting for Pod "test-namespace-4d5e71b3/autonaming-test" to be scheduled
 ++ kubernetes:core/v1:Pod autonaming-test creating replacement (0s) [diff: ~metadata]; Waiting for Pod "test-namespace-4d5e71b3/autonaming-test" to be initialized
 ++ kubernetes:core/v1:Pod autonaming-test creating replacement (0s) [diff: ~metadata]; Waiting for Pod "test-namespace-4d5e71b3/autonaming-test" to be ready
@ updating....
 ++ kubernetes:core/v1:Pod autonaming-test created replacement (1s) [diff: ~metadata]; Waiting for Pod "test-namespace-4d5e71b3/autonaming-test" to be ready
 +- kubernetes:core/v1:Pod autonaming-test replacing (0s) [diff: ~metadata]; Waiting for Pod "test-namespace-4d5e71b3/autonaming-test" to be ready
 +- kubernetes:core/v1:Pod autonaming-test replaced (0.00s) [diff: ~metadata]; Waiting for Pod "test-namespace-4d5e71b3/autonaming-test" to be ready
 -- kubernetes:core/v1:Pod autonaming-test deleting original (0s) [diff: ~metadata]; Waiting for Pod "test-namespace-4d5e71b3/autonaming-test" to be ready
@ updating.....
 -- kubernetes:core/v1:Pod autonaming-test deleted original (1s) [diff: ~metadata]; Waiting for Pod "test-namespace-4d5e71b3/autonaming-test" to be ready
```

After:
```
 ++ kubernetes:core/v1:Pod autonaming-test creating replacement (0s) [diff: ~metadata]
 ++ kubernetes:core/v1:Pod autonaming-test creating replacement (0s) [diff: ~metadata];
 ++ kubernetes:core/v1:Pod autonaming-test creating replacement (0s) [diff: ~metadata]; Waiting for Pod "test-namespace-c74027dd/autonaming-test" to be scheduled
 ++ kubernetes:core/v1:Pod autonaming-test creating replacement (0s) [diff: ~metadata]; Waiting for Pod "test-namespace-c74027dd/autonaming-test" to be initialized
 ++ kubernetes:core/v1:Pod autonaming-test creating replacement (0s) [diff: ~metadata]; Waiting for Pod "test-namespace-c74027dd/autonaming-test" to be ready
@ updating....
 ++ kubernetes:core/v1:Pod autonaming-test creating replacement (1s) [diff: ~metadata];
 ++ kubernetes:core/v1:Pod autonaming-test created replacement (1s) [diff: ~metadata];
 +- kubernetes:core/v1:Pod autonaming-test replacing (0s) [diff: ~metadata];
 +- kubernetes:core/v1:Pod autonaming-test replaced (0.00s) [diff: ~metadata];
 -- kubernetes:core/v1:Pod autonaming-test deleting original (0s) [diff: ~metadata];
@ updating.....
 -- kubernetes:core/v1:Pod autonaming-test deleting original (1s) [diff: ~metadata];
 -- kubernetes:core/v1:Pod autonaming-test deleted original (1s) [diff: ~metadata];
```

### Related issues (optional)

Closes #2761

### CODE REVIEW

File: provider/pkg/await/await.go [hunk 1]
```diff
@@ -276,6 +276,7 @@ func Creation(c CreateConfig) (*unstructured.Unstructured, error) {
 				if waitErr != nil {
 					return nil, waitErr
 				}
+				_ = clearStatus(c.Context, c.Host, c.URN)
```
Comment (t0yv0) [inline provider/pkg/await/await.go:279]: Nit: what I've seen at Pulumi before for intentionally ignoring errors is:

```
err := clearStatus(...)
contract.IgnoreError(err)
```

File: provider/pkg/await/await.go [hunk 2]
```diff
@@ -773,6 +776,10 @@ func Deletion(c DeleteConfig) error {
 				},
 				clientForResource: client,
 			})
+			if waitErr != nil {
```
Comment (t0yv0) [inline provider/pkg/await/await.go:779]: This is one bit here (and associated return) where it's not immediately obvious to a tired reader that control flow is not changing, and this is just a logging change, however I think that's still the case, it's not changing, localizing error handling to make the code better.. Appreciate eyes on this :)

**Review by t0yv0 — APPROVED** [review]
