### PR TITLE
Fix diff panic for malformed kubeconfig

### LINKED ISSUE #1543: Panic when diffing an invalid kubeconfig
A mixture of 2 space indents in YAML and 4 space indents in Typescript caused my editor to malform the `kubeconfig` during unrelated refactoring.

This causes `pulumi up` to panic when computing the `diff: ~kubeconfig`

## Expected behavior
Some reasonable error reporting instead of process crash.

## Current behavior
`pulumi up` crashes with:

```
  pulumi:pulumi:Stack (pulumi-kubernetes-segfault-dev):
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1d21d22]
    goroutine 29 [running]:
    github.com/pulumi/pulumi-kubernetes/provider/v3/pkg/provider.getActiveClusterFromConfig(0xc0004a86c0, 0xc00024ad20, 0xc000697380)
    	/home/runner/work/pulumi-kubernetes/pulumi-kubernetes/provider/pkg/provider/util.go:118 +0xe2
    github.com/pulumi/pulumi-kubernetes/provider/v3/pkg/provider.(*kubeProvider).DiffConfig(0xc0009a7a40, 0x2507808, 0xc00024ac00, 0xc0001e8000, 0xc0009a7a40, 0x1f0d501, 0xc000834180)
    	/home/runner/work/pulumi-kubernetes/pulumi-kubernetes/provider/pkg/provider/provider.go:345 +0xcb8
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_DiffConfig_Handler.func1(0x2507808, 0xc00024ac00, 0x20b3780, 0xc0001e8000, 0x20c8ca0, 0x3561868, 0x2507808, 0xc00024ac00)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.0.0/proto/go/provider.pb.go:2158 +0x89
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x2507808, 0xc000120ab0, 0x20b3780, 0xc0001e8000, 0xc00013e0c0, 0xc0004020d8, 0x0, 0x0, 0x24c19e0, 0xc00007d790)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x30a
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_DiffConfig_Handler(0x214f4a0, 0xc0009a7a40, 0x2507808, 0xc000120ab0, 0xc0004a84e0, 0xc000622d80, 0x2507808, 0xc000120ab0, 0xc000577300, 0x127a)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.0.0/proto/go/provider.pb.go:2160 +0x150
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc00079ce00, 0x25235b8, 0xc000582600, 0xc000538100, 0xc00070de60, 0x34ff1d0, 0x0, 0x0, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.34.0/server.go:1210 +0x52b
    google.golang.org/grpc.(*Server).handleStream(0xc00079ce00, 0x25235b8, 0xc000582600, 0xc000538100, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.34.0/server.go:1533 +0xd0c
    google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000532080, 0xc00079ce00, 0x25235b8, 0xc000582600, 0xc000538100)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.34.0/server.go:871 +0xab
    created by google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.34.0/server.go:869 +0x1fd
```

## Steps to reproduce
I've minimized the problem: https://github.com/rraval/pulumi-kubernetes-segfault

1. Check out the initial commit: [`index.ts`](https://github.com/rraval/pulumi-kubernetes-segfault/blob/7e563fbe872db01be91c75eceac5bc46589cf150/index.ts).
2. Run `pulumi up` with no issues.
3. Move to the second commit: [`index.ts`](https://github.com/rraval/pulumi-kubernetes-segfault/blob/ff38268a7582a3996e2e971ffc5016290b041fe8/index.ts), [Diff](https://github.com/rraval/pulumi-kubernetes-segfault/commit/ff38268a7582a3996e2e971ffc5016290b041fe8#diff-dcdc3e0b3362edb8fec2a51d3fa51f8fb8af8f70247e06d9887fa934834c9122). This commit corrupts the indentation of `kubeconfig`, making it invalid.
4. Run `pulumi up` again, see panic from above.

## Context (Environment)

Refactoring some code to move the provider creation from top level into a function (hence the change in indentation).

### PR DESCRIPTION
**Pull request by lblackstone**
### Proposed changes
If the kubeconfig context name was not indented
properly, it could lead to a map lookup failing, and
then a subsequent unchecked nil value.

### Related issues (optional)
Fix #1543

### CODE REVIEW

File: provider/pkg/provider/util.go [hunk 1]
```diff
@@ -115,7 +115,11 @@ func getActiveClusterFromConfig(config *clientapi.Config, overrides resource.Pro
...
 	}
 
-	activeClusterName := config.Contexts[currentContext].Cluster
+	activeContext := config.Contexts[currentContext]
+	if activeContext == nil {
+		return &clientapi.Cluster{}
+	}
+	activeClusterName := activeContext.Cluster
 
 	activeCluster := config.Clusters[activeClusterName]
```
Comment (lukehoban) [inline provider/pkg/provider/util.go:120]: Can the same issue occur here as well?

File: provider/pkg/provider/util.go [hunk 2]
```diff
@@ -115,7 +115,11 @@ func getActiveClusterFromConfig(config *clientapi.Config, overrides resource.Pro
 		currentContext = val.StringValue()
 	}
 
-	activeClusterName := config.Contexts[currentContext].Cluster
+	activeContext := config.Contexts[currentContext]
+	if activeContext == nil {
+		return &clientapi.Cluster{}
```
Comment (lukehoban) [inline provider/pkg/provider/util.go:120]: This means we don't report up a useful error about what caused this. Should this function return a useful error?

**Review by lukehoban — APPROVED** [review]
Can we add test coverage for these failure cases?

File: provider/pkg/provider/util.go (hunk 1 above)
Comment (lblackstone) [reply provider/pkg/provider/util.go:120]: Looks like it. Good catch.

File: provider/pkg/provider/util.go (hunk 2 above)
Comment (lblackstone) [reply provider/pkg/provider/util.go:120]: I'm not sure it's possible to tell if this is actually an error since this runs during preview and Outputs may not yet be fully resolved. I suspect that it might lead to erroneous warnings.

This particular case was a bit odd because the outdented YAML still parsed cleanly, but changed the semantics of the configuration. This change fixes the panic, and now correctly shows a replacement in the preview. This should be sufficient for a user to notice that something is going wrong if they weren't expecting a change.
