### PR TITLE
Emit useful error when `kubernetes:config:kubeconfig` fails to parse

### LINKED ISSUE #209: Problem parsing kubeconfig when passed via "kubernetes:kubeconfig"
If I set `$KUBECONFIG` in my environment, then pulumi can find my cluster and things work fine.

But if I set `kubernetes:kubeconfig` in my stack's yaml, I get an error:

```
Diagnostics:
  global: global
    error: failed to parse kubeconfig: couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
```

The first issue is certainly that it is [trying to parse the filename as a kubeconfig](https://github.com/pulumi/pulumi-kubernetes/blob/master/pkg/provider/provider.go#L131). That is almost certainly a bug. After that, I'm not clear if the underlying codec will accept yaml/json interchangably, but I will try to find out and make a pr.

### PR DESCRIPTION
**Pull request by hausdorff**
Fixes #209.

### CODE REVIEW

File: pkg/provider/provider.go [hunk 1]
```diff
@@ -234,7 +234,9 @@ func (k *kubeProvider) Configure(_ context.Context, req *pulumirpc.ConfigureRequ
 	if configJSON, ok := vars["kubernetes:config:kubeconfig"]; ok {
 		config, err := clientcmd.Load([]byte(configJSON))
 		if err != nil {
-			return nil, fmt.Errorf("failed to parse kubeconfig: %v", err)
+			return nil, pkgerrors.Wrap(err, "failed to parse kubeconfig data in "+
```
Comment (pgavlin) [inline pkg/provider/provider.go]: Does a YAML literal work here as well as JSON? Also, the wording is a bit informal; I'd kill "and not (say) a filename".

Comment (hausdorff) [reply pkg/provider/provider.go]: Updated the wording, but I think it's fine to not bother to clarify that JSON is a strict subset of YAML because (1) "YAML" in the k8s ecosystem is used, basically, as shorthand for "JSON or YAML", (20 I've actually never seen someone write kubeconfig in JSON (3) if you do, `kubectl` auto-converts it to YAML the first time it changes it for any reason, and (4) the ecosystem, IME, largely understands that JSON is a subset of YAML anyway.
