### PR TITLE
Replace PersistentVolume if volume source changes

### LINKED ISSUE #1014: PersistentVolume immutable fields don't trigger replace
### Problem description

When changing `spec.awsElasticBlockStore.volumeID` of a `.core.v1.PersistentVolume` pulumi tries to update instead of replace and gets a Kubernetes API error.

### Errors & Logs

`the Kubernetes API server reported that "<pv>" failed to fully initialize or become live: PersistentVolume "<pv>" is invalid: spec.persistentvolumesource: Forbidden: is immutable after creation`

### Affected product version(s)

pulumi: 1.11.1
k8s server: 1.14.9

### Reproducing the issue

I assume changing `spec.awsElasticBlockStore.volumeID` on any `.core.v1.PersistentVolume` will fail.

### Suggestions for a fix

Make that field trigger a replacement instead of an update.

Or maybe https://github.com/pulumi/pulumi-kubernetes/issues/342

### PR DESCRIPTION
**Pull request by lblackstone**
### Proposed changes
Add replacement cases for PersistentVolume to the diff
logic. All PersistentVolumeSource fields are immutable.

### Related issues (optional)
Fixes #1014

### CODE REVIEW

File: pkg/provider/diff.go [hunk 1]
```diff
@@ -78,6 +78,31 @@ var forceNew = _groups{
 var core = _versions{
 	"v1": _kinds{
 		"ConfigMap": properties{".binaryData", ".data"},
+		"PersistentVolume": append(
```
Comment (metral) [inline pkg/provider/diff.go]: Let's link the [volume types doc](https://kubernetes.io/docs/concepts/storage/volumes/#types-of-volumes).

---

Any chance we can programmatically pull this list from the API?

 e.g.

`kubectl explain pod.spec.volumes` shows all volume types so it seems like API's should be possible. Thoughts?

Comment (lblackstone) [reply pkg/provider/diff.go]: I pulled this info from the API reference, but am not sure of a reliable way to do so programmatically. I included everything that had a Kind name ending in `VolumeSource`, but these Kinds don't seem to share a common interface.

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#volume-v1-core

Comment (metral) [reply pkg/provider/diff.go]: Not a fan of reflect in Go due to its perf cost, but is it worth considering asserting the various interfaces to approach this programmatically. Is this viable?

Comment (lblackstone) [reply pkg/provider/diff.go]: Since the rest of this file is also manually curated for now, I'm inclined to defer further work here. We need to figure out a more robust approach at some point, but that's probably going to involve upstream work to fix the k8s OpenAPI spec.

Comment (lblackstone) [reply pkg/provider/diff.go]: #342

**Comment by maxromanovsky** [comment]
On a somewhat different, but similar matter: how about adding a logic to re-create PVs based on `status`? If PV has status `Released`, then it cannot be re-used unless manually re-created. How about handling such case automatically if `opts.delete_before_replace` is `true`? [Reference](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#retain)

```yaml
status:
  phase: Released
```
