### PR TITLE
Use dry-run in Diff when available.

### LINKED ISSUE #644: API server normalization of values is causing a preview to show changes when one is not expected in testing.
This error showed up in CI cron jobs in the last 24 hours of `pulumi/eks` tests:

A deployment marked with resources `2048Mi` is being normalized to `2Gi` on the initial update, and then on the `empty` `pulumi preview` step it is trying to change it back to `2048Mi` - this unexpected change causes the test to fail when it does not expect changes.

This occurs on `pulumi preview` right after an initial `pulumi up` of a Deployment using resources with `2048Mi` notation.

```
metral@argon:~/temp-clusters/migrate-nodegroups-6$ pul preview --diff
Previewing update (test6):
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:test6::migrate-nodegroups::pulumi:pulumi:Stack::migrate-nodegroups-test6]
    ~ kubernetes:apps/v1:Deployment: (update)
        [id=apps-ql27r77a/nginx-ing-cntlr-tr0nrsi8]
        [urn=urn:pulumi:test6::migrate-nodegroups::kubernetes:apps/v1:Deployment::nginx-ing-cntlr]
        [provider=urn:pulumi:test6::migrate-nodegroups::eks:index:Cluster$pulumi:providers:kubernetes::migrate-nodegroups-provider::4316e425-4b56-4dd0-9d7e-78555a61b922]
      ~ spec: {
          ~ template: {
              ~ spec: {
                  ~ containers: [
                      ~ [0]: {
                              ~ resources: {
                                  ~ limits  : {
                                      ~ memory: "2Gi" => "2048Mi"
                                    }
                                  ~ requests: {
                                      ~ memory: "1Gi" => "1024Mi"
                                    }
                                }
                            }
                    ]
                }
            }
        }
Resources:
    ~ 1 to update
    84 unchanged
```

**Versions**:
- `pulumi/pulumi`: 0.17.25
- `pulumi/kubernetes`: 0.25.2
- `pulumi/eks`: 0.18.10

See related Slack [conversation](https://pulumi.slack.com/archives/CBUP505U7/p1562651913033000
) about a similar type of error occurring in the aws-tf-provider a couple weeks back.

### PR DESCRIPTION
**Pull request by pgavlin**
These changes update `Diff` to calculate the new state for the patched
resource by requesting that the API server dry-run the patch when
possible. This avoids unexpected diffs due to server-side normalization
of values that are present in both the resource's configuration and its
state.

Fixes #644.

### CODE REVIEW

File: pkg/provider/provider.go [hunk 1]
```diff
@@ -1370,9 +1428,15 @@ type patchConverter struct {
 // If a difference is present at the given path and the path matches one of the patterns in the database of
 // force-new properties, the diff is amended to indicate that the resource needs to be replaced due to the change in
 // this property.
-func (pc *patchConverter) addPatchValueToDiff(path []interface{}, v, old interface{}, inArray bool) error {
+func (pc *patchConverter) addPatchValueToDiff(path []interface{}, v, old, input interface{}, inArray bool) error {
 	contract.Assert(v != nil || old != nil)
 
+	// If there is no old input, then the only possible diff here is a delete. All other diffs must be diffs between
+	// old and new properties that are populated by the server.
+	if input == nil && v != nil {
```
Comment (pgavlin) [inline pkg/provider/provider.go]: Though this will handle the case where a server-populated property is added or changed between the old and the new state, it won't handle the case where a server-populated property is deleted. In order to handle that case we'd also need to provider the old input value. This is easy enough to do that we should probably just bite the bullet and do it.

Comment (pgavlin) [reply pkg/provider/provider.go]: I went ahead and did this.

File: tests/integration/dry-run/step1/index.ts [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+                            // dry-run support, Pulumi will detect a spurious diff due to the normalization.
+                            memory: "2048Mi",
+                        },
+                    },
+                }],
+            }
+        }
+    }
+});
+export const name = deployment.metadata.apply(m => m.name);
```
Comment (lblackstone) [inline tests/integration/dry-run/step1/index.ts]:
```suggestion
export const name = deployment.metadata.name;
```
