### PR TITLE
Automatically fill in .Capabilities in Helm Charts

### LINKED ISSUE #196: Automatically fill in `.Capabilities` in Helm Charts
These are typically filled in on the server (_e.g._, whether the API server supports RBAC or not). Helm Charts tend to use these values for doing things like determining the `apiVersion` to use for certain resources. If this is not filled in, it can fail in extremely confusing ways.

### LINKED ISSUE #753: Pass correct --kube-version to `helm template`
### Problem description

helm  template is invoked without `--kube-version`, which then internally defaults to `1.9` cluster version. 

### Suggestions for a fix

get kubernetes version from provider and pass it to `helm template --kube-version ${k8sver}`

### LINKED ISSUE #2141: Helm Release fails if Chart uses .Capabilities.APIVersions
### What happened?

I was trying to install Cilium's Helm Chart using Pulumi and once I enabled the ServiceMonitor option it failed, even though the cluster I was targeting had prometheus-operator CRDs installed in it.

When I investigated the chart I found it was using `.Capabilities.APIVersions.Has` to force it to error out if the CRD wasn't installed. The lines in the Helm file which are causing this issue are specified here https://github.com/cilium/cilium/blob/master/install/kubernetes/cilium/templates/validate.yaml#L18-L23.

I did find a closed issue in Cilium's repo which asked for a way to override this check but they closed the ticket as depending on the Kubernetes version and API versions available it changes what the chart outputs https://github.com/cilium/cilium/issues/16552

When I looked through Pulumi's code I saw that APIVersions is set to nil when passed into Helm for rendering https://github.com/pulumi/pulumi-kubernetes/blob/5277945f4d5fd63032d3f7014e27fb113335eeaa/provider/pkg/provider/helm_release.go#L1107

Therefore, I need a way to either manually specify what the APIVersions are or that Pulumi automatically detects the APIVersions installed in the target cluster and passes it into Helm.

### Steps to reproduce

Created an empty stack and ensured that kubectl is pointing at a cluster with Prometheus Operator CRDs installed in it
```js
import * as pulumi from '@pulumi/pulumi'
import * as k8s from '@pulumi/kubernetes'

const cilium = new k8s.helm.v3.Release('cilium', {
  chart: 'cilium',
  version: '1.12.0',
  repositoryOpts: {
    repo: 'https://helm.cilium.io/'
  },
  namespace: 'kube-system',
  values: {
    prometheus: {
      enabled: true,
      serviceMonitor: {
        enabled: true
      }
    }
  }
})
```

### Expected Behavior

The helm release is deployed without error into the cluster which already contains the prometheus-operator CRD's

### Actual Behavior

```
❯ pulumi preview
Previewing update (archie-test):
     Type                              Name                     Plan       Info
 +   pulumi:pulumi:Stack               archie-test-archie-test  create     
     └─ kubernetes:helm.sh/v3:Release  cilium                              1 error
 
Diagnostics:
  kubernetes:helm.sh/v3:Release (cilium):
    error: failed to create chart from template: execution error at (cilium/templates/validate.yaml:21:9): Service Monitor requires monitoring.coreos.com/v1 CRDs. Please refer to https://github.com/prometheus-operator/prometheus-operator/blob/master/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
```

### Versions used

```
❯ pulumi about
CLI          
Version      3.37.2
Go Version   go1.18.4
Go Compiler  gc

Plugins
NAME        VERSION
kubernetes  3.20.4
nodejs      unknown

Host     
OS       darwin
Version  12.5
Arch     x86_64

This project is written in nodejs: executable='/Users/archie/.nvm/versions/node/v16.16.0/bin/node' version='v16.16.0'

Backend        
Name           ARCHIE-LAPTOP
URL            gs://pulumi-state
User           archie
Organizations  

Dependencies:
NAME                VERSION
@pulumi/pulumi      3.37.2
@types/node         14.18.24
@pulumi/kubernetes  3.20.4

Pulumi locates its logs in /var/folders/7f/4wh6789d7bl12zbm5kqf65m00000gp/T/ by default
warning: Failed to get information about the current stack: No current stack
```

### Additional context

I know the CRDs are installed correctly because kubectl reported they are created
```
❯ kubectl get customresourcedefinitions.apiextensions.k8s.io servicemonitors.monitoring.coreos.com
NAME                                    CREATED AT
servicemonitors.monitoring.coreos.com   2022-06-16T15:52:25Z
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by yann-soubeyrand**
### Proposed changes

This PR tries to add automatic filling of Helm capabilities (Kubernetes version and API versions) in Chart resource. I’ve successfully built and tested this PR with a simple chart, but I’m not familiar with development on this repository (on Pulumi providers in general), so I may need some help to bring this PR to proper releasable state.

### Related issues (optional)

Fix #196
Fix #2141
Fix #753

### CODE REVIEW

File: provider/pkg/provider/invoke_helm_template.go [hunk 1]
```diff
@@ -245,6 +242,43 @@ func (c *chart) template() (string, error) {
...
+			Minor:   kubeVersion.Minor,
+		}
+
+		installAction.APIVersions = apiVersions
+	}
+
+	// Preserve backward compatibility
+	if len(c.opts.APIVersions) > 0 {
+		installAction.APIVersions = c.opts.APIVersions
+	}
```
Comment (lblackstone) [inline provider/pkg/provider/invoke_helm_template.go:280]: I'd check this first, and skip the discovery client calls to the apiserver if true.

**Review by lblackstone — COMMENTED** [review]
This looks great; thanks for the PR @yann-soubeyrand! Just one minor suggestion, and then LGTM if the tests pass.

File: provider/pkg/provider/invoke_helm_template.go (hunk 1 above)
Comment (yann-soubeyrand) [reply provider/pkg/provider/invoke_helm_template.go]: Hello @lblackstone, thanks for the review :wink:

I followed your suggestion and modified the code, but now I’m wondering if we really want to disable Kubernetes version discovery when APIVersions are provided. What do you think?

Regarding the tests, it seems they haven’t run, do I have to fix something on my side?

Comment (yann-soubeyrand) [reply provider/pkg/provider/invoke_helm_template.go]: I posted a message in Slack (https://pulumi-community.slack.com/archives/CRFURDVQB/p1661613221358179) to get some directions on how to develop on this provider, maybe you have the answers to my questions?

Comment (lblackstone) [reply provider/pkg/provider/invoke_helm_template.go]: > I followed your suggestion and modified the code, but now I’m wondering if we really want to disable Kubernetes version discovery when APIVersions are provided. What do you think?

Ah, I didn't notice that the `DefaultCapabilities` was setting the kube version before, and defaulted to v1.20. Maybe we should set that explicitly here? The problem is that the cluster may not be available yet when this code is running (i.e., if it's a preview in a stack where the cluster hasn't been created yet), so we need a fallback value set.

> Regarding the tests, it seems they haven’t run, do I have to fix something on my side?

For external contributors, a maintainer has to run the tests with the `/run-acceptance-tests` comment, and then the bot will respond with a link to the test run that you can check: https://github.com/pulumi/pulumi-kubernetes/pull/2155#issuecomment-1230941714

It looks like everything passed, so this should be good once we handle the default k8s version.

Comment (yann-soubeyrand) [reply provider/pkg/provider/invoke_helm_template.go]: > > I followed your suggestion and modified the code, but now I’m wondering if we really want to disable Kubernetes version discovery when APIVersions are provided. What do you think?
> 
> Ah, I didn't notice that the `DefaultCapabilities` was setting the kube version before, and defaulted to v1.20. Maybe we should set that explicitly here? The problem is that the cluster may not be available yet when this code is running (i.e., if it's a preview in a stack where the cluster hasn't been created yet), so we need a fallback value set.

The default KubeVersion seems to still be set here https://github.com/helm/helm/blob/dbc6d8e20fe1d58d50e6ed30f09a04a77e4c68db/pkg/action/install.go#L216.

My concern was about the fact that people having APIVersions manually set won’t benefit from the discovery of the KubeVersion. But it’s not a regression. We could also add the ability to manually set the KubeVersion (as for the APIVersions), but that’d be a fairly different PR :wink: 

> 
> > Regarding the tests, it seems they haven’t run, do I have to fix something on my side?
> 
> For external contributors, a maintainer has to run the tests with the `/run-acceptance-tests` comment, and then the bot will respond with a link to the test run that you can check: [#2155 (comment)](https://github.com/pulumi/pulumi-kubernetes/pull/2155#issuecomment-1230941714)
> 
> It looks like everything passed, so this should be good once we handle the default k8s version.

Ha OK, I had a notification with this link https://github.com/pulumi/pulumi-kubernetes/actions/runs/2939221543 which made me think the tests didn’t run, I didn’t see https://github.com/pulumi/pulumi-kubernetes/actions/runs/2952219436, so that’s OK :wink:

**Review by lblackstone — APPROVED** [review]
LGTM -- thanks for a great PR!

**Comment by LambArchie** [comment]
Thank you @yann-soubeyrand for doing this PR as it fixes the issue I had in #2141 (I've tested locally to check it does everything my issue needed it to do)

**Comment by yann-soubeyrand** [comment]
Thanks @lblackstone for the prompt review :wink:

**Comment by LucasBrazi06** [comment]
@yann-soubeyrand I see only apiVersions in the Chart's options but I would have expected also kubeVersions to solve the issue you had in the first place and that I'm currently having: #2249
What did you do to fixed it?
Thanks in advance!

**Comment by yann-soubeyrand** [comment]
@LucasBrazi06 to solve this issue, I added the ability to automatically fill in .Capabilities (which contains Kubernetes version) in Helm Charts to this provider. Therefore, the (existing) apiVersions attribute should not be needed nor the (non-existing) kubeVersion attribute.
