### PR TITLE
Fix Deployment await logic

### LINKED ISSUE #611: A failed Deployment update doesn't seem to fail
If I update an existing Deployment to reference an erroneous image name, the update succeeds, even though the resulting Pod ends up in an endless backoff.

The resulting `kubectl get po` looks like this:

```
$ kubectl get po
NAME                              READY     STATUS             RESTARTS   AGE
nginx-u76btcdw-9b5ccdb7-psf64     0/1       ImagePullBackOff   0          22s
nginx-u76btcdw-9cb4784bd-vjrww    1/1       Running            0          52s
```

`nginx-u76btcdw-9cb4784bd-vjrww` is the old Pod running the correctly named image -- which I assume would go away once the rollout has completed -- and `nginx-u76btcdw-9b5ccdb7-psf64` is the newly created Pod that is meant to replace it, but cannot, due to the mistyped image name.

This is inconsistent with what happens with a new `Deployment`. Shouldn't this fail too?

-------

@lblackstone Update:
I've fixed this for all apiVersions except for `extensions/v1beta1`, which will require additional work. Will close out this issue once #656 is done.

### PR DESCRIPTION
**Pull request by lblackstone**
The Deployment await logic had a bug for the old `extensions/v1beta1`
apiVersion which was causing the await logic to erroneously pass for
change triggered rollouts, even if the Deployment was invalid.

For some reason, the resource client was defaulting to
the old apiVersion, even though recent versions were available on the
cluster. Updated the client to ignore `extensions/v1beta1`, and
reverted the buggy await logic related to that apiVersion.

Fixes #611

### CODE REVIEW

File: pkg/clients/clients.go [hunk 1]
```diff
@@ -117,6 +117,11 @@ func (dcs *DynamicClientSet) gvkForKind(kind kinds.Kind) (*schema.GroupVersionKi
 	}
 
 	for _, gvResources := range resources {
+		// For some reason, the server is returning the old "extensions/v1beta1" GV before "apps/v1", so manually
+		// skip it.
+		if gvResources.GroupVersion == "extensions/v1beta1" {
+			continue
```
Comment (hausdorff) [inline pkg/clients/clients.go]: I really do not like skipping the API versions here. If we have a preferred API version I think we should look for it and then fall back to this if we can't find it.

**Comment by hausdorff** [comment]
Also we concluded that this partial revert breaks old versions of `Deployment`, right?

**Comment by lblackstone** [comment]
> Also we concluded that this partial revert breaks old versions of `Deployment`, right?

Right, as shown by the failing test. Instead of reverting, I'm working on fixing the workaround logic for the `extensions/v1beta1` version.

File: pkg/await/apps_deployment.go [hunk 2]
```diff
@@ -460,6 +459,11 @@ func (dia *deploymentInitAwaiter) processDeploymentEvent(event watch.Event) {
 		}
 	}
 
+	// Since we can't tell for sure from this version of the API, mark ReplicaSet as available.
```
Comment (hausdorff) [inline pkg/await/apps_deployment.go]: I'm fine with this as a bug fix, but we should be able to actually account for this by looking at the pods themselves, right?

File: pkg/await/apps_deployment.go [hunk 3]
```diff
@@ -416,10 +417,8 @@ func (dia *deploymentInitAwaiter) processDeploymentEvent(event watch.Event) {
 			continue
 		}
 
-		if progressingStatusUnavailable {
-			// Since we can't tell for sure from this version of the API, mark as available.
-			dia.replicaSetAvailable = true
-		} else if condition["type"] == "Progressing" {
+		if condition["type"] == "Progressing" {
+		    progressingStatusUnavailable = false
```
Comment (hausdorff) [inline pkg/await/apps_deployment.go]: I'm confused about why this is correct, and why the previous way of doing this is incorrect. Also, if the controller is slow to add the progressing condition initially, we'll just mark the deployment as available, won't we? That doesn't seem right.

File: pkg/await/apps_deployment.go (hunk 2 above)
Comment (lblackstone) [reply pkg/await/apps_deployment.go]: Yeah, I think so. I'm inclined to rewrite this awaiter sooner rather than later because I'm having trouble wrapping my head around all of the nuances here.

File: pkg/await/apps_deployment.go (hunk 3 above)
Comment (lblackstone) [reply pkg/await/apps_deployment.go]: The problem I'm running into is that it doesn't seem to be possible to tell if the Progressing status will ever exist for a Deployment. If it was created with the `extensions/v1beta1` API, it will not include that status, even if you request the `apps/v1` version. I missed that nuance previously, so explicitly checking the apiVersion on the received object doesn't do any good.

I think we need to reexamine the await logic for Deployment, and possibly avoid using this status field to make a determination since it doesn't work in general.

Comment (hausdorff) [reply pkg/await/apps_deployment.go]: We can tell based on the inputs what API version we was used to create this resource, though, right?

File: pkg/await/apps_deployment.go (hunk 2 above)
Comment (lblackstone) [reply pkg/await/apps_deployment.go]: Still working on a fix for the `extensions/v1beta1` apiVersion, but pushing a fix for the other apiVersions in the meantime. I'll address the workaround separately

**Comment by hausdorff** [comment]
Also note that this is _not_ a fix for #611 any more. It is a fix for a related issue.

**Comment by lblackstone** [comment]
@hausdorff Opened #656 to track the portion I'm not addressing here.
