### PR TITLE
Fix bug with Go Helm v3 transformation marshaling

### LINKED ISSUE #1369: Error with yaml transformation in go helm/v3
### Problem description

Using `[]yaml.transformation` with `helm/v3` while the same code works with `helm/v2`:

```
error: program failed: json: unsupported type: func(map[string]interface {}, ...pulumi.ResourceOption)
    exit status 1
 
    error: an unhandled error occurred: program exited with non-zero exit code: 1
``` 

### Affected product version(s)

pulumi `v2.13.2`
pulumi-kubernetes sdk `v2.6.3`
go version `1.15.3`

### Reproducing the issue
consider the following pulumi program:

```go
package main

import (
	"github.com/pulumi/pulumi-kubernetes/sdk/v2/go/kubernetes/helm/v3"
	"github.com/pulumi/pulumi-kubernetes/sdk/v2/go/kubernetes/yaml"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {

		_, err := helm.NewChart(ctx, "jaeger-operator", helm.ChartArgs{
			Chart: pulumi.String("jaeger-operator"),
			FetchArgs: helm.FetchArgs{
				Repo: pulumi.String("https://jaegertracing.github.io/helm-charts"),
			},
			Transformations: []yaml.Transformation{
				// when the operator pod starts it overrides the
				// .spec.selector of svc/jaeger-operator-metrics field to
				// `name=jaeger-operator` which is missing from the pod labels,
				// so the endpoints are never created. we add that label here to mitigate that
				func(state map[string]interface{}, opts ...pulumi.ResourceOption) {
					if state["kind"] == "Deployment" {
						podTemplate := state["spec"].(map[string]interface{})["template"].(map[string]interface{})
						podLabels := podTemplate["metadata"].(map[string]interface{})["labels"].(map[string]interface{})
						podLabels["name"] = "jaeger-operator"
					}
				},
			},
		})
		if err != nil {
			return err
		}

		return nil
	})
}
```

it fails with the error above, but using `github.com/pulumi/pulumi-kubernetes/sdk/v2/go/kubernetes/helm/v2` works as expected and pulumi is able to create the resources just fine

### PR DESCRIPTION
**Pull request by lblackstone**
### Proposed changes
The Helm v3 code was incorrectly trying to marshal transformation functions into JSON before invoking the provider's Helm support. The transformations only execute in the context of the SDK, so the correct behavior is to omit those in the marshaled JSON.

### Related issues (optional)
Fix #1369

### CODE REVIEW

**Review by komalali — APPROVED** [review]

**Review by viveklak — APPROVED** [review]

File: sdk/go/kubernetes/helm/v3/pulumiTypes.go [hunk 1]
```diff
@@ -150,7 +150,7 @@ type chartArgs struct {
 	APIVersions     []string               `json:"api_versions,omitempty" pulumi:"apiVersions"`
 	Namespace       string                 `json:"namespace,omitempty" pulumi:"namespace"`
 	Values          map[string]interface{} `json:"values,omitempty" pulumi:"values"`
-	Transformations []yaml.Transformation  `json:"transformations,omitempty" pulumi:"transformations"`
+	Transformations []yaml.Transformation  `json:"-" pulumi:"transformations"`
```
Comment (viveklak) [inline sdk/go/kubernetes/helm/v3/pulumiTypes.go:153]: Nit: Perhaps add a small note here about why this is dropped?
