### PR TITLE
Handle CSA to SSA field manager conflicts

### LINKED ISSUE #2352: Field manager name conflicts for resources created with client-side apply
### What happened?

Recent versions of kubernetes began setting a field manager for all resources based on the name of the executable performing the update, even for resources managed using client-side apply. This can cause problems for resources that were created using client-side apply that are subsequently updated using server-side apply because the field manager name may conflict.

Related: https://github.com/pulumi/pulumi-kubernetes/issues/2262

### Expected Behavior

Updating a resource created using client-side apply mode should not cause conflicts based on the field manager name.

### Steps to reproduce

1. Create a resource using client-side apply mode with pulumi-kubernetes
2. Change the provider to use SSA mode and update a value on the resource
3. Run an update
4. The field manager name will conflict and raise an error

Example:

```ts
import * as k8s from "@pulumi/kubernetes";

const provider = new k8s.Provider("k8s", {
    enableServerSideApply: false, // change to true on step 2
});
const appLabels = { app: "nginx" };
const deployment = new k8s.apps.v1.Deployment("nginx", {
    spec: {
        selector: {matchLabels: appLabels},
        replicas: 3,
        template: {
            metadata: {labels: appLabels},
            spec: {
                containers: [
                    {
                        name: "nginx",
                        image: "nginx:1.16", // change to "nginx:1.17" on step 2
                    },
                ],
            },
        },
    }
}, {provider});
```

Results in the following error:
```
  kubernetes:apps/v1:Deployment (nginx):
    error: Preview failed: 1 error occurred:
    	* the Kubernetes API server reported that "default/nginx-f43bda57" failed to fully initialize or become live: Server-Side Apply field conflict detected. see https://www.pulumi.com/registry/packages/kubernetes/how-to-guides/managing-resources-with-server-side-apply/#handle-field-conflicts-on-existing-resources for troubleshooting help
    : Apply failed with 1 conflict: conflict with "pulumi-resource-kubernetes" using apps/v1: .spec.template.spec.containers[name="nginx"].image
```

### Output of `pulumi about`

n/a

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by lblackstone**
### Proposed changes
Some versions of k8s have started setting managed fields for all resources, even those managed by
Client-side Apply (CSA). This can cause field manager conflicts when a resource is upgraded to
Server-side Apply (SSA). This change detects this type of conflict and forces the patch to avoid raising an
error.

### Related issues (optional)
Fix #2352

### CODE REVIEW

**Comment by lblackstone** [comment]
@rquitales It just occurred to me that it might be preferable to transfer management of all fields to a SSA field manager on a CSA -> SSA upgrade rather than handling when conflicts arise. Any thoughts on that?

Concretely, the current change results in two different field managers like this (note the difference in the "operation", which causes a conflict even if the "manager" name matches):
```json
{
    "apiVersion": "apps/v1",
    "fieldsType": "FieldsV1",
    "fieldsV1": {
        "f:metadata": {
            "f:annotations": {
                "f:pulumi.com/autonamed": {}
            },
            "f:labels": {
                "f:app.kubernetes.io/managed-by": {}
            }
        },
        "f:spec": {
            "f:replicas": {},
            "f:selector": {},
            "f:template": {
                "f:metadata": {
                    "f:labels": {
                        "f:app": {}
                    }
                },
                "f:spec": {
                    "f:containers": {
                        "k:{\"name\":\"nginx\"}": {
                            ".": {},
                            "f:image": {},
                            "f:name": {}
                        }
                    }
                }
            }
        }
    },
    "manager": "pulumi-kubernetes-9dbcec1c", // <-- The SSA field manager
    "operation": "Apply",
    "time": "2023-04-06T15:50:51Z"
},
{
    "apiVersion": "apps/v1",
    "fieldsType": "FieldsV1",
    "fieldsV1": {
        "f:metadata": {
            "f:annotations": {
                ".": {},
                "f:kubectl.kubernetes.io/last-applied-configuration": {},
                "f:pulumi.com/autonamed": {}
            },
            "f:labels": {
                ".": {},
                "f:app.kubernetes.io/managed-by": {}
            }
        },
        "f:spec": {
            "f:progressDeadlineSeconds": {},
            "f:replicas": {},
            "f:revisionHistoryLimit": {},
            "f:selector": {},
            "f:strategy": {
                "f:rollingUpdate": {
                    ".": {},
                    "f:maxSurge": {},
                    "f:maxUnavailable": {}
                },
                "f:type": {}
            },
            "f:template": {
                "f:metadata": {
                    "f:labels": {
                        ".": {},
                        "f:app": {}
                    }
                },
                "f:spec": {
                    "f:containers": {
                        "k:{\"name\":\"nginx\"}": {
                            ".": {},
                            "f:imagePullPolicy": {},
                            "f:name": {},
                            "f:resources": {},
                            "f:terminationMessagePath": {},
                            "f:terminationMessagePolicy": {}
                        }
                    },
                    "f:dnsPolicy": {},
                    "f:restartPolicy": {},
                    "f:schedulerName": {},
                    "f:securityContext": {},
                    "f:terminationGracePeriodSeconds": {}
                }
            }
        }
    },
    "manager": "pulumi-resource-kubernetes",  // <-- The CSA field manager
    "operation": "Update",
    "time": "2023-04-06T15:50:04Z"
},
```

File: provider/pkg/await/await.go [hunk 1]
```diff
@@ -438,13 +444,29 @@ func Update(c UpdateConfig) (*unstructured.Unstructured, error) {
 			// Issue patch request.
 			// NOTE: We can use the same client because if the `kind` changes, this will cause
 			// a replace (i.e., destroy and create).
-			currentOutputs, err = client.Patch(c.Context, c.Inputs.GetName(), types.ApplyPatchType, objYAML, options)
-			if err != nil {
-				if errors.IsConflict(err) {
-					err = fmt.Errorf("Server-Side Apply field conflict detected. see %s for troubleshooting help\n: %w",
-						ssaConflictDocLink, err)
+			maybeRetry := true
+			for {
```
Comment (rquitales) [inline provider/pkg/await/await.go:448]: Logic here mostly looks good to me.
nit: Is it possible to functionalize this for loop instead, perhaps into a recursive like function since we have many nested code blocks now that might make it harder for us to read.

Comment (rquitales) [reply provider/pkg/await/await.go:448]: We can iterate on this in a follow-up PR.

**Review by rquitales — APPROVED** [review]
